==29790== Memcheck, a memory error detector
==29790== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29790== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29790== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/engine-jit
==29790== 
==29790== 
==29790== HEAP SUMMARY:
==29790==     in use at exit: 26,712 bytes in 86 blocks
==29790==   total heap usage: 539 allocs, 453 frees, 101,948 bytes allocated
==29790== 
==29790== 8 bytes in 1 blocks are still reachable in loss record 1 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD31002: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29790==    by 0xD31002: rayon_core::util::leak (util.rs:5)
==29790==    by 0xD362FE: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29790==    by 0xD6C338: core::result::Result<T,E>::map (result.rs:519)
==29790==    by 0xD36399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790==    by 0xD597D0: std::sync::once::Once::call_once (once.rs:264)
==29790==    by 0xD362A6: rayon_core::registry::set_global_registry (registry.rs:194)
==29790== 
==29790== 32 bytes in 1 blocks are still reachable in loss record 2 of 30
==29790==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29790==    by 0x4E3F165: dlsym (dlsym.c:70)
==29790==    by 0x1C2BD13: fetch (weak.rs:61)
==29790==    by 0x1C2BD13: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29790==    by 0x1C2BD13: min_stack_size (thread.rs:449)
==29790==    by 0x1C2BD13: std::sys::unix::thread::Thread::new (thread.rs:49)
==29790==    by 0xD65D3B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29790==    by 0xD66F6B: std::thread::Builder::spawn (mod.rs:386)
==29790==    by 0xD35D88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29790==    by 0xD36E6F: rayon_core::registry::Registry::new (registry.rs:260)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790== 
==29790== 64 bytes in 4 blocks are still reachable in loss record 3 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD44CE6: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29790==    by 0xD44CE6: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29790==    by 0xD61593: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29790==    by 0xD616E3: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29790==    by 0xD616B3: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29790==    by 0xD433E6: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29790==    by 0xD372EE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29790==    by 0xD6FFFC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29790==    by 0xD40C4D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29790== 
==29790== 64 bytes in 4 blocks are still reachable in loss record 4 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1C2BC6C: alloc (alloc.rs:80)
==29790==    by 0x1C2BC6C: alloc (alloc.rs:174)
==29790==    by 0x1C2BC6C: exchange_malloc (alloc.rs:277)
==29790==    by 0x1C2BC6C: std::sys::unix::thread::Thread::new (thread.rs:44)
==29790==    by 0xD65D3B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29790==    by 0xD66F6B: std::thread::Builder::spawn (mod.rs:386)
==29790==    by 0xD35D88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29790==    by 0xD36E6F: rayon_core::registry::Registry::new (registry.rs:260)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790==    by 0xD597D0: std::sync::once::Once::call_once (once.rs:264)
==29790==    by 0xD362A6: rayon_core::registry::set_global_registry (registry.rs:194)
==29790== 
==29790== 72 bytes in 1 blocks are still reachable in loss record 5 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x181E3FB: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0x181E523: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0x181E35C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0x1821217: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==29790==    by 0x182154C: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==29790==    by 0x1812EC0: __static_ref_initialize (frame_info.rs:28)
==29790==    by 0x1812EC0: core::ops::function::FnOnce::call_once (function.rs:233)
==29790==    by 0x184ABDB: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29790==    by 0x1849554: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790==    by 0x18494D0: std::sync::once::Once::call_once (once.rs:264)
==29790==    by 0x180E2E8: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==29790==    by 0x180E2E8: __stability (lib.rs:142)
==29790==    by 0x180E2E8: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==29790== 
==29790== 96 bytes in 3 blocks are still reachable in loss record 6 of 30
==29790==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29790==    by 0x1BF829E: register_dtor (fast_thread_local.rs:33)
==29790==    by 0x1BF829E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29790==    by 0x1BF829E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29790==    by 0x1C1AA99: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29790==    by 0x1C1AA99: __getit (local.rs:175)
==29790==    by 0x1C1AA99: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29790==    by 0x1C1AA99: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29790==    by 0x1C1AA99: std::sys_common::thread_info::set (thread_info.rs:40)
==29790==    by 0xD66101: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29790==    by 0xD5A81E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29790==    by 0x1C2C089: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29790==    by 0x1C2C089: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29790==    by 0x1C2C089: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29790==    by 0x52516DA: start_thread (pthread_create.c:463)
==29790==    by 0x57A271E: clone (clone.S:95)
==29790== 
==29790== 96 bytes in 3 blocks are still reachable in loss record 7 of 30
==29790==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29790==    by 0xD9E071: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29790==    by 0xD9DF72: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29790==    by 0xD9E116: std::thread::local::fast::Key<T>::get (local.rs:410)
==29790==    by 0xD9DE6C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29790==    by 0xD47B14: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29790==    by 0xD4D4A2: crossbeam_epoch::default::with_handle (default.rs:43)
==29790==    by 0xD4D786: crossbeam_epoch::default::is_pinned (default.rs:30)
==29790==    by 0xD435AC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29790==    by 0xD39152: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29790==    by 0xD3453C: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29790== 
==29790== 160 bytes in 4 blocks are still reachable in loss record 8 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD6444F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29790==    by 0xD77C60: rayon_core::latch::LockLatch::new (latch.rs:230)
==29790==    by 0xD3809C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29790==    by 0xD5A731: core::ops::function::FnMut::call_mut (function.rs:154)
==29790==    by 0xD6FD13: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29790==    by 0xD536B3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29790==    by 0xD715C8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29790==    by 0xD6F4C9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29790== 
==29790== 160 bytes in 4 blocks are still reachable in loss record 9 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD6444F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29790==    by 0xD77C60: rayon_core::latch::LockLatch::new (latch.rs:230)
==29790==    by 0xD380B4: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29790==    by 0xD5A731: core::ops::function::FnMut::call_mut (function.rs:154)
==29790==    by 0xD6FD13: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29790==    by 0xD536B3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29790==    by 0xD715C8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29790==    by 0xD6F4C9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29790== 
==29790== 160 bytes in 4 blocks are still reachable in loss record 10 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD6444F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29790==    by 0xD67DC3: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29790==    by 0xD52AAE: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29790==    by 0xD4FEDD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29790==    by 0xD5134A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29790==    by 0xD6FEC0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29790==    by 0xD40A58: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29790==    by 0xD71699: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29790== 
==29790== 160 bytes in 4 blocks are still reachable in loss record 11 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1BF963E: alloc (alloc.rs:80)
==29790==    by 0x1BF963E: alloc (alloc.rs:174)
==29790==    by 0x1BF963E: exchange_malloc (alloc.rs:277)
==29790==    by 0x1BF963E: new<()> (mutex.rs:223)
==29790==    by 0x1BF963E: std::thread::Thread::new (mod.rs:1149)
==29790==    by 0xD65ADD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29790==    by 0xD66F6B: std::thread::Builder::spawn (mod.rs:386)
==29790==    by 0xD35D88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29790==    by 0xD36E6F: rayon_core::registry::Registry::new (registry.rs:260)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790==    by 0xD597D0: std::sync::once::Once::call_once (once.rs:264)
==29790==    by 0xD362A6: rayon_core::registry::set_global_registry (registry.rs:194)
==29790== 
==29790== 160 bytes in 4 blocks are still reachable in loss record 12 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD2F4A7: alloc::sync::Arc<T>::new (sync.rs:324)
==29790==    by 0xD65B7B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29790==    by 0xD66F6B: std::thread::Builder::spawn (mod.rs:386)
==29790==    by 0xD35D88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29790==    by 0xD36E6F: rayon_core::registry::Registry::new (registry.rs:260)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790== 
==29790== 192 bytes in 4 blocks are still reachable in loss record 13 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1C16736: alloc (alloc.rs:80)
==29790==    by 0x1C16736: alloc (alloc.rs:174)
==29790==    by 0x1C16736: exchange_malloc (alloc.rs:277)
==29790==    by 0x1C16736: std::sync::condvar::Condvar::new (condvar.rs:130)
==29790==    by 0xD77C7C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29790==    by 0xD3809C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29790==    by 0xD5A731: core::ops::function::FnMut::call_mut (function.rs:154)
==29790==    by 0xD6FD13: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29790==    by 0xD536B3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29790==    by 0xD715C8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29790==    by 0xD6F4C9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29790==    by 0xD570A1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29790==    by 0xD57D24: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29790==    by 0xD58CC6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29790== 
==29790== 192 bytes in 4 blocks are still reachable in loss record 14 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1C16736: alloc (alloc.rs:80)
==29790==    by 0x1C16736: alloc (alloc.rs:174)
==29790==    by 0x1C16736: exchange_malloc (alloc.rs:277)
==29790==    by 0x1C16736: std::sync::condvar::Condvar::new (condvar.rs:130)
==29790==    by 0xD77C7C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29790==    by 0xD380B4: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29790==    by 0xD5A731: core::ops::function::FnMut::call_mut (function.rs:154)
==29790==    by 0xD6FD13: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29790==    by 0xD536B3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29790==    by 0xD715C8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29790==    by 0xD6F4C9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29790==    by 0xD570A1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29790==    by 0xD57D24: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29790==    by 0xD58CC6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29790== 
==29790== 192 bytes in 4 blocks are still reachable in loss record 15 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1C16736: alloc (alloc.rs:80)
==29790==    by 0x1C16736: alloc (alloc.rs:174)
==29790==    by 0x1C16736: exchange_malloc (alloc.rs:277)
==29790==    by 0x1C16736: std::sync::condvar::Condvar::new (condvar.rs:130)
==29790==    by 0xD52ACA: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29790==    by 0xD4FEDD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29790==    by 0xD5134A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29790==    by 0xD6FEC0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29790==    by 0xD40A58: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29790==    by 0xD71699: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29790==    by 0xD6F2FA: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29790==    by 0xD57467: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29790==    by 0xD57C81: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29790==    by 0xD58C65: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29790== 
==29790== 192 bytes in 4 blocks are still reachable in loss record 16 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1BF96A2: alloc (alloc.rs:80)
==29790==    by 0x1BF96A2: alloc (alloc.rs:174)
==29790==    by 0x1BF96A2: exchange_malloc (alloc.rs:277)
==29790==    by 0x1BF96A2: new (condvar.rs:130)
==29790==    by 0x1BF96A2: std::thread::Thread::new (mod.rs:1150)
==29790==    by 0xD65ADD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29790==    by 0xD66F6B: std::thread::Builder::spawn (mod.rs:386)
==29790==    by 0xD35D88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29790==    by 0xD36E6F: rayon_core::registry::Registry::new (registry.rs:260)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790==    by 0xD597D0: std::sync::once::Once::call_once (once.rs:264)
==29790==    by 0xD362A6: rayon_core::registry::set_global_registry (registry.rs:194)
==29790== 
==29790== 320 bytes in 4 blocks are still reachable in loss record 17 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1BF96F1: alloc (alloc.rs:80)
==29790==    by 0x1BF96F1: alloc (alloc.rs:174)
==29790==    by 0x1BF96F1: exchange_malloc (alloc.rs:277)
==29790==    by 0x1BF96F1: new<std::thread::Inner> (sync.rs:324)
==29790==    by 0x1BF96F1: std::thread::Thread::new (mod.rs:1145)
==29790==    by 0xD65ADD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29790==    by 0xD66F6B: std::thread::Builder::spawn (mod.rs:386)
==29790==    by 0xD35D88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29790==    by 0xD36E6F: rayon_core::registry::Registry::new (registry.rs:260)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790==    by 0xD597D0: std::sync::once::Once::call_once (once.rs:264)
==29790==    by 0xD362A6: rayon_core::registry::set_global_registry (registry.rs:194)
==29790== 
==29790== 384 bytes in 1 blocks are still reachable in loss record 18 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xDC69DB: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xDC7283: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xDBDD9A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29790==    by 0xD7AA20: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29790==    by 0xD79373: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29790==    by 0xD7CF72: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29790==    by 0xD55E58: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29790==    by 0xD56FB7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29790==    by 0xD57D24: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29790==    by 0xD58CC6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29790==    by 0xD6F128: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29790== 
==29790== 416 bytes in 4 blocks are still reachable in loss record 19 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD65CA7: new<closure-0> (boxed.rs:177)
==29790==    by 0xD65CA7: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29790==    by 0xD66F6B: std::thread::Builder::spawn (mod.rs:386)
==29790==    by 0xD35D88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29790==    by 0xD36E6F: rayon_core::registry::Registry::new (registry.rs:260)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790== 
==29790== 512 bytes in 1 blocks are still reachable in loss record 20 of 30
==29790==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1C1C1A9: aligned_malloc (alloc.rs:95)
==29790==    by 0x1C1C1A9: alloc (alloc.rs:22)
==29790==    by 0x1C1C1A9: __rdl_alloc (alloc.rs:304)
==29790==    by 0xDC69DB: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xDC7283: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xDBDD9A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29790==    by 0xD7AD80: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29790==    by 0xD79273: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29790==    by 0xD7CED2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29790==    by 0xD55DF8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29790==    by 0xD573A7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29790==    by 0xD57C81: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29790== 
==29790== 640 bytes in 1 blocks are still reachable in loss record 21 of 30
==29790==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1C1C1A9: aligned_malloc (alloc.rs:95)
==29790==    by 0x1C1C1A9: alloc (alloc.rs:22)
==29790==    by 0x1C1C1A9: __rdl_alloc (alloc.rs:304)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD2F2D5: alloc::sync::Arc<T>::new (sync.rs:324)
==29790==    by 0xD36A67: rayon_core::registry::Registry::new (registry.rs:238)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790== 
==29790== 640 bytes in 1 blocks are still reachable in loss record 22 of 30
==29790==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1C1C1A9: aligned_malloc (alloc.rs:95)
==29790==    by 0x1C1C1A9: alloc (alloc.rs:22)
==29790==    by 0x1C1C1A9: __rdl_alloc (alloc.rs:304)
==29790==    by 0xDA28DB: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xDA2E23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xDA283C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD9EAB5: alloc::sync::Arc<T>::new (sync.rs:324)
==29790==    by 0xD9EFF9: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29790==    by 0xD9F026: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29790==    by 0xD9D519: __static_ref_initialize (default.rs:13)
==29790==    by 0xD9D519: core::ops::function::FnOnce::call_once (function.rs:233)
==29790==    by 0xD9D385: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29790==    by 0xD9E644: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790== 
==29790== 808 bytes in 1 blocks are still reachable in loss record 23 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x181E3FB: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0x181E523: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0x181E35C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0x182C5D0: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==29790==    by 0x182C5D0: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==29790==    by 0x1812ED9: core::ops::function::FnOnce::call_once (function.rs:233)
==29790==    by 0x181F61C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==29790==    by 0x1844EDE: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==29790==    by 0x18452B1: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==29790==    by 0x1846129: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==29790==    by 0x180DFFF: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==29790==    by 0xBD73D4: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==29790== 
==29790== 1,152 bytes in 4 blocks are possibly lost in loss record 24 of 30
==29790==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29790==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29790==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29790==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29790==    by 0x1C2BDBC: std::sys::unix::thread::Thread::new (thread.rs:66)
==29790==    by 0xD65D3B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29790==    by 0xD66F6B: std::thread::Builder::spawn (mod.rs:386)
==29790==    by 0xD35D88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29790==    by 0xD36E6F: rayon_core::registry::Registry::new (registry.rs:260)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790== 
==29790== 1,520 bytes in 1 blocks are still reachable in loss record 25 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD450C1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29790==    by 0xD450C1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29790==    by 0xD4394D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29790==    by 0xD36833: rayon_core::registry::Registry::new (registry.rs:242)
==29790==    by 0xD35FFD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29790==    by 0xD36389: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29790==    by 0xD59853: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29790==    by 0x1C16DE9: std::sync::once::Once::call_inner (once.rs:416)
==29790==    by 0xD597D0: std::sync::once::Once::call_once (once.rs:264)
==29790== 
==29790== 1,536 bytes in 4 blocks are still reachable in loss record 26 of 30
==29790==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0x1C1C1A9: aligned_malloc (alloc.rs:95)
==29790==    by 0x1C1C1A9: alloc (alloc.rs:22)
==29790==    by 0x1C1C1A9: __rdl_alloc (alloc.rs:304)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD2F0F5: alloc::sync::Arc<T>::new (sync.rs:324)
==29790==    by 0xD4347D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29790==    by 0xD372EE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29790==    by 0xD6FFFC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29790==    by 0xD40C4D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29790==    by 0xD71853: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29790== 
==29790== 2,008 bytes in 1 blocks are still reachable in loss record 27 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xDA28DB: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xDA2E23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xDA283C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD9B1F9: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29790==    by 0xD9B1F9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29790==    by 0xD9ABA5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29790==    by 0xD9AAF5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29790==    by 0xD9B3FB: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29790==    by 0xD967F3: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29790==    by 0xD9EFEB: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29790==    by 0xD9F026: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29790==    by 0xD9D519: __static_ref_initialize (default.rs:13)
==29790==    by 0xD9D519: core::ops::function::FnOnce::call_once (function.rs:233)
==29790== 
==29790== 4,096 bytes in 4 blocks are still reachable in loss record 28 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD7902D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29790==    by 0xD7C2A0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29790==    by 0xD7841E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29790==    by 0xD53C2E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29790==    by 0xD41E90: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29790==    by 0xD43369: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29790==    by 0xD372EE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29790==    by 0xD6FFFC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29790==    by 0xD40C4D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29790== 
==29790== 4,560 bytes in 3 blocks are still reachable in loss record 29 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xD5F83B: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xD60663: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xD5F79C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD450C1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29790==    by 0xD450C1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29790==    by 0xD4394D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29790==    by 0xD30ECC: rayon_core::job::JobFifo::new (job.rs:193)
==29790==    by 0xD3928A: rayon_core::registry::main_loop (registry.rs:806)
==29790==    by 0xD358BF: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29790==    by 0xD35F70: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29790==    by 0xD6E81F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29790==    by 0xD66DF0: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29790== 
==29790== 6,120 bytes in 3 blocks are still reachable in loss record 30 of 30
==29790==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29790==    by 0xDA28DB: alloc::alloc::alloc (alloc.rs:80)
==29790==    by 0xDA2E23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29790==    by 0xDA283C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29790==    by 0xD96229: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29790==    by 0xD96229: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29790==    by 0xD9AB45: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29790==    by 0xD9AAA5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29790==    by 0xD97092: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29790==    by 0xD9F04D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29790==    by 0xD9DE33: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29790==    by 0xD9D4F8: core::ops::function::FnOnce::call_once (function.rs:233)
==29790==    by 0xDA2FCB: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29790== 
==29790== LEAK SUMMARY:
==29790==    definitely lost: 0 bytes in 0 blocks
==29790==    indirectly lost: 0 bytes in 0 blocks
==29790==      possibly lost: 1,152 bytes in 4 blocks
==29790==    still reachable: 25,560 bytes in 82 blocks
==29790==         suppressed: 0 bytes in 0 blocks
==29790== 
==29790== For counts of detected and suppressed errors, rerun with: -v
==29790== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
