==29780== Memcheck, a memory error detector
==29780== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29780== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29780== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/engine-headless
==29780== 
--29780-- WARNING: unhandled amd64-linux syscall: 332
--29780-- You may be able to write your own handler.
--29780-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--29780-- Nevertheless we consider this a bug.  Please report
--29780-- it at http://valgrind.org/support/bug_reports.html.
==29780== 
==29780== HEAP SUMMARY:
==29780==     in use at exit: 29,456 bytes in 88 blocks
==29780==   total heap usage: 786 allocs, 698 frees, 135,542 bytes allocated
==29780== 
==29780== 8 bytes in 1 blocks are still reachable in loss record 1 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE03352: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29780==    by 0xE03352: rayon_core::util::leak (util.rs:5)
==29780==    by 0xE0864E: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29780==    by 0xE3E688: core::result::Result<T,E>::map (result.rs:519)
==29780==    by 0xE086E9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780==    by 0xE2BB20: std::sync::once::Once::call_once (once.rs:264)
==29780==    by 0xE085F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29780== 
==29780== 32 bytes in 1 blocks are still reachable in loss record 2 of 28
==29780==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29780==    by 0x4E3F165: dlsym (dlsym.c:70)
==29780==    by 0x1D6CDD3: fetch (weak.rs:61)
==29780==    by 0x1D6CDD3: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29780==    by 0x1D6CDD3: min_stack_size (thread.rs:449)
==29780==    by 0x1D6CDD3: std::sys::unix::thread::Thread::new (thread.rs:49)
==29780==    by 0xE3808B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29780==    by 0xE392BB: std::thread::Builder::spawn (mod.rs:386)
==29780==    by 0xE080D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29780==    by 0xE091BF: rayon_core::registry::Registry::new (registry.rs:260)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780== 
==29780== 64 bytes in 4 blocks are still reachable in loss record 3 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE17036: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29780==    by 0xE17036: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29780==    by 0xE338E3: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29780==    by 0xE33A33: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29780==    by 0xE33A03: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29780==    by 0xE15736: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29780==    by 0xE0963E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29780==    by 0xE4234C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29780==    by 0xE12F9D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29780== 
==29780== 64 bytes in 4 blocks are still reachable in loss record 4 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D6CD2C: alloc (alloc.rs:80)
==29780==    by 0x1D6CD2C: alloc (alloc.rs:174)
==29780==    by 0x1D6CD2C: exchange_malloc (alloc.rs:277)
==29780==    by 0x1D6CD2C: std::sys::unix::thread::Thread::new (thread.rs:44)
==29780==    by 0xE3808B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29780==    by 0xE392BB: std::thread::Builder::spawn (mod.rs:386)
==29780==    by 0xE080D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29780==    by 0xE091BF: rayon_core::registry::Registry::new (registry.rs:260)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780==    by 0xE2BB20: std::sync::once::Once::call_once (once.rs:264)
==29780==    by 0xE085F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29780== 
==29780== 128 bytes in 4 blocks are still reachable in loss record 5 of 28
==29780==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29780==    by 0x1D3935E: register_dtor (fast_thread_local.rs:33)
==29780==    by 0x1D3935E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29780==    by 0x1D3935E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29780==    by 0x1D5BB59: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29780==    by 0x1D5BB59: __getit (local.rs:175)
==29780==    by 0x1D5BB59: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29780==    by 0x1D5BB59: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29780==    by 0x1D5BB59: std::sys_common::thread_info::set (thread_info.rs:40)
==29780==    by 0xE38451: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29780==    by 0xE2CB6E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29780==    by 0x1D6D149: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29780==    by 0x1D6D149: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29780==    by 0x1D6D149: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29780==    by 0x52516DA: start_thread (pthread_create.c:463)
==29780==    by 0x57A271E: clone (clone.S:95)
==29780== 
==29780== 128 bytes in 4 blocks are still reachable in loss record 6 of 28
==29780==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29780==    by 0xE703C1: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29780==    by 0xE702C2: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29780==    by 0xE70466: std::thread::local::fast::Key<T>::get (local.rs:410)
==29780==    by 0xE701BC: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29780==    by 0xE19E64: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29780==    by 0xE1F7F2: crossbeam_epoch::default::with_handle (default.rs:43)
==29780==    by 0xE1FAD6: crossbeam_epoch::default::is_pinned (default.rs:30)
==29780==    by 0xE158FC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29780==    by 0xE0B4A2: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29780==    by 0xE0688C: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29780== 
==29780== 160 bytes in 4 blocks are still reachable in loss record 7 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE3679F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29780==    by 0xE49FB0: rayon_core::latch::LockLatch::new (latch.rs:230)
==29780==    by 0xE0A3EC: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29780==    by 0xE2CA81: core::ops::function::FnMut::call_mut (function.rs:154)
==29780==    by 0xE42063: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29780==    by 0xE25A03: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29780==    by 0xE43918: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29780==    by 0xE41819: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29780== 
==29780== 160 bytes in 4 blocks are still reachable in loss record 8 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE3679F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29780==    by 0xE49FB0: rayon_core::latch::LockLatch::new (latch.rs:230)
==29780==    by 0xE0A404: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29780==    by 0xE2CA81: core::ops::function::FnMut::call_mut (function.rs:154)
==29780==    by 0xE42063: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29780==    by 0xE25A03: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29780==    by 0xE43918: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29780==    by 0xE41819: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29780== 
==29780== 160 bytes in 4 blocks are still reachable in loss record 9 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE3679F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29780==    by 0xE3A113: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29780==    by 0xE24DFE: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29780==    by 0xE2222D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29780==    by 0xE2369A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29780==    by 0xE42210: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29780==    by 0xE12DA8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29780==    by 0xE439E9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29780== 
==29780== 160 bytes in 4 blocks are still reachable in loss record 10 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D3A6FE: alloc (alloc.rs:80)
==29780==    by 0x1D3A6FE: alloc (alloc.rs:174)
==29780==    by 0x1D3A6FE: exchange_malloc (alloc.rs:277)
==29780==    by 0x1D3A6FE: new<()> (mutex.rs:223)
==29780==    by 0x1D3A6FE: std::thread::Thread::new (mod.rs:1149)
==29780==    by 0xE37E2D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29780==    by 0xE392BB: std::thread::Builder::spawn (mod.rs:386)
==29780==    by 0xE080D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29780==    by 0xE091BF: rayon_core::registry::Registry::new (registry.rs:260)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780==    by 0xE2BB20: std::sync::once::Once::call_once (once.rs:264)
==29780==    by 0xE085F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29780== 
==29780== 160 bytes in 4 blocks are still reachable in loss record 11 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE017F7: alloc::sync::Arc<T>::new (sync.rs:324)
==29780==    by 0xE37ECB: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29780==    by 0xE392BB: std::thread::Builder::spawn (mod.rs:386)
==29780==    by 0xE080D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29780==    by 0xE091BF: rayon_core::registry::Registry::new (registry.rs:260)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780== 
==29780== 192 bytes in 4 blocks are still reachable in loss record 12 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D577F6: alloc (alloc.rs:80)
==29780==    by 0x1D577F6: alloc (alloc.rs:174)
==29780==    by 0x1D577F6: exchange_malloc (alloc.rs:277)
==29780==    by 0x1D577F6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29780==    by 0xE49FCC: rayon_core::latch::LockLatch::new (latch.rs:231)
==29780==    by 0xE0A3EC: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29780==    by 0xE2CA81: core::ops::function::FnMut::call_mut (function.rs:154)
==29780==    by 0xE42063: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29780==    by 0xE25A03: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29780==    by 0xE43918: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29780==    by 0xE41819: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29780==    by 0xE293F1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29780==    by 0xE2A074: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29780==    by 0xE2B016: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29780== 
==29780== 192 bytes in 4 blocks are still reachable in loss record 13 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D577F6: alloc (alloc.rs:80)
==29780==    by 0x1D577F6: alloc (alloc.rs:174)
==29780==    by 0x1D577F6: exchange_malloc (alloc.rs:277)
==29780==    by 0x1D577F6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29780==    by 0xE49FCC: rayon_core::latch::LockLatch::new (latch.rs:231)
==29780==    by 0xE0A404: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29780==    by 0xE2CA81: core::ops::function::FnMut::call_mut (function.rs:154)
==29780==    by 0xE42063: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29780==    by 0xE25A03: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29780==    by 0xE43918: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29780==    by 0xE41819: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29780==    by 0xE293F1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29780==    by 0xE2A074: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29780==    by 0xE2B016: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29780== 
==29780== 192 bytes in 4 blocks are still reachable in loss record 14 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D577F6: alloc (alloc.rs:80)
==29780==    by 0x1D577F6: alloc (alloc.rs:174)
==29780==    by 0x1D577F6: exchange_malloc (alloc.rs:277)
==29780==    by 0x1D577F6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29780==    by 0xE24E1A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29780==    by 0xE2222D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29780==    by 0xE2369A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29780==    by 0xE42210: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29780==    by 0xE12DA8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29780==    by 0xE439E9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29780==    by 0xE4164A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29780==    by 0xE297B7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29780==    by 0xE29FD1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29780==    by 0xE2AFB5: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29780== 
==29780== 192 bytes in 4 blocks are still reachable in loss record 15 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D3A762: alloc (alloc.rs:80)
==29780==    by 0x1D3A762: alloc (alloc.rs:174)
==29780==    by 0x1D3A762: exchange_malloc (alloc.rs:277)
==29780==    by 0x1D3A762: new (condvar.rs:130)
==29780==    by 0x1D3A762: std::thread::Thread::new (mod.rs:1150)
==29780==    by 0xE37E2D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29780==    by 0xE392BB: std::thread::Builder::spawn (mod.rs:386)
==29780==    by 0xE080D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29780==    by 0xE091BF: rayon_core::registry::Registry::new (registry.rs:260)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780==    by 0xE2BB20: std::sync::once::Once::call_once (once.rs:264)
==29780==    by 0xE085F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29780== 
==29780== 320 bytes in 4 blocks are still reachable in loss record 16 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D3A7B1: alloc (alloc.rs:80)
==29780==    by 0x1D3A7B1: alloc (alloc.rs:174)
==29780==    by 0x1D3A7B1: exchange_malloc (alloc.rs:277)
==29780==    by 0x1D3A7B1: new<std::thread::Inner> (sync.rs:324)
==29780==    by 0x1D3A7B1: std::thread::Thread::new (mod.rs:1145)
==29780==    by 0xE37E2D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29780==    by 0xE392BB: std::thread::Builder::spawn (mod.rs:386)
==29780==    by 0xE080D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29780==    by 0xE091BF: rayon_core::registry::Registry::new (registry.rs:260)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780==    by 0xE2BB20: std::sync::once::Once::call_once (once.rs:264)
==29780==    by 0xE085F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29780== 
==29780== 384 bytes in 1 blocks are still reachable in loss record 17 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE98D2B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE995D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE900EA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29780==    by 0xE4CD70: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29780==    by 0xE4B6C3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29780==    by 0xE4F2C2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29780==    by 0xE281A8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29780==    by 0xE29307: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29780==    by 0xE2A074: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29780==    by 0xE2B016: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29780==    by 0xE41478: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29780== 
==29780== 416 bytes in 4 blocks are still reachable in loss record 18 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE37FF7: new<closure-0> (boxed.rs:177)
==29780==    by 0xE37FF7: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29780==    by 0xE392BB: std::thread::Builder::spawn (mod.rs:386)
==29780==    by 0xE080D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29780==    by 0xE091BF: rayon_core::registry::Registry::new (registry.rs:260)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780== 
==29780== 512 bytes in 1 blocks are still reachable in loss record 19 of 28
==29780==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D5D269: aligned_malloc (alloc.rs:95)
==29780==    by 0x1D5D269: alloc (alloc.rs:22)
==29780==    by 0x1D5D269: __rdl_alloc (alloc.rs:304)
==29780==    by 0xE98D2B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE995D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE900EA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29780==    by 0xE4D0D0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29780==    by 0xE4B5C3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29780==    by 0xE4F222: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29780==    by 0xE28148: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29780==    by 0xE296F7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29780==    by 0xE29FD1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29780== 
==29780== 640 bytes in 1 blocks are still reachable in loss record 20 of 28
==29780==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D5D269: aligned_malloc (alloc.rs:95)
==29780==    by 0x1D5D269: alloc (alloc.rs:22)
==29780==    by 0x1D5D269: __rdl_alloc (alloc.rs:304)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE01625: alloc::sync::Arc<T>::new (sync.rs:324)
==29780==    by 0xE08DB7: rayon_core::registry::Registry::new (registry.rs:238)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780== 
==29780== 640 bytes in 1 blocks are still reachable in loss record 21 of 28
==29780==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D5D269: aligned_malloc (alloc.rs:95)
==29780==    by 0x1D5D269: alloc (alloc.rs:22)
==29780==    by 0x1D5D269: __rdl_alloc (alloc.rs:304)
==29780==    by 0xE74C2B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE75173: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE74B8C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE70E05: alloc::sync::Arc<T>::new (sync.rs:324)
==29780==    by 0xE71349: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29780==    by 0xE71376: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29780==    by 0xE6F869: __static_ref_initialize (default.rs:13)
==29780==    by 0xE6F869: core::ops::function::FnOnce::call_once (function.rs:233)
==29780==    by 0xE6F6D5: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29780==    by 0xE70994: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780== 
==29780== 1,152 bytes in 4 blocks are possibly lost in loss record 22 of 28
==29780==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29780==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29780==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29780==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29780==    by 0x1D6CE7C: std::sys::unix::thread::Thread::new (thread.rs:66)
==29780==    by 0xE3808B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29780==    by 0xE392BB: std::thread::Builder::spawn (mod.rs:386)
==29780==    by 0xE080D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29780==    by 0xE091BF: rayon_core::registry::Registry::new (registry.rs:260)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780== 
==29780== 1,520 bytes in 1 blocks are still reachable in loss record 23 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE17411: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29780==    by 0xE17411: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29780==    by 0xE15C9D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29780==    by 0xE08B83: rayon_core::registry::Registry::new (registry.rs:242)
==29780==    by 0xE0834D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29780==    by 0xE086D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29780==    by 0xE2BBA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29780==    by 0x1D57EA9: std::sync::once::Once::call_inner (once.rs:416)
==29780==    by 0xE2BB20: std::sync::once::Once::call_once (once.rs:264)
==29780== 
==29780== 1,536 bytes in 4 blocks are still reachable in loss record 24 of 28
==29780==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0x1D5D269: aligned_malloc (alloc.rs:95)
==29780==    by 0x1D5D269: alloc (alloc.rs:22)
==29780==    by 0x1D5D269: __rdl_alloc (alloc.rs:304)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE01445: alloc::sync::Arc<T>::new (sync.rs:324)
==29780==    by 0xE157CD: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29780==    by 0xE0963E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29780==    by 0xE4234C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29780==    by 0xE12F9D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29780==    by 0xE43BA3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29780== 
==29780== 2,008 bytes in 1 blocks are still reachable in loss record 25 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE74C2B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE75173: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE74B8C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE6D549: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29780==    by 0xE6D549: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29780==    by 0xE6CEF5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29780==    by 0xE6CE45: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29780==    by 0xE6D74B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29780==    by 0xE68B43: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29780==    by 0xE7133B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29780==    by 0xE71376: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29780==    by 0xE6F869: __static_ref_initialize (default.rs:13)
==29780==    by 0xE6F869: core::ops::function::FnOnce::call_once (function.rs:233)
==29780== 
==29780== 4,096 bytes in 4 blocks are still reachable in loss record 26 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE4B37D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29780==    by 0xE4E5F0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29780==    by 0xE4A76E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29780==    by 0xE25F7E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29780==    by 0xE141E0: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29780==    by 0xE156B9: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29780==    by 0xE0963E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29780==    by 0xE4234C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29780==    by 0xE12F9D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29780== 
==29780== 6,080 bytes in 4 blocks are still reachable in loss record 27 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE31B8B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE329B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE31AEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE17411: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29780==    by 0xE17411: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29780==    by 0xE15C9D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29780==    by 0xE0321C: rayon_core::job::JobFifo::new (job.rs:193)
==29780==    by 0xE0B5DA: rayon_core::registry::main_loop (registry.rs:806)
==29780==    by 0xE07C0F: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29780==    by 0xE082C0: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29780==    by 0xE40B6F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29780==    by 0xE39140: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29780== 
==29780== 8,160 bytes in 4 blocks are still reachable in loss record 28 of 28
==29780==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29780==    by 0xE74C2B: alloc::alloc::alloc (alloc.rs:80)
==29780==    by 0xE75173: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29780==    by 0xE74B8C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29780==    by 0xE68579: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29780==    by 0xE68579: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29780==    by 0xE6CE95: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29780==    by 0xE6CDF5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29780==    by 0xE693E2: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29780==    by 0xE7139D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29780==    by 0xE70183: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29780==    by 0xE6F848: core::ops::function::FnOnce::call_once (function.rs:233)
==29780==    by 0xE7531B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29780== 
==29780== LEAK SUMMARY:
==29780==    definitely lost: 0 bytes in 0 blocks
==29780==    indirectly lost: 0 bytes in 0 blocks
==29780==      possibly lost: 1,152 bytes in 4 blocks
==29780==    still reachable: 28,304 bytes in 84 blocks
==29780==         suppressed: 0 bytes in 0 blocks
==29780== 
==29780== For counts of detected and suppressed errors, rerun with: -v
==29780== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
