==22283== Memcheck, a memory error detector
==22283== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22283== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==22283== Command: /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors
==22283== 
==22283== Conditional jump or move depends on uninitialised value(s)
==22283==    at 0x68953D: wasmparser::validator::Validator::end (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x67F03C: wasmparser::validator::Validator::payload (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x67E2B1: wasmparser::validator::Validator::validate_all (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x297A4C: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x263338: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::validate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x579EB4: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25C1A1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25D31D: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25BD02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x72B6F2: {{closure}} (rt.rs:52)
==22283==    by 0x72B6F2: do_call<closure-0,i32> (panicking.rs:348)
==22283==    by 0x72B6F2: try<i32,closure-0> (panicking.rs:325)
==22283==    by 0x72B6F2: catch_unwind<closure-0,i32> (panic.rs:394)
==22283==    by 0x72B6F2: std::rt::lang_start_internal (rt.rs:51)
==22283==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==  Uninitialised value was created by a stack allocation
==22283==    at 0x297960: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== valgrind: Unrecognised instruction at address 0x4040016.
==22283==    at 0x4040016: ???
==22283==    by 0x4040041: ???
==22283==    by 0x4040095: ???
==22283==    by 0x6B6950: RegisterSetjmp (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6ABB67: std::thread::local::LocalKey<T>::with (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6B3064: wasmer_vm::trap::traphandlers::wasmer_call_trampoline (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25DE92: wasmer::native::NativeFunc<(),Rets>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25D796: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25BD02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x72B6F2: {{closure}} (rt.rs:52)
==22283==    by 0x72B6F2: do_call<closure-0,i32> (panicking.rs:348)
==22283==    by 0x72B6F2: try<i32,closure-0> (panicking.rs:325)
==22283==    by 0x72B6F2: catch_unwind<closure-0,i32> (panic.rs:394)
==22283==    by 0x72B6F2: std::rt::lang_start_internal (rt.rs:51)
==22283==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== Your program just tried to execute an instruction that Valgrind
==22283== did not recognise.  There are two possible reasons for this.
==22283== 1. Your program has a bug and erroneously jumped to a non-code
==22283==    location.  If you are running Memcheck and you just saw a
==22283==    warning about a bad jump, it's probably your program's fault.
==22283== 2. The instruction is legitimate but Valgrind doesn't handle it,
==22283==    i.e. it's Valgrind's fault.  If you think this is the case or
==22283==    you are not sure, please let us know and we'll try to fix it.
==22283== Either way, Valgrind will now raise a SIGILL signal which will
==22283== probably kill your program.
==22283== Warning: client switching stacks?  SP change: 0x4051f68 --> 0x1ffefff400
==22283==          to suppress, use: --max-stackframe=137354728600 or greater
==22283== 
==22283== HEAP SUMMARY:
==22283==     in use at exit: 30,384 bytes in 91 blocks
==22283==   total heap usage: 739 allocs, 648 frees, 127,257 bytes allocated
==22283== 
==22283== 16 bytes in 1 blocks are still reachable in loss record 1 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x6BD4B8: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x6C1CF6: backtrace::lock::lock (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6C9E40: backtrace::backtrace::trace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6BCA05: backtrace::capture::Backtrace::new_unresolved (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6AB9E9: std::thread::local::LocalKey<T>::with (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6B3410: wasmer_vm::trap::traphandlers::trap_handler (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x525C97F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.27.so)
==22283==    by 0x4040015: ???
==22283== 
==22283== 32 bytes in 1 blocks are still reachable in loss record 2 of 33
==22283==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==22283==    by 0x4E3F165: dlsym (dlsym.c:70)
==22283==    by 0x739CC3: fetch (weak.rs:61)
==22283==    by 0x739CC3: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==22283==    by 0x739CC3: min_stack_size (thread.rs:449)
==22283==    by 0x739CC3: std::sys::unix::thread::Thread::new (thread.rs:49)
==22283==    by 0x2DB246: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE4E6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DF0AF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 32 bytes in 1 blocks are still reachable in loss record 3 of 33
==22283==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==22283==    by 0x2ECCBD: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E46A2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DC1FB: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DFDF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DDECA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0B10: std::sys_common::backtrace::__rust_begin_short_backtrace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DB40E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x73A039: call_once<(),FnOnce<()>> (boxed.rs:1081)
==22283==    by 0x73A039: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==22283==    by 0x73A039: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==22283==    by 0x52516DA: start_thread (pthread_create.c:463)
==22283==    by 0x57A271E: clone (clone.S:95)
==22283== 
==22283== 40 bytes in 1 blocks are still reachable in loss record 4 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x6C949B: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6BD4A8: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x6C1CF6: backtrace::lock::lock (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6C9E40: backtrace::backtrace::trace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6BCA05: backtrace::capture::Backtrace::new_unresolved (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6AB9E9: std::thread::local::LocalKey<T>::with (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x6B3410: wasmer_vm::trap::traphandlers::trap_handler (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x525C97F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.27.so)
==22283==    by 0x4040015: ???
==22283== 
==22283== 64 bytes in 4 blocks are still reachable in loss record 5 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2E44FC: crossbeam_deque::deque::Worker<T>::new_lifo (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E54E7: core::iter::traits::iterator::Iterator::unzip (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE986: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2B14C1: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 64 bytes in 4 blocks are still reachable in loss record 6 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x739C1C: alloc (alloc.rs:80)
==22283==    by 0x739C1C: alloc (alloc.rs:174)
==22283==    by 0x739C1C: exchange_malloc (alloc.rs:277)
==22283==    by 0x739C1C: std::sys::unix::thread::Thread::new (thread.rs:44)
==22283==    by 0x2DB246: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE4E6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DF0AF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 72 bytes in 1 blocks are still reachable in loss record 7 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x640D7D: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x6449EB: wasmer_engine::trap::frame_info::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x284825: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x27EAF5: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x57A26E: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x578BE3: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25D473: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25BD02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x72B6F2: {{closure}} (rt.rs:52)
==22283==    by 0x72B6F2: do_call<closure-0,i32> (panicking.rs:348)
==22283==    by 0x72B6F2: try<i32,closure-0> (panicking.rs:325)
==22283==    by 0x72B6F2: catch_unwind<closure-0,i32> (panic.rs:394)
==22283==    by 0x72B6F2: std::rt::lang_start_internal (rt.rs:51)
==22283==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 96 bytes in 3 blocks are still reachable in loss record 8 of 33
==22283==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==22283==    by 0x2ECCBD: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E46A2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DC166: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DFDF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DDECA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0B10: std::sys_common::backtrace::__rust_begin_short_backtrace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DB40E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x73A039: call_once<(),FnOnce<()>> (boxed.rs:1081)
==22283==    by 0x73A039: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==22283==    by 0x73A039: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==22283==    by 0x52516DA: start_thread (pthread_create.c:463)
==22283==    by 0x57A271E: clone (clone.S:95)
==22283== 
==22283== 128 bytes in 4 blocks are still reachable in loss record 9 of 33
==22283==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==22283==    by 0x70624E: register_dtor (fast_thread_local.rs:33)
==22283==    by 0x70624E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==22283==    by 0x70624E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==22283==    by 0x728A49: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==22283==    by 0x728A49: __getit (local.rs:175)
==22283==    by 0x728A49: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==22283==    by 0x728A49: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==22283==    by 0x728A49: std::sys_common::thread_info::set (thread_info.rs:40)
==22283==    by 0x2DB3CC: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x73A039: call_once<(),FnOnce<()>> (boxed.rs:1081)
==22283==    by 0x73A039: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==22283==    by 0x73A039: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==22283==    by 0x52516DA: start_thread (pthread_create.c:463)
==22283==    by 0x57A271E: clone (clone.S:95)
==22283== 
==22283== 160 bytes in 4 blocks are still reachable in loss record 10 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2E262C: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DF9FB: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E5868: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0930: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DEA2A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 160 bytes in 4 blocks are still reachable in loss record 11 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2E262C: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DFA26: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E5868: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0930: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DEA2A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 160 bytes in 4 blocks are still reachable in loss record 12 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2E262C: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E56CB: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DEAA0: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2B14C1: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 160 bytes in 4 blocks are still reachable in loss record 13 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x7075EE: alloc (alloc.rs:80)
==22283==    by 0x7075EE: alloc (alloc.rs:174)
==22283==    by 0x7075EE: exchange_malloc (alloc.rs:277)
==22283==    by 0x7075EE: new<()> (mutex.rs:223)
==22283==    by 0x7075EE: std::thread::Thread::new (mod.rs:1149)
==22283==    by 0x2DB131: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE4E6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DF0AF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 160 bytes in 4 blocks are still reachable in loss record 14 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2DB153: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE4E6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DF0AF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2B14C1: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 192 bytes in 4 blocks are still reachable in loss record 15 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x7246E6: alloc (alloc.rs:80)
==22283==    by 0x7246E6: alloc (alloc.rs:174)
==22283==    by 0x7246E6: exchange_malloc (alloc.rs:277)
==22283==    by 0x7246E6: std::sync::condvar::Condvar::new (condvar.rs:130)
==22283==    by 0x2DFA06: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E5868: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0930: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DEA2A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 192 bytes in 4 blocks are still reachable in loss record 16 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x7246E6: alloc (alloc.rs:80)
==22283==    by 0x7246E6: alloc (alloc.rs:174)
==22283==    by 0x7246E6: exchange_malloc (alloc.rs:277)
==22283==    by 0x7246E6: std::sync::condvar::Condvar::new (condvar.rs:130)
==22283==    by 0x2DFA31: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E5868: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0930: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DEA2A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 192 bytes in 4 blocks are still reachable in loss record 17 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x7246E6: alloc (alloc.rs:80)
==22283==    by 0x7246E6: alloc (alloc.rs:174)
==22283==    by 0x7246E6: exchange_malloc (alloc.rs:277)
==22283==    by 0x7246E6: std::sync::condvar::Condvar::new (condvar.rs:130)
==22283==    by 0x2E56D1: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DEAA0: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2B14C1: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 192 bytes in 4 blocks are still reachable in loss record 18 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x707652: alloc (alloc.rs:80)
==22283==    by 0x707652: alloc (alloc.rs:174)
==22283==    by 0x707652: exchange_malloc (alloc.rs:277)
==22283==    by 0x707652: new (condvar.rs:130)
==22283==    by 0x707652: std::thread::Thread::new (mod.rs:1150)
==22283==    by 0x2DB131: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE4E6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DF0AF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 320 bytes in 4 blocks are still reachable in loss record 19 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x7076A1: alloc (alloc.rs:80)
==22283==    by 0x7076A1: alloc (alloc.rs:174)
==22283==    by 0x7076A1: exchange_malloc (alloc.rs:277)
==22283==    by 0x7076A1: new<std::thread::Inner> (sync.rs:324)
==22283==    by 0x7076A1: std::thread::Thread::new (mod.rs:1145)
==22283==    by 0x2DB131: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE4E6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DF0AF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 384 bytes in 1 blocks are still reachable in loss record 20 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2E3B4C: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E08EC: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DEA2A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2B14C1: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 416 bytes in 4 blocks are still reachable in loss record 21 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2DB1E8: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE4E6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DF0AF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2B14C1: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 512 bytes in 1 blocks are still reachable in loss record 22 of 33
==22283==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x72A159: aligned_malloc (alloc.rs:95)
==22283==    by 0x72A159: alloc (alloc.rs:22)
==22283==    by 0x72A159: __rdl_alloc (alloc.rs:304)
==22283==    by 0x2E3D66: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DEA5A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 640 bytes in 1 blocks are still reachable in loss record 23 of 33
==22283==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x72A159: aligned_malloc (alloc.rs:95)
==22283==    by 0x72A159: alloc (alloc.rs:22)
==22283==    by 0x72A159: __rdl_alloc (alloc.rs:304)
==22283==    by 0x2DEC96: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2B14C1: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 640 bytes in 1 blocks are still reachable in loss record 24 of 33
==22283==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x72A159: aligned_malloc (alloc.rs:95)
==22283==    by 0x72A159: alloc (alloc.rs:22)
==22283==    by 0x72A159: __rdl_alloc (alloc.rs:304)
==22283==    by 0x2ED0C2: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2ECD5D: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E46A2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DC166: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DFDF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DDECA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0B10: std::sys_common::backtrace::__rust_begin_short_backtrace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DB40E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 808 bytes in 1 blocks are still reachable in loss record 25 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x64C2DF: alloc::collections::btree::map::BTreeMap<K,V>::insert (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x644DF1: wasmer_engine::trap::frame_info::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x284825: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x27EAF5: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x57A26E: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x578BE3: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25D473: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x25BD02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x72B6F2: {{closure}} (rt.rs:52)
==22283==    by 0x72B6F2: do_call<closure-0,i32> (panicking.rs:348)
==22283==    by 0x72B6F2: try<i32,closure-0> (panicking.rs:325)
==22283==    by 0x72B6F2: catch_unwind<closure-0,i32> (panic.rs:394)
==22283==    by 0x72B6F2: std::rt::lang_start_internal (rt.rs:51)
==22283==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 1,152 bytes in 4 blocks are possibly lost in loss record 26 of 33
==22283==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==22283==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==22283==    by 0x5252227: allocate_stack (allocatestack.c:627)
==22283==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==22283==    by 0x739D6C: std::sys::unix::thread::Thread::new (thread.rs:66)
==22283==    by 0x2DB246: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE4E6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DF0AF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 1,520 bytes in 1 blocks are still reachable in loss record 27 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2DEAF2: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2B14C1: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x29DF01: <wasmer_compiler_cranelift::compiler::CraneliftCompiler as wasmer_compiler::compiler::Compiler>::compile_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x282768: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 1,536 bytes in 4 blocks are still reachable in loss record 28 of 33
==22283==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x72A159: aligned_malloc (alloc.rs:95)
==22283==    by 0x72A159: alloc (alloc.rs:22)
==22283==    by 0x72A159: __rdl_alloc (alloc.rs:304)
==22283==    by 0x2E45A0: crossbeam_deque::deque::Worker<T>::new_lifo (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E54E7: core::iter::traits::iterator::Iterator::unzip (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE986: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 2,008 bytes in 1 blocks are still reachable in loss record 29 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2EC80E: crossbeam_epoch::sync::queue::Queue<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2ED092: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2ECD5D: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E46A2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DC166: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DFDF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DDECA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0B10: std::sys_common::backtrace::__rust_begin_short_backtrace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DB40E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x73A039: call_once<(),FnOnce<()>> (boxed.rs:1081)
==22283==    by 0x73A039: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==22283==    by 0x73A039: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==22283== 
==22283== 2,040 bytes in 1 blocks are still reachable in loss record 30 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2EA0EF: crossbeam_epoch::internal::Local::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2ECCE4: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E46A2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DC1FB: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DFDF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DDECA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0B10: std::sys_common::backtrace::__rust_begin_short_backtrace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DB40E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x73A039: call_once<(),FnOnce<()>> (boxed.rs:1081)
==22283==    by 0x73A039: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==22283==    by 0x73A039: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==22283==    by 0x52516DA: start_thread (pthread_create.c:463)
==22283==    by 0x57A271E: clone (clone.S:95)
==22283== 
==22283== 4,096 bytes in 4 blocks are still reachable in loss record 31 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2E44E0: crossbeam_deque::deque::Worker<T>::new_lifo (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E54E7: core::iter::traits::iterator::Iterator::unzip (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DE986: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E2235: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x724D99: std::sync::once::Once::call_inner (once.rs:416)
==22283==    by 0x2DE665: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E1614: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x28AA11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x290F85: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x295488: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2B14C1: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283== 
==22283== 6,080 bytes in 4 blocks are still reachable in loss record 32 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2DD898: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0B10: std::sys_common::backtrace::__rust_begin_short_backtrace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DB40E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x73A039: call_once<(),FnOnce<()>> (boxed.rs:1081)
==22283==    by 0x73A039: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==22283==    by 0x73A039: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==22283==    by 0x52516DA: start_thread (pthread_create.c:463)
==22283==    by 0x57A271E: clone (clone.S:95)
==22283== 
==22283== 6,120 bytes in 3 blocks are still reachable in loss record 33 of 33
==22283==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22283==    by 0x2EA0EF: crossbeam_epoch::internal::Local::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2ECCE4: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E46A2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DC166: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DFDF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DDECA: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2E0B10: std::sys_common::backtrace::__rust_begin_short_backtrace (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x2DB40E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==22283==    by 0x73A039: call_once<(),FnOnce<()>> (boxed.rs:1081)
==22283==    by 0x73A039: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==22283==    by 0x73A039: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==22283==    by 0x52516DA: start_thread (pthread_create.c:463)
==22283==    by 0x57A271E: clone (clone.S:95)
==22283== 
==22283== LEAK SUMMARY:
==22283==    definitely lost: 0 bytes in 0 blocks
==22283==    indirectly lost: 0 bytes in 0 blocks
==22283==      possibly lost: 1,152 bytes in 4 blocks
==22283==    still reachable: 29,232 bytes in 87 blocks
==22283==         suppressed: 0 bytes in 0 blocks
==22283== 
==22283== For counts of detected and suppressed errors, rerun with: -v
==22283== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
