==29829== Memcheck, a memory error detector
==29829== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29829== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29829== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/exported-memory
==29829== 
==29829== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==29829== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==29829== 
==29829== HEAP SUMMARY:
==29829==     in use at exit: 30,336 bytes in 90 blocks
==29829==   total heap usage: 565 allocs, 475 frees, 112,623 bytes allocated
==29829== 
==29829== 8 bytes in 1 blocks are still reachable in loss record 1 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD32AA2: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29829==    by 0xD32AA2: rayon_core::util::leak (util.rs:5)
==29829==    by 0xD37D9E: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29829==    by 0xD6DDD8: core::result::Result<T,E>::map (result.rs:519)
==29829==    by 0xD37E39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829==    by 0xD5B270: std::sync::once::Once::call_once (once.rs:264)
==29829==    by 0xD37D46: rayon_core::registry::set_global_registry (registry.rs:194)
==29829== 
==29829== 32 bytes in 1 blocks are still reachable in loss record 2 of 30
==29829==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29829==    by 0x4E3F165: dlsym (dlsym.c:70)
==29829==    by 0x1C2D8B3: fetch (weak.rs:61)
==29829==    by 0x1C2D8B3: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29829==    by 0x1C2D8B3: min_stack_size (thread.rs:449)
==29829==    by 0x1C2D8B3: std::sys::unix::thread::Thread::new (thread.rs:49)
==29829==    by 0xD677DB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29829==    by 0xD68A0B: std::thread::Builder::spawn (mod.rs:386)
==29829==    by 0xD37828: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29829==    by 0xD3890F: rayon_core::registry::Registry::new (registry.rs:260)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829== 
==29829== 64 bytes in 4 blocks are still reachable in loss record 3 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD46786: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29829==    by 0xD46786: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29829==    by 0xD63033: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29829==    by 0xD63183: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29829==    by 0xD63153: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29829==    by 0xD44E86: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29829==    by 0xD38D8E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29829==    by 0xD71A9C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29829==    by 0xD426ED: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29829== 
==29829== 64 bytes in 4 blocks are still reachable in loss record 4 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1C2D80C: alloc (alloc.rs:80)
==29829==    by 0x1C2D80C: alloc (alloc.rs:174)
==29829==    by 0x1C2D80C: exchange_malloc (alloc.rs:277)
==29829==    by 0x1C2D80C: std::sys::unix::thread::Thread::new (thread.rs:44)
==29829==    by 0xD677DB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29829==    by 0xD68A0B: std::thread::Builder::spawn (mod.rs:386)
==29829==    by 0xD37828: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29829==    by 0xD3890F: rayon_core::registry::Registry::new (registry.rs:260)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829==    by 0xD5B270: std::sync::once::Once::call_once (once.rs:264)
==29829==    by 0xD37D46: rayon_core::registry::set_global_registry (registry.rs:194)
==29829== 
==29829== 72 bytes in 1 blocks are still reachable in loss record 5 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x181FF9B: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0x18200C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0x181FEFC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0x1822DB7: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==29829==    by 0x18230EC: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==29829==    by 0x1814A60: __static_ref_initialize (frame_info.rs:28)
==29829==    by 0x1814A60: core::ops::function::FnOnce::call_once (function.rs:233)
==29829==    by 0x184C77B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29829==    by 0x184B0F4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829==    by 0x184B070: std::sync::once::Once::call_once (once.rs:264)
==29829==    by 0x180FE88: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==29829==    by 0x180FE88: __stability (lib.rs:142)
==29829==    by 0x180FE88: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==29829== 
==29829== 128 bytes in 4 blocks are still reachable in loss record 6 of 30
==29829==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29829==    by 0x1BF9E3E: register_dtor (fast_thread_local.rs:33)
==29829==    by 0x1BF9E3E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29829==    by 0x1BF9E3E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29829==    by 0x1C1C639: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29829==    by 0x1C1C639: __getit (local.rs:175)
==29829==    by 0x1C1C639: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29829==    by 0x1C1C639: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29829==    by 0x1C1C639: std::sys_common::thread_info::set (thread_info.rs:40)
==29829==    by 0xD67BA1: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29829==    by 0xD5C2BE: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29829==    by 0x1C2DC29: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29829==    by 0x1C2DC29: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29829==    by 0x1C2DC29: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29829==    by 0x52516DA: start_thread (pthread_create.c:463)
==29829==    by 0x57A271E: clone (clone.S:95)
==29829== 
==29829== 128 bytes in 4 blocks are still reachable in loss record 7 of 30
==29829==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29829==    by 0xD9FB11: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29829==    by 0xD9FA12: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29829==    by 0xD9FBB6: std::thread::local::fast::Key<T>::get (local.rs:410)
==29829==    by 0xD9F90C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29829==    by 0xD495B4: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29829==    by 0xD4EF42: crossbeam_epoch::default::with_handle (default.rs:43)
==29829==    by 0xD4F226: crossbeam_epoch::default::is_pinned (default.rs:30)
==29829==    by 0xD4504C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29829==    by 0xD3ABF2: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29829==    by 0xD35FDC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29829== 
==29829== 160 bytes in 4 blocks are still reachable in loss record 8 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD65EEF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29829==    by 0xD79700: rayon_core::latch::LockLatch::new (latch.rs:230)
==29829==    by 0xD39B3C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29829==    by 0xD5C1D1: core::ops::function::FnMut::call_mut (function.rs:154)
==29829==    by 0xD717B3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29829==    by 0xD55153: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29829==    by 0xD73068: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29829==    by 0xD70F69: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29829== 
==29829== 160 bytes in 4 blocks are still reachable in loss record 9 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD65EEF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29829==    by 0xD79700: rayon_core::latch::LockLatch::new (latch.rs:230)
==29829==    by 0xD39B54: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29829==    by 0xD5C1D1: core::ops::function::FnMut::call_mut (function.rs:154)
==29829==    by 0xD717B3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29829==    by 0xD55153: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29829==    by 0xD73068: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29829==    by 0xD70F69: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29829== 
==29829== 160 bytes in 4 blocks are still reachable in loss record 10 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD65EEF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29829==    by 0xD69863: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29829==    by 0xD5454E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29829==    by 0xD5197D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29829==    by 0xD52DEA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29829==    by 0xD71960: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29829==    by 0xD424F8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29829==    by 0xD73139: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29829== 
==29829== 160 bytes in 4 blocks are still reachable in loss record 11 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1BFB1DE: alloc (alloc.rs:80)
==29829==    by 0x1BFB1DE: alloc (alloc.rs:174)
==29829==    by 0x1BFB1DE: exchange_malloc (alloc.rs:277)
==29829==    by 0x1BFB1DE: new<()> (mutex.rs:223)
==29829==    by 0x1BFB1DE: std::thread::Thread::new (mod.rs:1149)
==29829==    by 0xD6757D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29829==    by 0xD68A0B: std::thread::Builder::spawn (mod.rs:386)
==29829==    by 0xD37828: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29829==    by 0xD3890F: rayon_core::registry::Registry::new (registry.rs:260)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829==    by 0xD5B270: std::sync::once::Once::call_once (once.rs:264)
==29829==    by 0xD37D46: rayon_core::registry::set_global_registry (registry.rs:194)
==29829== 
==29829== 160 bytes in 4 blocks are still reachable in loss record 12 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD30F47: alloc::sync::Arc<T>::new (sync.rs:324)
==29829==    by 0xD6761B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29829==    by 0xD68A0B: std::thread::Builder::spawn (mod.rs:386)
==29829==    by 0xD37828: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29829==    by 0xD3890F: rayon_core::registry::Registry::new (registry.rs:260)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829== 
==29829== 192 bytes in 4 blocks are still reachable in loss record 13 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1C182D6: alloc (alloc.rs:80)
==29829==    by 0x1C182D6: alloc (alloc.rs:174)
==29829==    by 0x1C182D6: exchange_malloc (alloc.rs:277)
==29829==    by 0x1C182D6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29829==    by 0xD7971C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29829==    by 0xD39B3C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29829==    by 0xD5C1D1: core::ops::function::FnMut::call_mut (function.rs:154)
==29829==    by 0xD717B3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29829==    by 0xD55153: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29829==    by 0xD73068: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29829==    by 0xD70F69: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29829==    by 0xD58B41: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29829==    by 0xD597C4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29829==    by 0xD5A766: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29829== 
==29829== 192 bytes in 4 blocks are still reachable in loss record 14 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1C182D6: alloc (alloc.rs:80)
==29829==    by 0x1C182D6: alloc (alloc.rs:174)
==29829==    by 0x1C182D6: exchange_malloc (alloc.rs:277)
==29829==    by 0x1C182D6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29829==    by 0xD7971C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29829==    by 0xD39B54: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29829==    by 0xD5C1D1: core::ops::function::FnMut::call_mut (function.rs:154)
==29829==    by 0xD717B3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29829==    by 0xD55153: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29829==    by 0xD73068: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29829==    by 0xD70F69: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29829==    by 0xD58B41: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29829==    by 0xD597C4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29829==    by 0xD5A766: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29829== 
==29829== 192 bytes in 4 blocks are still reachable in loss record 15 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1C182D6: alloc (alloc.rs:80)
==29829==    by 0x1C182D6: alloc (alloc.rs:174)
==29829==    by 0x1C182D6: exchange_malloc (alloc.rs:277)
==29829==    by 0x1C182D6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29829==    by 0xD5456A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29829==    by 0xD5197D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29829==    by 0xD52DEA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29829==    by 0xD71960: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29829==    by 0xD424F8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29829==    by 0xD73139: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29829==    by 0xD70D9A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29829==    by 0xD58F07: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29829==    by 0xD59721: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29829==    by 0xD5A705: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29829== 
==29829== 192 bytes in 4 blocks are still reachable in loss record 16 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1BFB242: alloc (alloc.rs:80)
==29829==    by 0x1BFB242: alloc (alloc.rs:174)
==29829==    by 0x1BFB242: exchange_malloc (alloc.rs:277)
==29829==    by 0x1BFB242: new (condvar.rs:130)
==29829==    by 0x1BFB242: std::thread::Thread::new (mod.rs:1150)
==29829==    by 0xD6757D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29829==    by 0xD68A0B: std::thread::Builder::spawn (mod.rs:386)
==29829==    by 0xD37828: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29829==    by 0xD3890F: rayon_core::registry::Registry::new (registry.rs:260)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829==    by 0xD5B270: std::sync::once::Once::call_once (once.rs:264)
==29829==    by 0xD37D46: rayon_core::registry::set_global_registry (registry.rs:194)
==29829== 
==29829== 320 bytes in 4 blocks are still reachable in loss record 17 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1BFB291: alloc (alloc.rs:80)
==29829==    by 0x1BFB291: alloc (alloc.rs:174)
==29829==    by 0x1BFB291: exchange_malloc (alloc.rs:277)
==29829==    by 0x1BFB291: new<std::thread::Inner> (sync.rs:324)
==29829==    by 0x1BFB291: std::thread::Thread::new (mod.rs:1145)
==29829==    by 0xD6757D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29829==    by 0xD68A0B: std::thread::Builder::spawn (mod.rs:386)
==29829==    by 0xD37828: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29829==    by 0xD3890F: rayon_core::registry::Registry::new (registry.rs:260)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829==    by 0xD5B270: std::sync::once::Once::call_once (once.rs:264)
==29829==    by 0xD37D46: rayon_core::registry::set_global_registry (registry.rs:194)
==29829== 
==29829== 384 bytes in 1 blocks are still reachable in loss record 18 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xDC847B: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xDC8D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xDBF83A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29829==    by 0xD7C4C0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29829==    by 0xD7AE13: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29829==    by 0xD7EA12: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29829==    by 0xD578F8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29829==    by 0xD58A57: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29829==    by 0xD597C4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29829==    by 0xD5A766: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29829==    by 0xD70BC8: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29829== 
==29829== 416 bytes in 4 blocks are still reachable in loss record 19 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD67747: new<closure-0> (boxed.rs:177)
==29829==    by 0xD67747: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29829==    by 0xD68A0B: std::thread::Builder::spawn (mod.rs:386)
==29829==    by 0xD37828: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29829==    by 0xD3890F: rayon_core::registry::Registry::new (registry.rs:260)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829== 
==29829== 512 bytes in 1 blocks are still reachable in loss record 20 of 30
==29829==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1C1DD49: aligned_malloc (alloc.rs:95)
==29829==    by 0x1C1DD49: alloc (alloc.rs:22)
==29829==    by 0x1C1DD49: __rdl_alloc (alloc.rs:304)
==29829==    by 0xDC847B: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xDC8D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xDBF83A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29829==    by 0xD7C820: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29829==    by 0xD7AD13: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29829==    by 0xD7E972: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29829==    by 0xD57898: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29829==    by 0xD58E47: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29829==    by 0xD59721: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29829== 
==29829== 640 bytes in 1 blocks are still reachable in loss record 21 of 30
==29829==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1C1DD49: aligned_malloc (alloc.rs:95)
==29829==    by 0x1C1DD49: alloc (alloc.rs:22)
==29829==    by 0x1C1DD49: __rdl_alloc (alloc.rs:304)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD30D75: alloc::sync::Arc<T>::new (sync.rs:324)
==29829==    by 0xD38507: rayon_core::registry::Registry::new (registry.rs:238)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829== 
==29829== 640 bytes in 1 blocks are still reachable in loss record 22 of 30
==29829==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1C1DD49: aligned_malloc (alloc.rs:95)
==29829==    by 0x1C1DD49: alloc (alloc.rs:22)
==29829==    by 0x1C1DD49: __rdl_alloc (alloc.rs:304)
==29829==    by 0xDA437B: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xDA48C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xDA42DC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xDA0555: alloc::sync::Arc<T>::new (sync.rs:324)
==29829==    by 0xDA0A99: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29829==    by 0xDA0AC6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29829==    by 0xD9EFB9: __static_ref_initialize (default.rs:13)
==29829==    by 0xD9EFB9: core::ops::function::FnOnce::call_once (function.rs:233)
==29829==    by 0xD9EE25: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29829==    by 0xDA00E4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829== 
==29829== 808 bytes in 1 blocks are still reachable in loss record 23 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x181FF9B: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0x18200C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0x181FEFC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0x182E170: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==29829==    by 0x182E170: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==29829==    by 0x1814A79: core::ops::function::FnOnce::call_once (function.rs:233)
==29829==    by 0x18211BC: core::option::Option<T>::get_or_insert_with (option.rs:853)
==29829==    by 0x1846A7E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==29829==    by 0x1846E51: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==29829==    by 0x1847CC9: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==29829==    by 0x180FB9F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==29829==    by 0xBD8E74: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==29829== 
==29829== 1,152 bytes in 4 blocks are possibly lost in loss record 24 of 30
==29829==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29829==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29829==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29829==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29829==    by 0x1C2D95C: std::sys::unix::thread::Thread::new (thread.rs:66)
==29829==    by 0xD677DB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29829==    by 0xD68A0B: std::thread::Builder::spawn (mod.rs:386)
==29829==    by 0xD37828: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29829==    by 0xD3890F: rayon_core::registry::Registry::new (registry.rs:260)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829== 
==29829== 1,520 bytes in 1 blocks are still reachable in loss record 25 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD46B61: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29829==    by 0xD46B61: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29829==    by 0xD453ED: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29829==    by 0xD382D3: rayon_core::registry::Registry::new (registry.rs:242)
==29829==    by 0xD37A9D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29829==    by 0xD37E29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29829==    by 0xD5B2F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29829==    by 0x1C18989: std::sync::once::Once::call_inner (once.rs:416)
==29829==    by 0xD5B270: std::sync::once::Once::call_once (once.rs:264)
==29829== 
==29829== 1,536 bytes in 4 blocks are still reachable in loss record 26 of 30
==29829==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0x1C1DD49: aligned_malloc (alloc.rs:95)
==29829==    by 0x1C1DD49: alloc (alloc.rs:22)
==29829==    by 0x1C1DD49: __rdl_alloc (alloc.rs:304)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD30B95: alloc::sync::Arc<T>::new (sync.rs:324)
==29829==    by 0xD44F1D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29829==    by 0xD38D8E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29829==    by 0xD71A9C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29829==    by 0xD426ED: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29829==    by 0xD732F3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29829== 
==29829== 2,008 bytes in 1 blocks are still reachable in loss record 27 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xDA437B: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xDA48C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xDA42DC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD9CC99: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29829==    by 0xD9CC99: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29829==    by 0xD9C645: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29829==    by 0xD9C595: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29829==    by 0xD9CE9B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29829==    by 0xD98293: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29829==    by 0xDA0A8B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29829==    by 0xDA0AC6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29829==    by 0xD9EFB9: __static_ref_initialize (default.rs:13)
==29829==    by 0xD9EFB9: core::ops::function::FnOnce::call_once (function.rs:233)
==29829== 
==29829== 4,096 bytes in 4 blocks are still reachable in loss record 28 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD7AACD: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29829==    by 0xD7DD40: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29829==    by 0xD79EBE: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29829==    by 0xD556CE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29829==    by 0xD43930: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29829==    by 0xD44E09: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29829==    by 0xD38D8E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29829==    by 0xD71A9C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29829==    by 0xD426ED: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29829== 
==29829== 6,080 bytes in 4 blocks are still reachable in loss record 29 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xD612DB: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xD62103: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xD6123C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD46B61: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29829==    by 0xD46B61: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29829==    by 0xD453ED: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29829==    by 0xD3296C: rayon_core::job::JobFifo::new (job.rs:193)
==29829==    by 0xD3AD2A: rayon_core::registry::main_loop (registry.rs:806)
==29829==    by 0xD3735F: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29829==    by 0xD37A10: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29829==    by 0xD702BF: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29829==    by 0xD68890: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29829== 
==29829== 8,160 bytes in 4 blocks are still reachable in loss record 30 of 30
==29829==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29829==    by 0xDA437B: alloc::alloc::alloc (alloc.rs:80)
==29829==    by 0xDA48C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29829==    by 0xDA42DC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29829==    by 0xD97CC9: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29829==    by 0xD97CC9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29829==    by 0xD9C5E5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29829==    by 0xD9C545: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29829==    by 0xD98B32: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29829==    by 0xDA0AED: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29829==    by 0xD9F8D3: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29829==    by 0xD9EF98: core::ops::function::FnOnce::call_once (function.rs:233)
==29829==    by 0xDA4A6B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29829== 
==29829== LEAK SUMMARY:
==29829==    definitely lost: 0 bytes in 0 blocks
==29829==    indirectly lost: 0 bytes in 0 blocks
==29829==      possibly lost: 1,152 bytes in 4 blocks
==29829==    still reachable: 29,184 bytes in 86 blocks
==29829==         suppressed: 0 bytes in 0 blocks
==29829== 
==29829== For counts of detected and suppressed errors, rerun with: -v
==29829== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
