==29822== Memcheck, a memory error detector
==29822== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29822== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29822== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/exported-global
==29822== 
==29822== 
==29822== HEAP SUMMARY:
==29822==     in use at exit: 30,392 bytes in 92 blocks
==29822==   total heap usage: 850 allocs, 758 frees, 148,046 bytes allocated
==29822== 
==29822== 8 bytes in 1 blocks are still reachable in loss record 1 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD36012: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29822==    by 0xD36012: rayon_core::util::leak (util.rs:5)
==29822==    by 0xD3B30E: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29822==    by 0xD71348: core::result::Result<T,E>::map (result.rs:519)
==29822==    by 0xD3B3A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822==    by 0xD5E7E0: std::sync::once::Once::call_once (once.rs:264)
==29822==    by 0xD3B2B6: rayon_core::registry::set_global_registry (registry.rs:194)
==29822== 
==29822== 16 bytes in 1 blocks are still reachable in loss record 2 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1A4735B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0x1A48733: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0x1A472BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0x1A9EDFD: new<std::sync::mutex::Mutex<()>> (boxed.rs:177)
==29822==    by 0x1A9EDFD: backtrace::lock::lock::{{closure}} (lib.rs:134)
==29822==    by 0x1A9935F: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822==    by 0x1A992D8: std::sync::once::Once::call_once (once.rs:264)
==29822==    by 0x1A9ED32: backtrace::lock::lock (lib.rs:133)
==29822==    by 0x1A3A5EB: backtrace::backtrace::trace (mod.rs:52)
==29822==    by 0x1A7676C: backtrace::capture::Backtrace::create (capture.rs:176)
==29822==    by 0x1A766E3: backtrace::capture::Backtrace::new_unresolved (capture.rs:170)
==29822== 
==29822== 32 bytes in 1 blocks are still reachable in loss record 3 of 32
==29822==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29822==    by 0x4E3F165: dlsym (dlsym.c:70)
==29822==    by 0x1C30E23: fetch (weak.rs:61)
==29822==    by 0x1C30E23: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29822==    by 0x1C30E23: min_stack_size (thread.rs:449)
==29822==    by 0x1C30E23: std::sys::unix::thread::Thread::new (thread.rs:49)
==29822==    by 0xD6AD4B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29822==    by 0xD6BF7B: std::thread::Builder::spawn (mod.rs:386)
==29822==    by 0xD3AD98: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29822==    by 0xD3BE7F: rayon_core::registry::Registry::new (registry.rs:260)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822== 
==29822== 40 bytes in 1 blocks are still reachable in loss record 4 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1A4735B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0x1A48733: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0x1A472BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0x1A787AC: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29822==    by 0x1A9EDEE: backtrace::lock::lock::{{closure}} (lib.rs:134)
==29822==    by 0x1A9935F: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822==    by 0x1A992D8: std::sync::once::Once::call_once (once.rs:264)
==29822==    by 0x1A9ED32: backtrace::lock::lock (lib.rs:133)
==29822==    by 0x1A3A5EB: backtrace::backtrace::trace (mod.rs:52)
==29822==    by 0x1A7676C: backtrace::capture::Backtrace::create (capture.rs:176)
==29822== 
==29822== 64 bytes in 4 blocks are still reachable in loss record 5 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD49CF6: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29822==    by 0xD49CF6: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29822==    by 0xD665A3: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29822==    by 0xD666F3: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29822==    by 0xD666C3: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29822==    by 0xD483F6: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29822==    by 0xD3C2FE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29822==    by 0xD7500C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29822==    by 0xD45C5D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29822== 
==29822== 64 bytes in 4 blocks are still reachable in loss record 6 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1C30D7C: alloc (alloc.rs:80)
==29822==    by 0x1C30D7C: alloc (alloc.rs:174)
==29822==    by 0x1C30D7C: exchange_malloc (alloc.rs:277)
==29822==    by 0x1C30D7C: std::sys::unix::thread::Thread::new (thread.rs:44)
==29822==    by 0xD6AD4B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29822==    by 0xD6BF7B: std::thread::Builder::spawn (mod.rs:386)
==29822==    by 0xD3AD98: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29822==    by 0xD3BE7F: rayon_core::registry::Registry::new (registry.rs:260)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822==    by 0xD5E7E0: std::sync::once::Once::call_once (once.rs:264)
==29822==    by 0xD3B2B6: rayon_core::registry::set_global_registry (registry.rs:194)
==29822== 
==29822== 72 bytes in 1 blocks are still reachable in loss record 7 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x182350B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0x1823633: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0x182346C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0x1826327: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==29822==    by 0x182665C: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==29822==    by 0x1817FD0: __static_ref_initialize (frame_info.rs:28)
==29822==    by 0x1817FD0: core::ops::function::FnOnce::call_once (function.rs:233)
==29822==    by 0x184FCEB: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29822==    by 0x184E664: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822==    by 0x184E5E0: std::sync::once::Once::call_once (once.rs:264)
==29822==    by 0x18133F8: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==29822==    by 0x18133F8: __stability (lib.rs:142)
==29822==    by 0x18133F8: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==29822== 
==29822== 128 bytes in 4 blocks are still reachable in loss record 8 of 32
==29822==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29822==    by 0x1BFD3AE: register_dtor (fast_thread_local.rs:33)
==29822==    by 0x1BFD3AE: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29822==    by 0x1BFD3AE: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29822==    by 0x1C1FBA9: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29822==    by 0x1C1FBA9: __getit (local.rs:175)
==29822==    by 0x1C1FBA9: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29822==    by 0x1C1FBA9: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29822==    by 0x1C1FBA9: std::sys_common::thread_info::set (thread_info.rs:40)
==29822==    by 0xD6B111: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29822==    by 0xD5F82E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29822==    by 0x1C31199: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29822==    by 0x1C31199: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29822==    by 0x1C31199: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29822==    by 0x52516DA: start_thread (pthread_create.c:463)
==29822==    by 0x57A271E: clone (clone.S:95)
==29822== 
==29822== 128 bytes in 4 blocks are still reachable in loss record 9 of 32
==29822==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29822==    by 0xDA3081: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29822==    by 0xDA2F82: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29822==    by 0xDA3126: std::thread::local::fast::Key<T>::get (local.rs:410)
==29822==    by 0xDA2E7C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29822==    by 0xD4CB24: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29822==    by 0xD524B2: crossbeam_epoch::default::with_handle (default.rs:43)
==29822==    by 0xD52796: crossbeam_epoch::default::is_pinned (default.rs:30)
==29822==    by 0xD485BC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29822==    by 0xD3E162: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29822==    by 0xD3954C: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29822== 
==29822== 160 bytes in 4 blocks are still reachable in loss record 10 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD6945F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29822==    by 0xD7CC70: rayon_core::latch::LockLatch::new (latch.rs:230)
==29822==    by 0xD3D0AC: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29822==    by 0xD5F741: core::ops::function::FnMut::call_mut (function.rs:154)
==29822==    by 0xD74D23: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29822==    by 0xD586C3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29822==    by 0xD765D8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29822==    by 0xD744D9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29822== 
==29822== 160 bytes in 4 blocks are still reachable in loss record 11 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD6945F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29822==    by 0xD7CC70: rayon_core::latch::LockLatch::new (latch.rs:230)
==29822==    by 0xD3D0C4: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29822==    by 0xD5F741: core::ops::function::FnMut::call_mut (function.rs:154)
==29822==    by 0xD74D23: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29822==    by 0xD586C3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29822==    by 0xD765D8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29822==    by 0xD744D9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29822== 
==29822== 160 bytes in 4 blocks are still reachable in loss record 12 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD6945F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29822==    by 0xD6CDD3: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29822==    by 0xD57ABE: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29822==    by 0xD54EED: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29822==    by 0xD5635A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29822==    by 0xD74ED0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29822==    by 0xD45A68: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29822==    by 0xD766A9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29822== 
==29822== 160 bytes in 4 blocks are still reachable in loss record 13 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1BFE74E: alloc (alloc.rs:80)
==29822==    by 0x1BFE74E: alloc (alloc.rs:174)
==29822==    by 0x1BFE74E: exchange_malloc (alloc.rs:277)
==29822==    by 0x1BFE74E: new<()> (mutex.rs:223)
==29822==    by 0x1BFE74E: std::thread::Thread::new (mod.rs:1149)
==29822==    by 0xD6AAED: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29822==    by 0xD6BF7B: std::thread::Builder::spawn (mod.rs:386)
==29822==    by 0xD3AD98: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29822==    by 0xD3BE7F: rayon_core::registry::Registry::new (registry.rs:260)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822==    by 0xD5E7E0: std::sync::once::Once::call_once (once.rs:264)
==29822==    by 0xD3B2B6: rayon_core::registry::set_global_registry (registry.rs:194)
==29822== 
==29822== 160 bytes in 4 blocks are still reachable in loss record 14 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD344B7: alloc::sync::Arc<T>::new (sync.rs:324)
==29822==    by 0xD6AB8B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29822==    by 0xD6BF7B: std::thread::Builder::spawn (mod.rs:386)
==29822==    by 0xD3AD98: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29822==    by 0xD3BE7F: rayon_core::registry::Registry::new (registry.rs:260)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822== 
==29822== 192 bytes in 4 blocks are still reachable in loss record 15 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1C1B846: alloc (alloc.rs:80)
==29822==    by 0x1C1B846: alloc (alloc.rs:174)
==29822==    by 0x1C1B846: exchange_malloc (alloc.rs:277)
==29822==    by 0x1C1B846: std::sync::condvar::Condvar::new (condvar.rs:130)
==29822==    by 0xD7CC8C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29822==    by 0xD3D0AC: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29822==    by 0xD5F741: core::ops::function::FnMut::call_mut (function.rs:154)
==29822==    by 0xD74D23: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29822==    by 0xD586C3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29822==    by 0xD765D8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29822==    by 0xD744D9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29822==    by 0xD5C0B1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29822==    by 0xD5CD34: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29822==    by 0xD5DCD6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29822== 
==29822== 192 bytes in 4 blocks are still reachable in loss record 16 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1C1B846: alloc (alloc.rs:80)
==29822==    by 0x1C1B846: alloc (alloc.rs:174)
==29822==    by 0x1C1B846: exchange_malloc (alloc.rs:277)
==29822==    by 0x1C1B846: std::sync::condvar::Condvar::new (condvar.rs:130)
==29822==    by 0xD7CC8C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29822==    by 0xD3D0C4: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29822==    by 0xD5F741: core::ops::function::FnMut::call_mut (function.rs:154)
==29822==    by 0xD74D23: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29822==    by 0xD586C3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29822==    by 0xD765D8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29822==    by 0xD744D9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29822==    by 0xD5C0B1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29822==    by 0xD5CD34: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29822==    by 0xD5DCD6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29822== 
==29822== 192 bytes in 4 blocks are still reachable in loss record 17 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1C1B846: alloc (alloc.rs:80)
==29822==    by 0x1C1B846: alloc (alloc.rs:174)
==29822==    by 0x1C1B846: exchange_malloc (alloc.rs:277)
==29822==    by 0x1C1B846: std::sync::condvar::Condvar::new (condvar.rs:130)
==29822==    by 0xD57ADA: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29822==    by 0xD54EED: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29822==    by 0xD5635A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29822==    by 0xD74ED0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29822==    by 0xD45A68: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29822==    by 0xD766A9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29822==    by 0xD7430A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29822==    by 0xD5C477: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29822==    by 0xD5CC91: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29822==    by 0xD5DC75: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29822== 
==29822== 192 bytes in 4 blocks are still reachable in loss record 18 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1BFE7B2: alloc (alloc.rs:80)
==29822==    by 0x1BFE7B2: alloc (alloc.rs:174)
==29822==    by 0x1BFE7B2: exchange_malloc (alloc.rs:277)
==29822==    by 0x1BFE7B2: new (condvar.rs:130)
==29822==    by 0x1BFE7B2: std::thread::Thread::new (mod.rs:1150)
==29822==    by 0xD6AAED: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29822==    by 0xD6BF7B: std::thread::Builder::spawn (mod.rs:386)
==29822==    by 0xD3AD98: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29822==    by 0xD3BE7F: rayon_core::registry::Registry::new (registry.rs:260)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822==    by 0xD5E7E0: std::sync::once::Once::call_once (once.rs:264)
==29822==    by 0xD3B2B6: rayon_core::registry::set_global_registry (registry.rs:194)
==29822== 
==29822== 320 bytes in 4 blocks are still reachable in loss record 19 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1BFE801: alloc (alloc.rs:80)
==29822==    by 0x1BFE801: alloc (alloc.rs:174)
==29822==    by 0x1BFE801: exchange_malloc (alloc.rs:277)
==29822==    by 0x1BFE801: new<std::thread::Inner> (sync.rs:324)
==29822==    by 0x1BFE801: std::thread::Thread::new (mod.rs:1145)
==29822==    by 0xD6AAED: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29822==    by 0xD6BF7B: std::thread::Builder::spawn (mod.rs:386)
==29822==    by 0xD3AD98: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29822==    by 0xD3BE7F: rayon_core::registry::Registry::new (registry.rs:260)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822==    by 0xD5E7E0: std::sync::once::Once::call_once (once.rs:264)
==29822==    by 0xD3B2B6: rayon_core::registry::set_global_registry (registry.rs:194)
==29822== 
==29822== 384 bytes in 1 blocks are still reachable in loss record 20 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xDCB9EB: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xDCC293: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xDC2DAA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29822==    by 0xD7FA30: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29822==    by 0xD7E383: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29822==    by 0xD81F82: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29822==    by 0xD5AE68: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29822==    by 0xD5BFC7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29822==    by 0xD5CD34: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29822==    by 0xD5DCD6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29822==    by 0xD74138: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29822== 
==29822== 416 bytes in 4 blocks are still reachable in loss record 21 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD6ACB7: new<closure-0> (boxed.rs:177)
==29822==    by 0xD6ACB7: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29822==    by 0xD6BF7B: std::thread::Builder::spawn (mod.rs:386)
==29822==    by 0xD3AD98: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29822==    by 0xD3BE7F: rayon_core::registry::Registry::new (registry.rs:260)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822== 
==29822== 512 bytes in 1 blocks are still reachable in loss record 22 of 32
==29822==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1C212B9: aligned_malloc (alloc.rs:95)
==29822==    by 0x1C212B9: alloc (alloc.rs:22)
==29822==    by 0x1C212B9: __rdl_alloc (alloc.rs:304)
==29822==    by 0xDCB9EB: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xDCC293: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xDC2DAA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29822==    by 0xD7FD90: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29822==    by 0xD7E283: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29822==    by 0xD81EE2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29822==    by 0xD5AE08: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29822==    by 0xD5C3B7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29822==    by 0xD5CC91: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29822== 
==29822== 640 bytes in 1 blocks are still reachable in loss record 23 of 32
==29822==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1C212B9: aligned_malloc (alloc.rs:95)
==29822==    by 0x1C212B9: alloc (alloc.rs:22)
==29822==    by 0x1C212B9: __rdl_alloc (alloc.rs:304)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD342E5: alloc::sync::Arc<T>::new (sync.rs:324)
==29822==    by 0xD3BA77: rayon_core::registry::Registry::new (registry.rs:238)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822== 
==29822== 640 bytes in 1 blocks are still reachable in loss record 24 of 32
==29822==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1C212B9: aligned_malloc (alloc.rs:95)
==29822==    by 0x1C212B9: alloc (alloc.rs:22)
==29822==    by 0x1C212B9: __rdl_alloc (alloc.rs:304)
==29822==    by 0xDA78EB: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xDA7E33: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xDA784C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xDA3AC5: alloc::sync::Arc<T>::new (sync.rs:324)
==29822==    by 0xDA4009: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29822==    by 0xDA4036: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29822==    by 0xDA2529: __static_ref_initialize (default.rs:13)
==29822==    by 0xDA2529: core::ops::function::FnOnce::call_once (function.rs:233)
==29822==    by 0xDA2395: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29822==    by 0xDA3654: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822== 
==29822== 808 bytes in 1 blocks are still reachable in loss record 25 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x182350B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0x1823633: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0x182346C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0x18316E0: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==29822==    by 0x18316E0: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==29822==    by 0x1817FE9: core::ops::function::FnOnce::call_once (function.rs:233)
==29822==    by 0x182472C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==29822==    by 0x1849FEE: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==29822==    by 0x184A3C1: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==29822==    by 0x184B239: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==29822==    by 0x181310F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==29822==    by 0xBDC3E4: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==29822== 
==29822== 1,152 bytes in 4 blocks are possibly lost in loss record 26 of 32
==29822==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29822==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29822==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29822==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29822==    by 0x1C30ECC: std::sys::unix::thread::Thread::new (thread.rs:66)
==29822==    by 0xD6AD4B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29822==    by 0xD6BF7B: std::thread::Builder::spawn (mod.rs:386)
==29822==    by 0xD3AD98: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29822==    by 0xD3BE7F: rayon_core::registry::Registry::new (registry.rs:260)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822== 
==29822== 1,520 bytes in 1 blocks are still reachable in loss record 27 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD4A0D1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29822==    by 0xD4A0D1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29822==    by 0xD4895D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29822==    by 0xD3B843: rayon_core::registry::Registry::new (registry.rs:242)
==29822==    by 0xD3B00D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29822==    by 0xD3B399: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29822==    by 0xD5E863: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29822==    by 0x1C1BEF9: std::sync::once::Once::call_inner (once.rs:416)
==29822==    by 0xD5E7E0: std::sync::once::Once::call_once (once.rs:264)
==29822== 
==29822== 1,536 bytes in 4 blocks are still reachable in loss record 28 of 32
==29822==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0x1C212B9: aligned_malloc (alloc.rs:95)
==29822==    by 0x1C212B9: alloc (alloc.rs:22)
==29822==    by 0x1C212B9: __rdl_alloc (alloc.rs:304)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD34105: alloc::sync::Arc<T>::new (sync.rs:324)
==29822==    by 0xD4848D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29822==    by 0xD3C2FE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29822==    by 0xD7500C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29822==    by 0xD45C5D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29822==    by 0xD76863: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29822== 
==29822== 2,008 bytes in 1 blocks are still reachable in loss record 29 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xDA78EB: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xDA7E33: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xDA784C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xDA0209: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29822==    by 0xDA0209: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29822==    by 0xD9FBB5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29822==    by 0xD9FB05: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29822==    by 0xDA040B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29822==    by 0xD9B803: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29822==    by 0xDA3FFB: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29822==    by 0xDA4036: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29822==    by 0xDA2529: __static_ref_initialize (default.rs:13)
==29822==    by 0xDA2529: core::ops::function::FnOnce::call_once (function.rs:233)
==29822== 
==29822== 4,096 bytes in 4 blocks are still reachable in loss record 30 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD7E03D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29822==    by 0xD812B0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29822==    by 0xD7D42E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29822==    by 0xD58C3E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29822==    by 0xD46EA0: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29822==    by 0xD48379: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29822==    by 0xD3C2FE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29822==    by 0xD7500C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29822==    by 0xD45C5D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29822== 
==29822== 6,080 bytes in 4 blocks are still reachable in loss record 31 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xD6484B: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xD65673: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xD647AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD4A0D1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29822==    by 0xD4A0D1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29822==    by 0xD4895D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29822==    by 0xD35EDC: rayon_core::job::JobFifo::new (job.rs:193)
==29822==    by 0xD3E29A: rayon_core::registry::main_loop (registry.rs:806)
==29822==    by 0xD3A8CF: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29822==    by 0xD3AF80: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29822==    by 0xD7382F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29822==    by 0xD6BE00: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29822== 
==29822== 8,160 bytes in 4 blocks are still reachable in loss record 32 of 32
==29822==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29822==    by 0xDA78EB: alloc::alloc::alloc (alloc.rs:80)
==29822==    by 0xDA7E33: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29822==    by 0xDA784C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29822==    by 0xD9B239: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29822==    by 0xD9B239: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29822==    by 0xD9FB55: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29822==    by 0xD9FAB5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29822==    by 0xD9C0A2: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29822==    by 0xDA405D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29822==    by 0xDA2E43: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29822==    by 0xDA2508: core::ops::function::FnOnce::call_once (function.rs:233)
==29822==    by 0xDA7FDB: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29822== 
==29822== LEAK SUMMARY:
==29822==    definitely lost: 0 bytes in 0 blocks
==29822==    indirectly lost: 0 bytes in 0 blocks
==29822==      possibly lost: 1,152 bytes in 4 blocks
==29822==    still reachable: 29,240 bytes in 88 blocks
==29822==         suppressed: 0 bytes in 0 blocks
==29822== 
==29822== For counts of detected and suppressed errors, rerun with: -v
==29822== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
