==13729== Memcheck, a memory error detector
==13729== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13729== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==13729== Command: /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function
==13729== 
==13729== Conditional jump or move depends on uninitialised value(s)
==13729==    at 0x68B97D: wasmparser::validator::Validator::end (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x68147C: wasmparser::validator::Validator::payload (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x6806F1: wasmparser::validator::Validator::validate_all (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x299BBC: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x265258: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::validate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BB54: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729==    by 0x25EC51: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==  Uninitialised value was created by a stack allocation
==13729==    at 0x299AD0: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 
==13729== HEAP SUMMARY:
==13729==     in use at exit: 28,144 bytes in 99 blocks
==13729==   total heap usage: 536 allocs, 437 frees, 101,810 bytes allocated
==13729== 
==13729== 3 bytes in 1 blocks are still reachable in loss record 1 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x65D86F: wasmer_compiler::translator::environ::ModuleEnvironment::declare_func_export (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65A53B: wasmer_compiler::translator::sections::parse_export_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x666D0D: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65CCB8: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284194: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729== 
==13729== 4 bytes in 1 blocks are still reachable in loss record 2 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x661CF0: alloc::raw_vec::RawVec<T,A>::reserve_exact (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x6592E6: wasmer_compiler::translator::sections::parse_function_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x666784: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65CCB8: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284194: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729== 
==13729== 5 bytes in 1 blocks are still reachable in loss record 3 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x65DCEF: wasmer_compiler::translator::environ::ModuleEnvironment::declare_function_name (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65BCE2: wasmer_compiler::translator::sections::parse_name_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x666F00: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65CCB8: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284194: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729== 
==13729== 8 bytes in 1 blocks are still reachable in loss record 4 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x662AE1: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65879F: wasmer_compiler::translator::sections::parse_type_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x666A9F: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65CCB8: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284194: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729== 
==13729== 8 bytes in 1 blocks are still reachable in loss record 5 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x662AE1: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x6587F4: wasmer_compiler::translator::sections::parse_type_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x666A9F: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65CCB8: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284194: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729== 
==13729== 8 bytes in 1 blocks are still reachable in loss record 6 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2E430A: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2A0051: <wasmer_compiler_cranelift::compiler::CraneliftCompiler as wasmer_compiler::compiler::Compiler>::compile_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284678: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 8 bytes in 1 blocks are indirectly lost in loss record 7 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2635F6: <alloc::boxed::Box<[T]> as core::clone::Clone>::clone (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x280A5A: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BF0D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x581702: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DCF1: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729==    by 0x25EC51: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 8 bytes in 1 blocks are indirectly lost in loss record 8 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x263506: <alloc::boxed::Box<[T]> as core::clone::Clone>::clone (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x280A87: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BF0D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x581702: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DCF1: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729==    by 0x25EC51: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 32 bytes in 1 blocks are still reachable in loss record 9 of 43
==13729==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==13729==    by 0x4E3F165: dlsym (dlsym.c:70)
==13729==    by 0x73C083: fetch (weak.rs:61)
==13729==    by 0x73C083: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==13729==    by 0x73C083: min_stack_size (thread.rs:449)
==13729==    by 0x73C083: std::sys::unix::thread::Thread::new (thread.rs:49)
==13729==    by 0x2DD3A6: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0726: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E12DF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 48 bytes in 1 blocks are still reachable in loss record 10 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x661BF7: alloc::raw_vec::RawVec<T,A>::reserve_exact (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x6585A7: wasmer_compiler::translator::sections::parse_type_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x666A9F: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65CCB8: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284194: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729== 
==13729== 52 bytes in 1 blocks are possibly lost in loss record 11 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x655AC2: hashbrown::raw::inner::RawTable<T>::fallible_with_capacity (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x6554DE: _ZN9hashbrown3raw5inner17RawTable$LT$T$GT$14reserve_rehash17he29be5fc862d84d8E.llvm.8588116468508767673 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65A671: wasmer_compiler::translator::sections::parse_export_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x666D0D: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65CCB8: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284194: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 64 bytes in 4 blocks are still reachable in loss record 12 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2E690C: crossbeam_deque::deque::Worker<T>::new_lifo (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E7787: core::iter::traits::iterator::Iterator::unzip (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0BB6: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 64 bytes in 4 blocks are still reachable in loss record 13 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x73BFDC: alloc (alloc.rs:80)
==13729==    by 0x73BFDC: alloc (alloc.rs:174)
==13729==    by 0x73BFDC: exchange_malloc (alloc.rs:277)
==13729==    by 0x73BFDC: std::sys::unix::thread::Thread::new (thread.rs:44)
==13729==    by 0x2DD3A6: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0726: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E12DF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 72 bytes in 1 blocks are still reachable in loss record 14 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x6431BD: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x646E2B: wasmer_engine::trap::frame_info::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x286735: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x280A15: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BF0D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x581702: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DCF1: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729==    by 0x25EC51: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 88 bytes in 1 blocks are still reachable in loss record 15 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x66509F: hashbrown::raw::RawTable<T>::reserve_rehash (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x665442: hashbrown::raw::RawTable<T>::insert (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x654654: hashbrown::map::HashMap<K,V,S>::insert (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65DD74: wasmer_compiler::translator::environ::ModuleEnvironment::declare_function_name (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65BCE2: wasmer_compiler::translator::sections::parse_name_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x666F00: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65CCB8: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284194: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 96 bytes in 3 blocks are still reachable in loss record 16 of 43
==13729==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==13729==    by 0x70860E: register_dtor (fast_thread_local.rs:33)
==13729==    by 0x70860E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==13729==    by 0x70860E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==13729==    by 0x72AE09: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==13729==    by 0x72AE09: __getit (local.rs:175)
==13729==    by 0x72AE09: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==13729==    by 0x72AE09: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==13729==    by 0x72AE09: std::sys_common::thread_info::set (thread_info.rs:40)
==13729==    by 0x2DD52C: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x73C3F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13729==    by 0x73C3F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13729==    by 0x73C3F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13729==    by 0x52516DA: start_thread (pthread_create.c:463)
==13729==    by 0x57A271E: clone (clone.S:95)
==13729== 
==13729== 96 bytes in 3 blocks are still reachable in loss record 17 of 43
==13729==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==13729==    by 0x2EEFDD: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E6AB2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2DE3B6: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E1FF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E010A: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2BA0: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2DD56E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x73C3F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13729==    by 0x73C3F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13729==    by 0x73C3F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13729==    by 0x52516DA: start_thread (pthread_create.c:463)
==13729==    by 0x57A271E: clone (clone.S:95)
==13729== 
==13729== 120 bytes in 1 blocks are still reachable in loss record 18 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x661AF7: alloc::raw_vec::RawVec<T,A>::reserve_exact (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65A3C3: wasmer_compiler::translator::sections::parse_export_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x666D0D: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x65CCB8: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284194: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729== 
==13729== 160 bytes in 4 blocks are still reachable in loss record 19 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2E459C: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E1BFB: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E79E8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2B30: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0C5A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 160 bytes in 4 blocks are still reachable in loss record 20 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2E459C: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E1C26: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E79E8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2B30: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0C5A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 160 bytes in 4 blocks are still reachable in loss record 21 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2E459C: std::sync::mutex::Mutex<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E7BAB: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0CD0: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 160 bytes in 4 blocks are still reachable in loss record 22 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x7099AE: alloc (alloc.rs:80)
==13729==    by 0x7099AE: alloc (alloc.rs:174)
==13729==    by 0x7099AE: exchange_malloc (alloc.rs:277)
==13729==    by 0x7099AE: new<()> (mutex.rs:223)
==13729==    by 0x7099AE: std::thread::Thread::new (mod.rs:1149)
==13729==    by 0x2DD291: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0726: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E12DF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 160 bytes in 4 blocks are still reachable in loss record 23 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2DD2B3: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0726: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E12DF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 192 bytes in 4 blocks are still reachable in loss record 24 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x726AA6: alloc (alloc.rs:80)
==13729==    by 0x726AA6: alloc (alloc.rs:174)
==13729==    by 0x726AA6: exchange_malloc (alloc.rs:277)
==13729==    by 0x726AA6: std::sync::condvar::Condvar::new (condvar.rs:130)
==13729==    by 0x2E1C06: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E79E8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2B30: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0C5A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 192 bytes in 4 blocks are still reachable in loss record 25 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x726AA6: alloc (alloc.rs:80)
==13729==    by 0x726AA6: alloc (alloc.rs:174)
==13729==    by 0x726AA6: exchange_malloc (alloc.rs:277)
==13729==    by 0x726AA6: std::sync::condvar::Condvar::new (condvar.rs:130)
==13729==    by 0x2E1C31: rayon_core::registry::ThreadInfo::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E79E8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2B30: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0C5A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 192 bytes in 4 blocks are still reachable in loss record 26 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x726AA6: alloc (alloc.rs:80)
==13729==    by 0x726AA6: alloc (alloc.rs:174)
==13729==    by 0x726AA6: exchange_malloc (alloc.rs:277)
==13729==    by 0x726AA6: std::sync::condvar::Condvar::new (condvar.rs:130)
==13729==    by 0x2E7BB1: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0CD0: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 192 bytes in 4 blocks are still reachable in loss record 27 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x709A12: alloc (alloc.rs:80)
==13729==    by 0x709A12: alloc (alloc.rs:174)
==13729==    by 0x709A12: exchange_malloc (alloc.rs:277)
==13729==    by 0x709A12: new (condvar.rs:130)
==13729==    by 0x709A12: std::thread::Thread::new (mod.rs:1150)
==13729==    by 0x2DD291: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0726: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E12DF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 320 bytes in 4 blocks are still reachable in loss record 28 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x709A61: alloc (alloc.rs:80)
==13729==    by 0x709A61: alloc (alloc.rs:174)
==13729==    by 0x709A61: exchange_malloc (alloc.rs:277)
==13729==    by 0x709A61: new<std::thread::Inner> (sync.rs:324)
==13729==    by 0x709A61: std::thread::Thread::new (mod.rs:1145)
==13729==    by 0x2DD291: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0726: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E12DF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 384 bytes in 1 blocks are still reachable in loss record 29 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2E5DBC: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2AEC: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0C5A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 416 bytes in 4 blocks are still reachable in loss record 30 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2DD348: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0726: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E12DF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 432 (416 direct, 16 indirect) bytes in 1 blocks are definitely lost in loss record 31 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x6AAC4D: wasmer_vm::instance::InstanceHandle::allocate_instance (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2803E1: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BF0D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x581702: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DCF1: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729==    by 0x25EC51: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 512 bytes in 1 blocks are still reachable in loss record 32 of 43
==13729==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x72C519: aligned_malloc (alloc.rs:95)
==13729==    by 0x72C519: alloc (alloc.rs:22)
==13729==    by 0x72C519: __rdl_alloc (alloc.rs:304)
==13729==    by 0x2E60D6: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0C8A: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 640 bytes in 1 blocks are still reachable in loss record 33 of 43
==13729==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x72C519: aligned_malloc (alloc.rs:95)
==13729==    by 0x72C519: alloc (alloc.rs:22)
==13729==    by 0x72C519: __rdl_alloc (alloc.rs:304)
==13729==    by 0x2E0EC6: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 640 bytes in 1 blocks are still reachable in loss record 34 of 43
==13729==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x72C519: aligned_malloc (alloc.rs:95)
==13729==    by 0x72C519: alloc (alloc.rs:22)
==13729==    by 0x72C519: __rdl_alloc (alloc.rs:304)
==13729==    by 0x2EF3E2: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2EF07D: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E6AB2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2DE3B6: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E1FF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E010A: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2BA0: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2DD56E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 664 bytes in 1 blocks are still reachable in loss record 35 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x284503: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x26540A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BBAF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2613F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DB92: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729==    by 0x25EC51: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 808 bytes in 1 blocks are still reachable in loss record 36 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x64E71F: alloc::collections::btree::map::BTreeMap<K,V>::insert (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x647231: wasmer_engine::trap::frame_info::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x286735: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x280A15: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x57BF0D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x581702: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25DCF1: exported_function::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x25BE02: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x72DAB2: {{closure}} (rt.rs:52)
==13729==    by 0x72DAB2: do_call<closure-0,i32> (panicking.rs:348)
==13729==    by 0x72DAB2: try<i32,closure-0> (panicking.rs:325)
==13729==    by 0x72DAB2: catch_unwind<closure-0,i32> (panic.rs:394)
==13729==    by 0x72DAB2: std::rt::lang_start_internal (rt.rs:51)
==13729==    by 0x25EC51: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 1,152 bytes in 4 blocks are possibly lost in loss record 37 of 43
==13729==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==13729==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==13729==    by 0x5252227: allocate_stack (allocatestack.c:627)
==13729==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==13729==    by 0x73C12C: std::sys::unix::thread::Thread::new (thread.rs:66)
==13729==    by 0x2DD3A6: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0726: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E12DF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 1,520 bytes in 1 blocks are still reachable in loss record 38 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2E0D22: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2A0051: <wasmer_compiler_cranelift::compiler::CraneliftCompiler as wasmer_compiler::compiler::Compiler>::compile_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x284678: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 1,536 bytes in 4 blocks are still reachable in loss record 39 of 43
==13729==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x72C519: aligned_malloc (alloc.rs:95)
==13729==    by 0x72C519: alloc (alloc.rs:22)
==13729==    by 0x72C519: __rdl_alloc (alloc.rs:304)
==13729==    by 0x2E69B0: crossbeam_deque::deque::Worker<T>::new_lifo (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E7787: core::iter::traits::iterator::Iterator::unzip (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0BB6: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 2,008 bytes in 1 blocks are still reachable in loss record 40 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2EEB2E: crossbeam_epoch::sync::queue::Queue<T>::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2EF3B2: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2EF07D: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E6AB2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2DE3B6: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E1FF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E010A: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2BA0: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2DD56E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x73C3F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13729==    by 0x73C3F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13729==    by 0x73C3F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13729== 
==13729== 4,096 bytes in 4 blocks are still reachable in loss record 41 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2E68F0: crossbeam_deque::deque::Worker<T>::new_lifo (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E7787: core::iter::traits::iterator::Iterator::unzip (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E0BB6: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E42D6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x727159: std::sync::once::Once::call_inner (once.rs:416)
==13729==    by 0x2E08A0: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E369B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x28C881: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x293425: <rayon::iter::while_some::WhileSome<I> as rayon::iter::ParallelIterator>::drive_unindexed (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x297BD8: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2B3621: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729== 
==13729== 4,560 bytes in 3 blocks are still reachable in loss record 42 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2DFAD8: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2BA0: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2DD56E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x73C3F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13729==    by 0x73C3F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13729==    by 0x73C3F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13729==    by 0x52516DA: start_thread (pthread_create.c:463)
==13729==    by 0x57A271E: clone (clone.S:95)
==13729== 
==13729== 6,120 bytes in 3 blocks are still reachable in loss record 43 of 43
==13729==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13729==    by 0x2EC40F: crossbeam_epoch::internal::Local::register (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2EF004: _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h3d6d30c5335b0a67E.llvm.12191645446024711930 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E6AB2: crossbeam_deque::deque::Stealer<T>::steal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2DE3B6: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E1FF9: rayon_core::registry::WorkerThread::wait_until_cold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E010A: rayon_core::registry::ThreadBuilder::run (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2E2BA0: _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd13678e4d803656bE.llvm.9549009445676040077 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x2DD56E: core::ops::function::FnOnce::call_once{{vtable-shim}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/exported-function)
==13729==    by 0x73C3F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==13729==    by 0x73C3F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==13729==    by 0x73C3F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==13729==    by 0x52516DA: start_thread (pthread_create.c:463)
==13729==    by 0x57A271E: clone (clone.S:95)
==13729== 
==13729== LEAK SUMMARY:
==13729==    definitely lost: 416 bytes in 1 blocks
==13729==    indirectly lost: 16 bytes in 2 blocks
==13729==      possibly lost: 1,204 bytes in 5 blocks
==13729==    still reachable: 26,508 bytes in 91 blocks
==13729==         suppressed: 0 bytes in 0 blocks
==13729== 
==13729== For counts of detected and suppressed errors, rerun with: -v
==13729== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
