==29839== Memcheck, a memory error detector
==29839== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29839== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29839== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/imported-function
==29839== 
==29839== 
==29839== HEAP SUMMARY:
==29839==     in use at exit: 30,410 bytes in 93 blocks
==29839==   total heap usage: 1,005 allocs, 912 frees, 175,395 bytes allocated
==29839== 
==29839== 1 bytes in 1 blocks are indirectly lost in loss record 1 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x19F7A8B: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0x19F7C23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0x19EE82D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29839==    by 0x19F36B0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29839==    by 0x19ED5AE: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29839==    by 0x19C84FE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29839==    by 0x1A24271: alloc::slice::hack::to_vec (slice.rs:157)
==29839==    by 0x19D8DCA: alloc::slice::<impl [T]>::to_vec (slice.rs:393)
==29839==    by 0x19CAACB: <alloc::vec::Vec<T> as core::clone::Clone>::clone (vec.rs:1940)
==29839==    by 0xB4290F: <wasmer_types::types::FunctionType as core::clone::Clone>::clone (types.rs:226)
==29839==    by 0xB4396F: wasmer::externals::function::Function::new (function.rs:82)
==29839== 
==29839== 1 bytes in 1 blocks are indirectly lost in loss record 2 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x19F7A8B: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0x19F7C23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0x19EE82D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29839==    by 0x19F36B0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29839==    by 0x19ED5AE: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29839==    by 0x19C84FE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29839==    by 0x1A24271: alloc::slice::hack::to_vec (slice.rs:157)
==29839==    by 0x19D8DCA: alloc::slice::<impl [T]>::to_vec (slice.rs:393)
==29839==    by 0x19CAACB: <alloc::vec::Vec<T> as core::clone::Clone>::clone (vec.rs:1940)
==29839==    by 0xB42930: <wasmer_types::types::FunctionType as core::clone::Clone>::clone (types.rs:228)
==29839==    by 0xB4396F: wasmer::externals::function::Function::new (function.rs:82)
==29839== 
==29839== 8 bytes in 1 blocks are still reachable in loss record 3 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD3A6B2: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29839==    by 0xD3A6B2: rayon_core::util::leak (util.rs:5)
==29839==    by 0xD3F9AE: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29839==    by 0xD759E8: core::result::Result<T,E>::map (result.rs:519)
==29839==    by 0xD3FA49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839==    by 0xD62E80: std::sync::once::Once::call_once (once.rs:264)
==29839==    by 0xD3F956: rayon_core::registry::set_global_registry (registry.rs:194)
==29839== 
==29839== 32 bytes in 1 blocks are still reachable in loss record 4 of 33
==29839==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29839==    by 0x4E3F165: dlsym (dlsym.c:70)
==29839==    by 0x1C353C3: fetch (weak.rs:61)
==29839==    by 0x1C353C3: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29839==    by 0x1C353C3: min_stack_size (thread.rs:449)
==29839==    by 0x1C353C3: std::sys::unix::thread::Thread::new (thread.rs:49)
==29839==    by 0xD6F3EB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29839==    by 0xD7061B: std::thread::Builder::spawn (mod.rs:386)
==29839==    by 0xD3F438: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29839==    by 0xD4051F: rayon_core::registry::Registry::new (registry.rs:260)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839== 
==29839== 64 bytes in 4 blocks are still reachable in loss record 5 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD4E396: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29839==    by 0xD4E396: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29839==    by 0xD6AC43: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29839==    by 0xD6AD93: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29839==    by 0xD6AD63: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29839==    by 0xD4CA96: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29839==    by 0xD4099E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29839==    by 0xD796AC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29839==    by 0xD4A2FD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29839== 
==29839== 64 bytes in 4 blocks are still reachable in loss record 6 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C3531C: alloc (alloc.rs:80)
==29839==    by 0x1C3531C: alloc (alloc.rs:174)
==29839==    by 0x1C3531C: exchange_malloc (alloc.rs:277)
==29839==    by 0x1C3531C: std::sys::unix::thread::Thread::new (thread.rs:44)
==29839==    by 0xD6F3EB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29839==    by 0xD7061B: std::thread::Builder::spawn (mod.rs:386)
==29839==    by 0xD3F438: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29839==    by 0xD4051F: rayon_core::registry::Registry::new (registry.rs:260)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839==    by 0xD62E80: std::sync::once::Once::call_once (once.rs:264)
==29839==    by 0xD3F956: rayon_core::registry::set_global_registry (registry.rs:194)
==29839== 
==29839== 72 bytes in 1 blocks are still reachable in loss record 7 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1827AAB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0x1827BD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0x1827A0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0x182A8C7: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==29839==    by 0x182ABFC: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==29839==    by 0x181C570: __static_ref_initialize (frame_info.rs:28)
==29839==    by 0x181C570: core::ops::function::FnOnce::call_once (function.rs:233)
==29839==    by 0x185428B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29839==    by 0x1852C04: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839==    by 0x1852B80: std::sync::once::Once::call_once (once.rs:264)
==29839==    by 0x1817998: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==29839==    by 0x1817998: __stability (lib.rs:142)
==29839==    by 0x1817998: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==29839== 
==29839== 74 (72 direct, 2 indirect) bytes in 1 blocks are definitely lost in loss record 8 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xB3A1CB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xB3A2F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xB3A12C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xB43A53: new<wasmer_vm::vmcontext::VMDynamicFunctionContext<wasmer::externals::function::VMDynamicFunctionWithoutEnv>> (boxed.rs:177)
==29839==    by 0xB43A53: wasmer::externals::function::Function::new (function.rs:89)
==29839==    by 0xB40703: imported_function::main (imports_function.rs:53)
==29839==    by 0xB4812A: std::rt::lang_start::{{closure}} (rt.rs:67)
==29839==    by 0x1C26DF2: {{closure}} (rt.rs:52)
==29839==    by 0x1C26DF2: do_call<closure-0,i32> (panicking.rs:348)
==29839==    by 0x1C26DF2: try<i32,closure-0> (panicking.rs:325)
==29839==    by 0x1C26DF2: catch_unwind<closure-0,i32> (panic.rs:394)
==29839==    by 0x1C26DF2: std::rt::lang_start_internal (rt.rs:51)
==29839==    by 0xB48106: std::rt::lang_start (rt.rs:67)
==29839==    by 0xB415F9: main (in /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/imported-function)
==29839== 
==29839== 128 bytes in 4 blocks are still reachable in loss record 9 of 33
==29839==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29839==    by 0x1C0194E: register_dtor (fast_thread_local.rs:33)
==29839==    by 0x1C0194E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29839==    by 0x1C0194E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29839==    by 0x1C24149: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29839==    by 0x1C24149: __getit (local.rs:175)
==29839==    by 0x1C24149: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29839==    by 0x1C24149: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29839==    by 0x1C24149: std::sys_common::thread_info::set (thread_info.rs:40)
==29839==    by 0xD6F7B1: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29839==    by 0xD63ECE: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29839==    by 0x1C35739: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29839==    by 0x1C35739: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29839==    by 0x1C35739: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29839==    by 0x52516DA: start_thread (pthread_create.c:463)
==29839==    by 0x57A271E: clone (clone.S:95)
==29839== 
==29839== 128 bytes in 4 blocks are still reachable in loss record 10 of 33
==29839==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29839==    by 0xDA7721: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29839==    by 0xDA7622: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29839==    by 0xDA77C6: std::thread::local::fast::Key<T>::get (local.rs:410)
==29839==    by 0xDA751C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29839==    by 0xD511C4: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29839==    by 0xD56B52: crossbeam_epoch::default::with_handle (default.rs:43)
==29839==    by 0xD56E36: crossbeam_epoch::default::is_pinned (default.rs:30)
==29839==    by 0xD4CC5C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29839==    by 0xD42802: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29839==    by 0xD3DBEC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29839== 
==29839== 160 bytes in 4 blocks are still reachable in loss record 11 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD6DAFF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29839==    by 0xD81310: rayon_core::latch::LockLatch::new (latch.rs:230)
==29839==    by 0xD4174C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29839==    by 0xD63DE1: core::ops::function::FnMut::call_mut (function.rs:154)
==29839==    by 0xD793C3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29839==    by 0xD5CD63: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29839==    by 0xD7AC78: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29839==    by 0xD78B79: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29839== 
==29839== 160 bytes in 4 blocks are still reachable in loss record 12 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD6DAFF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29839==    by 0xD81310: rayon_core::latch::LockLatch::new (latch.rs:230)
==29839==    by 0xD41764: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29839==    by 0xD63DE1: core::ops::function::FnMut::call_mut (function.rs:154)
==29839==    by 0xD793C3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29839==    by 0xD5CD63: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29839==    by 0xD7AC78: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29839==    by 0xD78B79: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29839== 
==29839== 160 bytes in 4 blocks are still reachable in loss record 13 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD6DAFF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29839==    by 0xD71473: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29839==    by 0xD5C15E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29839==    by 0xD5958D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29839==    by 0xD5A9FA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29839==    by 0xD79570: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29839==    by 0xD4A108: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29839==    by 0xD7AD49: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29839== 
==29839== 160 bytes in 4 blocks are still reachable in loss record 14 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C02CEE: alloc (alloc.rs:80)
==29839==    by 0x1C02CEE: alloc (alloc.rs:174)
==29839==    by 0x1C02CEE: exchange_malloc (alloc.rs:277)
==29839==    by 0x1C02CEE: new<()> (mutex.rs:223)
==29839==    by 0x1C02CEE: std::thread::Thread::new (mod.rs:1149)
==29839==    by 0xD6F18D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29839==    by 0xD7061B: std::thread::Builder::spawn (mod.rs:386)
==29839==    by 0xD3F438: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29839==    by 0xD4051F: rayon_core::registry::Registry::new (registry.rs:260)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839==    by 0xD62E80: std::sync::once::Once::call_once (once.rs:264)
==29839==    by 0xD3F956: rayon_core::registry::set_global_registry (registry.rs:194)
==29839== 
==29839== 160 bytes in 4 blocks are still reachable in loss record 15 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD38B57: alloc::sync::Arc<T>::new (sync.rs:324)
==29839==    by 0xD6F22B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29839==    by 0xD7061B: std::thread::Builder::spawn (mod.rs:386)
==29839==    by 0xD3F438: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29839==    by 0xD4051F: rayon_core::registry::Registry::new (registry.rs:260)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839== 
==29839== 192 bytes in 4 blocks are still reachable in loss record 16 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C1FDE6: alloc (alloc.rs:80)
==29839==    by 0x1C1FDE6: alloc (alloc.rs:174)
==29839==    by 0x1C1FDE6: exchange_malloc (alloc.rs:277)
==29839==    by 0x1C1FDE6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29839==    by 0xD8132C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29839==    by 0xD4174C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29839==    by 0xD63DE1: core::ops::function::FnMut::call_mut (function.rs:154)
==29839==    by 0xD793C3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29839==    by 0xD5CD63: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29839==    by 0xD7AC78: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29839==    by 0xD78B79: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29839==    by 0xD60751: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29839==    by 0xD613D4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29839==    by 0xD62376: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29839== 
==29839== 192 bytes in 4 blocks are still reachable in loss record 17 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C1FDE6: alloc (alloc.rs:80)
==29839==    by 0x1C1FDE6: alloc (alloc.rs:174)
==29839==    by 0x1C1FDE6: exchange_malloc (alloc.rs:277)
==29839==    by 0x1C1FDE6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29839==    by 0xD8132C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29839==    by 0xD41764: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29839==    by 0xD63DE1: core::ops::function::FnMut::call_mut (function.rs:154)
==29839==    by 0xD793C3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29839==    by 0xD5CD63: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29839==    by 0xD7AC78: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29839==    by 0xD78B79: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29839==    by 0xD60751: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29839==    by 0xD613D4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29839==    by 0xD62376: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29839== 
==29839== 192 bytes in 4 blocks are still reachable in loss record 18 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C1FDE6: alloc (alloc.rs:80)
==29839==    by 0x1C1FDE6: alloc (alloc.rs:174)
==29839==    by 0x1C1FDE6: exchange_malloc (alloc.rs:277)
==29839==    by 0x1C1FDE6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29839==    by 0xD5C17A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29839==    by 0xD5958D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29839==    by 0xD5A9FA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29839==    by 0xD79570: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29839==    by 0xD4A108: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29839==    by 0xD7AD49: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29839==    by 0xD789AA: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29839==    by 0xD60B17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29839==    by 0xD61331: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29839==    by 0xD62315: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29839== 
==29839== 192 bytes in 4 blocks are still reachable in loss record 19 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C02D52: alloc (alloc.rs:80)
==29839==    by 0x1C02D52: alloc (alloc.rs:174)
==29839==    by 0x1C02D52: exchange_malloc (alloc.rs:277)
==29839==    by 0x1C02D52: new (condvar.rs:130)
==29839==    by 0x1C02D52: std::thread::Thread::new (mod.rs:1150)
==29839==    by 0xD6F18D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29839==    by 0xD7061B: std::thread::Builder::spawn (mod.rs:386)
==29839==    by 0xD3F438: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29839==    by 0xD4051F: rayon_core::registry::Registry::new (registry.rs:260)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839==    by 0xD62E80: std::sync::once::Once::call_once (once.rs:264)
==29839==    by 0xD3F956: rayon_core::registry::set_global_registry (registry.rs:194)
==29839== 
==29839== 320 bytes in 4 blocks are still reachable in loss record 20 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C02DA1: alloc (alloc.rs:80)
==29839==    by 0x1C02DA1: alloc (alloc.rs:174)
==29839==    by 0x1C02DA1: exchange_malloc (alloc.rs:277)
==29839==    by 0x1C02DA1: new<std::thread::Inner> (sync.rs:324)
==29839==    by 0x1C02DA1: std::thread::Thread::new (mod.rs:1145)
==29839==    by 0xD6F18D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29839==    by 0xD7061B: std::thread::Builder::spawn (mod.rs:386)
==29839==    by 0xD3F438: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29839==    by 0xD4051F: rayon_core::registry::Registry::new (registry.rs:260)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839==    by 0xD62E80: std::sync::once::Once::call_once (once.rs:264)
==29839==    by 0xD3F956: rayon_core::registry::set_global_registry (registry.rs:194)
==29839== 
==29839== 384 bytes in 1 blocks are still reachable in loss record 21 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xDD008B: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xDD0933: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xDC744A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29839==    by 0xD840D0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29839==    by 0xD82A23: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29839==    by 0xD86622: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29839==    by 0xD5F508: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29839==    by 0xD60667: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29839==    by 0xD613D4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29839==    by 0xD62376: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29839==    by 0xD787D8: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29839== 
==29839== 416 bytes in 4 blocks are still reachable in loss record 22 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD6F357: new<closure-0> (boxed.rs:177)
==29839==    by 0xD6F357: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29839==    by 0xD7061B: std::thread::Builder::spawn (mod.rs:386)
==29839==    by 0xD3F438: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29839==    by 0xD4051F: rayon_core::registry::Registry::new (registry.rs:260)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839== 
==29839== 512 bytes in 1 blocks are still reachable in loss record 23 of 33
==29839==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C25859: aligned_malloc (alloc.rs:95)
==29839==    by 0x1C25859: alloc (alloc.rs:22)
==29839==    by 0x1C25859: __rdl_alloc (alloc.rs:304)
==29839==    by 0xDD008B: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xDD0933: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xDC744A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29839==    by 0xD84430: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29839==    by 0xD82923: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29839==    by 0xD86582: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29839==    by 0xD5F4A8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29839==    by 0xD60A57: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29839==    by 0xD61331: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29839== 
==29839== 640 bytes in 1 blocks are still reachable in loss record 24 of 33
==29839==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C25859: aligned_malloc (alloc.rs:95)
==29839==    by 0x1C25859: alloc (alloc.rs:22)
==29839==    by 0x1C25859: __rdl_alloc (alloc.rs:304)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD38985: alloc::sync::Arc<T>::new (sync.rs:324)
==29839==    by 0xD40117: rayon_core::registry::Registry::new (registry.rs:238)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839== 
==29839== 640 bytes in 1 blocks are still reachable in loss record 25 of 33
==29839==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C25859: aligned_malloc (alloc.rs:95)
==29839==    by 0x1C25859: alloc (alloc.rs:22)
==29839==    by 0x1C25859: __rdl_alloc (alloc.rs:304)
==29839==    by 0xDABF8B: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xDAC4D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xDABEEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xDA8165: alloc::sync::Arc<T>::new (sync.rs:324)
==29839==    by 0xDA86A9: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29839==    by 0xDA86D6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29839==    by 0xDA6BC9: __static_ref_initialize (default.rs:13)
==29839==    by 0xDA6BC9: core::ops::function::FnOnce::call_once (function.rs:233)
==29839==    by 0xDA6A35: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29839==    by 0xDA7CF4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839== 
==29839== 808 bytes in 1 blocks are still reachable in loss record 26 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1827AAB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0x1827BD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0x1827A0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0x1835C80: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==29839==    by 0x1835C80: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==29839==    by 0x181C589: core::ops::function::FnOnce::call_once (function.rs:233)
==29839==    by 0x1828CCC: core::option::Option<T>::get_or_insert_with (option.rs:853)
==29839==    by 0x184E58E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==29839==    by 0x184E961: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==29839==    by 0x184F7D9: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==29839==    by 0x18176AF: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==29839==    by 0xBE0A84: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==29839== 
==29839== 1,152 bytes in 4 blocks are possibly lost in loss record 27 of 33
==29839==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29839==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29839==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29839==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29839==    by 0x1C3546C: std::sys::unix::thread::Thread::new (thread.rs:66)
==29839==    by 0xD6F3EB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29839==    by 0xD7061B: std::thread::Builder::spawn (mod.rs:386)
==29839==    by 0xD3F438: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29839==    by 0xD4051F: rayon_core::registry::Registry::new (registry.rs:260)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839== 
==29839== 1,520 bytes in 1 blocks are still reachable in loss record 28 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD4E771: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29839==    by 0xD4E771: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29839==    by 0xD4CFFD: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29839==    by 0xD3FEE3: rayon_core::registry::Registry::new (registry.rs:242)
==29839==    by 0xD3F6AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29839==    by 0xD3FA39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29839==    by 0xD62F03: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29839==    by 0x1C20499: std::sync::once::Once::call_inner (once.rs:416)
==29839==    by 0xD62E80: std::sync::once::Once::call_once (once.rs:264)
==29839== 
==29839== 1,536 bytes in 4 blocks are still reachable in loss record 29 of 33
==29839==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0x1C25859: aligned_malloc (alloc.rs:95)
==29839==    by 0x1C25859: alloc (alloc.rs:22)
==29839==    by 0x1C25859: __rdl_alloc (alloc.rs:304)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD387A5: alloc::sync::Arc<T>::new (sync.rs:324)
==29839==    by 0xD4CB2D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29839==    by 0xD4099E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29839==    by 0xD796AC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29839==    by 0xD4A2FD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29839==    by 0xD7AF03: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29839== 
==29839== 2,008 bytes in 1 blocks are still reachable in loss record 30 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xDABF8B: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xDAC4D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xDABEEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xDA48A9: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29839==    by 0xDA48A9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29839==    by 0xDA4255: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29839==    by 0xDA41A5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29839==    by 0xDA4AAB: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29839==    by 0xD9FEA3: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29839==    by 0xDA869B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29839==    by 0xDA86D6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29839==    by 0xDA6BC9: __static_ref_initialize (default.rs:13)
==29839==    by 0xDA6BC9: core::ops::function::FnOnce::call_once (function.rs:233)
==29839== 
==29839== 4,096 bytes in 4 blocks are still reachable in loss record 31 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD826DD: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29839==    by 0xD85950: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29839==    by 0xD81ACE: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29839==    by 0xD5D2DE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29839==    by 0xD4B540: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29839==    by 0xD4CA19: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29839==    by 0xD4099E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29839==    by 0xD796AC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29839==    by 0xD4A2FD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29839== 
==29839== 6,080 bytes in 4 blocks are still reachable in loss record 32 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xD68EEB: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xD69D13: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xD68E4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD4E771: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29839==    by 0xD4E771: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29839==    by 0xD4CFFD: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29839==    by 0xD3A57C: rayon_core::job::JobFifo::new (job.rs:193)
==29839==    by 0xD4293A: rayon_core::registry::main_loop (registry.rs:806)
==29839==    by 0xD3EF6F: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29839==    by 0xD3F620: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29839==    by 0xD77ECF: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29839==    by 0xD704A0: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29839== 
==29839== 8,160 bytes in 4 blocks are still reachable in loss record 33 of 33
==29839==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29839==    by 0xDABF8B: alloc::alloc::alloc (alloc.rs:80)
==29839==    by 0xDAC4D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29839==    by 0xDABEEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29839==    by 0xD9F8D9: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29839==    by 0xD9F8D9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29839==    by 0xDA41F5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29839==    by 0xDA4155: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29839==    by 0xDA0742: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29839==    by 0xDA86FD: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29839==    by 0xDA74E3: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29839==    by 0xDA6BA8: core::ops::function::FnOnce::call_once (function.rs:233)
==29839==    by 0xDAC67B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29839== 
==29839== LEAK SUMMARY:
==29839==    definitely lost: 72 bytes in 1 blocks
==29839==    indirectly lost: 2 bytes in 2 blocks
==29839==      possibly lost: 1,152 bytes in 4 blocks
==29839==    still reachable: 29,184 bytes in 86 blocks
==29839==         suppressed: 0 bytes in 0 blocks
==29839== 
==29839== For counts of detected and suppressed errors, rerun with: -v
==29839== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
