==11421== Memcheck, a memory error detector
==11421== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11421== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11421== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/imported-function
==11421== 
==11421== 
==11421== HEAP SUMMARY:
==11421==     in use at exit: 30,402 bytes in 92 blocks
==11421==   total heap usage: 1,004 allocs, 912 frees, 175,387 bytes allocated
==11421== 
==11421== 1 bytes in 1 blocks are indirectly lost in loss record 1 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x19F7E3B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0x19F7FD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0x19EEBDD: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11421==    by 0x19F3A60: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11421==    by 0x19ED95E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11421==    by 0x19C88AE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11421==    by 0x1A24621: alloc::slice::hack::to_vec (slice.rs:157)
==11421==    by 0x19D917A: alloc::slice::<impl [T]>::to_vec (slice.rs:393)
==11421==    by 0x19CAE7B: <alloc::vec::Vec<T> as core::clone::Clone>::clone (vec.rs:1940)
==11421==    by 0xB423AF: <wasmer_types::types::FunctionType as core::clone::Clone>::clone (types.rs:226)
==11421==    by 0xB490FF: wasmer::externals::function::Function::new (function.rs:82)
==11421== 
==11421== 1 bytes in 1 blocks are indirectly lost in loss record 2 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x19F7E3B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0x19F7FD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0x19EEBDD: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11421==    by 0x19F3A60: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11421==    by 0x19ED95E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11421==    by 0x19C88AE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11421==    by 0x1A24621: alloc::slice::hack::to_vec (slice.rs:157)
==11421==    by 0x19D917A: alloc::slice::<impl [T]>::to_vec (slice.rs:393)
==11421==    by 0x19CAE7B: <alloc::vec::Vec<T> as core::clone::Clone>::clone (vec.rs:1940)
==11421==    by 0xB423D0: <wasmer_types::types::FunctionType as core::clone::Clone>::clone (types.rs:228)
==11421==    by 0xB490FF: wasmer::externals::function::Function::new (function.rs:82)
==11421== 
==11421== 32 bytes in 1 blocks are still reachable in loss record 3 of 32
==11421==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11421==    by 0x4E3F165: dlsym (dlsym.c:70)
==11421==    by 0x1C35773: fetch (weak.rs:61)
==11421==    by 0x1C35773: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11421==    by 0x1C35773: min_stack_size (thread.rs:449)
==11421==    by 0x1C35773: std::sys::unix::thread::Thread::new (thread.rs:49)
==11421==    by 0xD6E7CB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11421==    by 0xD70A4B: std::thread::Builder::spawn (mod.rs:386)
==11421==    by 0xD3F538: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11421==    by 0xD4067F: rayon_core::registry::Registry::new (registry.rs:256)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421== 
==11421== 64 bytes in 4 blocks are still reachable in loss record 4 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD4F736: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11421==    by 0xD4F736: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11421==    by 0xD6AF53: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11421==    by 0xD6B0A3: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11421==    by 0xD6B073: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11421==    by 0xD4DE36: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11421==    by 0xD40AFE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11421==    by 0xD7984C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11421==    by 0xD48BCD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11421== 
==11421== 64 bytes in 4 blocks are still reachable in loss record 5 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C356CC: alloc (alloc.rs:80)
==11421==    by 0x1C356CC: alloc (alloc.rs:174)
==11421==    by 0x1C356CC: exchange_malloc (alloc.rs:277)
==11421==    by 0x1C356CC: std::sys::unix::thread::Thread::new (thread.rs:44)
==11421==    by 0xD6E7CB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11421==    by 0xD70A4B: std::thread::Builder::spawn (mod.rs:386)
==11421==    by 0xD3F538: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11421==    by 0xD4067F: rayon_core::registry::Registry::new (registry.rs:256)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421==    by 0xD630D0: std::sync::once::Once::call_once (once.rs:264)
==11421==    by 0xD3FAB6: rayon_core::registry::set_global_registry (registry.rs:194)
==11421== 
==11421== 72 bytes in 1 blocks are still reachable in loss record 6 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1827E5B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0x1827F83: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0x1827DBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0x182AC77: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==11421==    by 0x182AFAC: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==11421==    by 0x181C920: __static_ref_initialize (frame_info.rs:28)
==11421==    by 0x181C920: core::ops::function::FnOnce::call_once (function.rs:233)
==11421==    by 0x185463B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11421==    by 0x1852FB4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421==    by 0x1852F30: std::sync::once::Once::call_once (once.rs:264)
==11421==    by 0x1817D48: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==11421==    by 0x1817D48: __stability (lib.rs:142)
==11421==    by 0x1817D48: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==11421== 
==11421== 74 (72 direct, 2 indirect) bytes in 1 blocks are definitely lost in loss record 7 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xB44E8B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xB44FB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xB44DEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xB491E3: new<wasmer_vm::vmcontext::VMDynamicFunctionContext<wasmer::externals::function::VMDynamicFunctionWithoutEnv>> (boxed.rs:177)
==11421==    by 0xB491E3: wasmer::externals::function::Function::new (function.rs:89)
==11421==    by 0xB39813: imported_function::main (imports_function.rs:53)
==11421==    by 0xB3C40A: std::rt::lang_start::{{closure}} (rt.rs:67)
==11421==    by 0x1C271A2: {{closure}} (rt.rs:52)
==11421==    by 0x1C271A2: do_call<closure-0,i32> (panicking.rs:348)
==11421==    by 0x1C271A2: try<i32,closure-0> (panicking.rs:325)
==11421==    by 0x1C271A2: catch_unwind<closure-0,i32> (panic.rs:394)
==11421==    by 0x1C271A2: std::rt::lang_start_internal (rt.rs:51)
==11421==    by 0xB3C3E6: std::rt::lang_start (rt.rs:67)
==11421==    by 0xB3A709: main (in /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/imported-function)
==11421== 
==11421== 128 bytes in 4 blocks are still reachable in loss record 8 of 32
==11421==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11421==    by 0x1C01CFE: register_dtor (fast_thread_local.rs:33)
==11421==    by 0x1C01CFE: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11421==    by 0x1C01CFE: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11421==    by 0x1C244F9: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11421==    by 0x1C244F9: __getit (local.rs:175)
==11421==    by 0x1C244F9: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11421==    by 0x1C244F9: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11421==    by 0x1C244F9: std::sys_common::thread_info::set (thread_info.rs:40)
==11421==    by 0xD6FC61: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11421==    by 0xD6427E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11421==    by 0x1C35AE9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11421==    by 0x1C35AE9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11421==    by 0x1C35AE9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11421==    by 0x52516DA: start_thread (pthread_create.c:463)
==11421==    by 0x57A271E: clone (clone.S:95)
==11421== 
==11421== 128 bytes in 4 blocks are still reachable in loss record 9 of 32
==11421==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11421==    by 0xDA7AD1: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11421==    by 0xDA79D2: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11421==    by 0xDA7B76: std::thread::local::fast::Key<T>::get (local.rs:410)
==11421==    by 0xDA78CC: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11421==    by 0xD52B44: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11421==    by 0xD56FD2: crossbeam_epoch::default::with_handle (default.rs:43)
==11421==    by 0xD57236: crossbeam_epoch::default::is_pinned (default.rs:30)
==11421==    by 0xD4DFFC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11421==    by 0xD42962: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11421==    by 0xD3DDFC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11421== 
==11421== 160 bytes in 4 blocks are still reachable in loss record 10 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD6DFAF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11421==    by 0xD816C0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11421==    by 0xD418AC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11421==    by 0xD64071: core::ops::function::FnMut::call_mut (function.rs:154)
==11421==    by 0xD7A033: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11421==    by 0xD5D053: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11421==    by 0xD7AD18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11421==    by 0xD78ED9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11421== 
==11421== 160 bytes in 4 blocks are still reachable in loss record 11 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD6DFAF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11421==    by 0xD816C0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11421==    by 0xD418C4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11421==    by 0xD64071: core::ops::function::FnMut::call_mut (function.rs:154)
==11421==    by 0xD7A033: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11421==    by 0xD5D053: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11421==    by 0xD7AD18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11421==    by 0xD78ED9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11421== 
==11421== 160 bytes in 4 blocks are still reachable in loss record 12 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD6DFAF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11421==    by 0xD71873: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11421==    by 0xD5C51E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11421==    by 0xD599CD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11421==    by 0xD5ADBA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11421==    by 0xD79D00: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11421==    by 0xD48EA8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11421==    by 0xD7AC59: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11421== 
==11421== 160 bytes in 4 blocks are still reachable in loss record 13 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C0309E: alloc (alloc.rs:80)
==11421==    by 0x1C0309E: alloc (alloc.rs:174)
==11421==    by 0x1C0309E: exchange_malloc (alloc.rs:277)
==11421==    by 0x1C0309E: new<()> (mutex.rs:223)
==11421==    by 0x1C0309E: std::thread::Thread::new (mod.rs:1149)
==11421==    by 0xD6E56D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11421==    by 0xD70A4B: std::thread::Builder::spawn (mod.rs:386)
==11421==    by 0xD3F538: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11421==    by 0xD4067F: rayon_core::registry::Registry::new (registry.rs:256)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421==    by 0xD630D0: std::sync::once::Once::call_once (once.rs:264)
==11421==    by 0xD3FAB6: rayon_core::registry::set_global_registry (registry.rs:194)
==11421== 
==11421== 160 bytes in 4 blocks are still reachable in loss record 14 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD38BB7: alloc::sync::Arc<T>::new (sync.rs:324)
==11421==    by 0xD6E60B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11421==    by 0xD70A4B: std::thread::Builder::spawn (mod.rs:386)
==11421==    by 0xD3F538: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11421==    by 0xD4067F: rayon_core::registry::Registry::new (registry.rs:256)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421== 
==11421== 192 bytes in 4 blocks are still reachable in loss record 15 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C20196: alloc (alloc.rs:80)
==11421==    by 0x1C20196: alloc (alloc.rs:174)
==11421==    by 0x1C20196: exchange_malloc (alloc.rs:277)
==11421==    by 0x1C20196: std::sync::condvar::Condvar::new (condvar.rs:130)
==11421==    by 0xD816DC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11421==    by 0xD418AC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11421==    by 0xD64071: core::ops::function::FnMut::call_mut (function.rs:154)
==11421==    by 0xD7A033: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11421==    by 0xD5D053: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11421==    by 0xD7AD18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11421==    by 0xD78ED9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11421==    by 0xD60ED1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11421==    by 0xD615B4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11421==    by 0xD626E6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11421== 
==11421== 192 bytes in 4 blocks are still reachable in loss record 16 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C20196: alloc (alloc.rs:80)
==11421==    by 0x1C20196: alloc (alloc.rs:174)
==11421==    by 0x1C20196: exchange_malloc (alloc.rs:277)
==11421==    by 0x1C20196: std::sync::condvar::Condvar::new (condvar.rs:130)
==11421==    by 0xD816DC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11421==    by 0xD418C4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11421==    by 0xD64071: core::ops::function::FnMut::call_mut (function.rs:154)
==11421==    by 0xD7A033: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11421==    by 0xD5D053: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11421==    by 0xD7AD18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11421==    by 0xD78ED9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11421==    by 0xD60ED1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11421==    by 0xD615B4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11421==    by 0xD626E6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11421== 
==11421== 192 bytes in 4 blocks are still reachable in loss record 17 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C20196: alloc (alloc.rs:80)
==11421==    by 0x1C20196: alloc (alloc.rs:174)
==11421==    by 0x1C20196: exchange_malloc (alloc.rs:277)
==11421==    by 0x1C20196: std::sync::condvar::Condvar::new (condvar.rs:130)
==11421==    by 0xD5C53A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11421==    by 0xD599CD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11421==    by 0xD5ADBA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11421==    by 0xD79D00: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11421==    by 0xD48EA8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11421==    by 0xD7AC59: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11421==    by 0xD78DAA: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11421==    by 0xD60AD7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11421==    by 0xD61701: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11421==    by 0xD62745: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11421== 
==11421== 192 bytes in 4 blocks are still reachable in loss record 18 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C03102: alloc (alloc.rs:80)
==11421==    by 0x1C03102: alloc (alloc.rs:174)
==11421==    by 0x1C03102: exchange_malloc (alloc.rs:277)
==11421==    by 0x1C03102: new (condvar.rs:130)
==11421==    by 0x1C03102: std::thread::Thread::new (mod.rs:1150)
==11421==    by 0xD6E56D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11421==    by 0xD70A4B: std::thread::Builder::spawn (mod.rs:386)
==11421==    by 0xD3F538: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11421==    by 0xD4067F: rayon_core::registry::Registry::new (registry.rs:256)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421==    by 0xD630D0: std::sync::once::Once::call_once (once.rs:264)
==11421==    by 0xD3FAB6: rayon_core::registry::set_global_registry (registry.rs:194)
==11421== 
==11421== 320 bytes in 4 blocks are still reachable in loss record 19 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C03151: alloc (alloc.rs:80)
==11421==    by 0x1C03151: alloc (alloc.rs:174)
==11421==    by 0x1C03151: exchange_malloc (alloc.rs:277)
==11421==    by 0x1C03151: new<std::thread::Inner> (sync.rs:324)
==11421==    by 0x1C03151: std::thread::Thread::new (mod.rs:1145)
==11421==    by 0xD6E56D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11421==    by 0xD70A4B: std::thread::Builder::spawn (mod.rs:386)
==11421==    by 0xD3F538: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11421==    by 0xD4067F: rayon_core::registry::Registry::new (registry.rs:256)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421==    by 0xD630D0: std::sync::once::Once::call_once (once.rs:264)
==11421==    by 0xD3FAB6: rayon_core::registry::set_global_registry (registry.rs:194)
==11421== 
==11421== 384 bytes in 1 blocks are still reachable in loss record 20 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xDD043B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xDD0CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xDC77FA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11421==    by 0xD84B40: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11421==    by 0xD82D53: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11421==    by 0xD86612: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11421==    by 0xD5F8F8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11421==    by 0xD60DE7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11421==    by 0xD615B4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11421==    by 0xD626E6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11421==    by 0xD78B68: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11421== 
==11421== 416 bytes in 4 blocks are still reachable in loss record 21 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD6E737: new<closure-0> (boxed.rs:177)
==11421==    by 0xD6E737: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11421==    by 0xD70A4B: std::thread::Builder::spawn (mod.rs:386)
==11421==    by 0xD3F538: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11421==    by 0xD4067F: rayon_core::registry::Registry::new (registry.rs:256)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421== 
==11421== 512 bytes in 1 blocks are still reachable in loss record 22 of 32
==11421==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C25C09: aligned_malloc (alloc.rs:95)
==11421==    by 0x1C25C09: alloc (alloc.rs:22)
==11421==    by 0x1C25C09: __rdl_alloc (alloc.rs:304)
==11421==    by 0xDD043B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xDD0CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xDC77FA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11421==    by 0xD847E0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11421==    by 0xD82C53: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11421==    by 0xD86752: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11421==    by 0xD5F8C8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11421==    by 0xD60A17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11421==    by 0xD61701: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11421== 
==11421== 640 bytes in 1 blocks are still reachable in loss record 23 of 32
==11421==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C25C09: aligned_malloc (alloc.rs:95)
==11421==    by 0x1C25C09: alloc (alloc.rs:22)
==11421==    by 0x1C25C09: __rdl_alloc (alloc.rs:304)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD389E5: alloc::sync::Arc<T>::new (sync.rs:324)
==11421==    by 0xD40277: rayon_core::registry::Registry::new (registry.rs:234)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421== 
==11421== 640 bytes in 1 blocks are still reachable in loss record 24 of 32
==11421==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C25C09: aligned_malloc (alloc.rs:95)
==11421==    by 0x1C25C09: alloc (alloc.rs:22)
==11421==    by 0x1C25C09: __rdl_alloc (alloc.rs:304)
==11421==    by 0xDAC33B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xDAC883: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xDAC29C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xDA8515: alloc::sync::Arc<T>::new (sync.rs:324)
==11421==    by 0xDA8A59: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11421==    by 0xDA8A86: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11421==    by 0xDA6F79: __static_ref_initialize (default.rs:13)
==11421==    by 0xDA6F79: core::ops::function::FnOnce::call_once (function.rs:233)
==11421==    by 0xDA6DE5: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11421==    by 0xDA80A4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421== 
==11421== 808 bytes in 1 blocks are still reachable in loss record 25 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1827E5B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0x1827F83: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0x1827DBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0x1836030: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==11421==    by 0x1836030: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==11421==    by 0x181C939: core::ops::function::FnOnce::call_once (function.rs:233)
==11421==    by 0x182907C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==11421==    by 0x184E93E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==11421==    by 0x184ED11: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==11421==    by 0x184FB89: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==11421==    by 0x1817A5F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==11421==    by 0xBE0C24: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==11421== 
==11421== 1,152 bytes in 4 blocks are possibly lost in loss record 26 of 32
==11421==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11421==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11421==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11421==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11421==    by 0x1C3581C: std::sys::unix::thread::Thread::new (thread.rs:66)
==11421==    by 0xD6E7CB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11421==    by 0xD70A4B: std::thread::Builder::spawn (mod.rs:386)
==11421==    by 0xD3F538: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11421==    by 0xD4067F: rayon_core::registry::Registry::new (registry.rs:256)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421== 
==11421== 1,520 bytes in 1 blocks are still reachable in loss record 27 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD4FB11: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11421==    by 0xD4FB11: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11421==    by 0xD4E39D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11421==    by 0xD40043: rayon_core::registry::Registry::new (registry.rs:238)
==11421==    by 0xD3F7AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11421==    by 0xD3FC69: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11421==    by 0xD63333: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11421==    by 0x1C20849: std::sync::once::Once::call_inner (once.rs:416)
==11421==    by 0xD630D0: std::sync::once::Once::call_once (once.rs:264)
==11421== 
==11421== 1,536 bytes in 4 blocks are still reachable in loss record 28 of 32
==11421==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0x1C25C09: aligned_malloc (alloc.rs:95)
==11421==    by 0x1C25C09: alloc (alloc.rs:22)
==11421==    by 0x1C25C09: __rdl_alloc (alloc.rs:304)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD38D45: alloc::sync::Arc<T>::new (sync.rs:324)
==11421==    by 0xD4DECD: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11421==    by 0xD40AFE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11421==    by 0xD7984C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11421==    by 0xD48BCD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11421==    by 0xD7AE03: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11421== 
==11421== 2,008 bytes in 1 blocks are still reachable in loss record 29 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xDAC33B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xDAC883: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xDAC29C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xDA4C59: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11421==    by 0xDA4C59: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11421==    by 0xDA4605: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11421==    by 0xDA4555: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11421==    by 0xDA4E5B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11421==    by 0xDA0253: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11421==    by 0xDA8A4B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11421==    by 0xDA8A86: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11421==    by 0xDA6F79: __static_ref_initialize (default.rs:13)
==11421==    by 0xDA6F79: core::ops::function::FnOnce::call_once (function.rs:233)
==11421== 
==11421== 4,096 bytes in 4 blocks are still reachable in loss record 30 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD8279D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11421==    by 0xD85D00: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11421==    by 0xD81E7E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11421==    by 0xD5D69E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11421==    by 0xD4C8E0: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11421==    by 0xD4DDB9: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11421==    by 0xD40AFE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11421==    by 0xD7984C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11421==    by 0xD48BCD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11421== 
==11421== 6,080 bytes in 4 blocks are still reachable in loss record 31 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xD6928B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xD6A0B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xD691EC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD4FB11: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11421==    by 0xD4FB11: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11421==    by 0xD4E39D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11421==    by 0xD3A77C: rayon_core::job::JobFifo::new (job.rs:193)
==11421==    by 0xD42A9A: rayon_core::registry::main_loop (registry.rs:802)
==11421==    by 0xD3F06F: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11421==    by 0xD3F720: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11421==    by 0xD7814F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11421==    by 0xD70950: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11421== 
==11421== 8,160 bytes in 4 blocks are still reachable in loss record 32 of 32
==11421==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11421==    by 0xDAC33B: alloc::alloc::alloc (alloc.rs:80)
==11421==    by 0xDAC883: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11421==    by 0xDAC29C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11421==    by 0xD9FC89: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11421==    by 0xD9FC89: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11421==    by 0xDA45A5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11421==    by 0xDA4505: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11421==    by 0xDA0AF2: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11421==    by 0xDA8AAD: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11421==    by 0xDA7893: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11421==    by 0xDA6F58: core::ops::function::FnOnce::call_once (function.rs:233)
==11421==    by 0xDACA2B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11421== 
==11421== LEAK SUMMARY:
==11421==    definitely lost: 72 bytes in 1 blocks
==11421==    indirectly lost: 2 bytes in 2 blocks
==11421==      possibly lost: 1,152 bytes in 4 blocks
==11421==    still reachable: 29,176 bytes in 85 blocks
==11421==         suppressed: 0 bytes in 0 blocks
==11421== 
==11421== For counts of detected and suppressed errors, rerun with: -v
==11421== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
