==11431== Memcheck, a memory error detector
==11431== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11431== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11431== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/imported-global
==11431== 
==11431== 
==11431== HEAP SUMMARY:
==11431==     in use at exit: 30,384 bytes in 91 blocks
==11431==   total heap usage: 834 allocs, 743 frees, 143,215 bytes allocated
==11431== 
==11431== 16 bytes in 1 blocks are still reachable in loss record 1 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1A4C08B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0x1A4D463: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0x1A4BFEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0x1AA3B2D: new<std::sync::mutex::Mutex<()>> (boxed.rs:177)
==11431==    by 0x1AA3B2D: backtrace::lock::lock::{{closure}} (lib.rs:134)
==11431==    by 0x1A9E08F: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431==    by 0x1A9E008: std::sync::once::Once::call_once (once.rs:264)
==11431==    by 0x1AA3A62: backtrace::lock::lock (lib.rs:133)
==11431==    by 0x1A3F31B: backtrace::backtrace::trace (mod.rs:52)
==11431==    by 0x1A7B49C: backtrace::capture::Backtrace::create (capture.rs:176)
==11431==    by 0x1A7B413: backtrace::capture::Backtrace::new_unresolved (capture.rs:170)
==11431== 
==11431== 32 bytes in 1 blocks are still reachable in loss record 2 of 31
==11431==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11431==    by 0x4E3F165: dlsym (dlsym.c:70)
==11431==    by 0x1C35B53: fetch (weak.rs:61)
==11431==    by 0x1C35B53: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11431==    by 0x1C35B53: min_stack_size (thread.rs:449)
==11431==    by 0x1C35B53: std::sys::unix::thread::Thread::new (thread.rs:49)
==11431==    by 0xD6EAAB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11431==    by 0xD70D2B: std::thread::Builder::spawn (mod.rs:386)
==11431==    by 0xD3F818: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11431==    by 0xD4095F: rayon_core::registry::Registry::new (registry.rs:256)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431== 
==11431== 40 bytes in 1 blocks are still reachable in loss record 3 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1A4C08B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0x1A4D463: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0x1A4BFEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0x1A7D4DC: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11431==    by 0x1AA3B1E: backtrace::lock::lock::{{closure}} (lib.rs:134)
==11431==    by 0x1A9E08F: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431==    by 0x1A9E008: std::sync::once::Once::call_once (once.rs:264)
==11431==    by 0x1AA3A62: backtrace::lock::lock (lib.rs:133)
==11431==    by 0x1A3F31B: backtrace::backtrace::trace (mod.rs:52)
==11431==    by 0x1A7B49C: backtrace::capture::Backtrace::create (capture.rs:176)
==11431== 
==11431== 64 bytes in 4 blocks are still reachable in loss record 4 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD4FA16: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11431==    by 0xD4FA16: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11431==    by 0xD6B233: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11431==    by 0xD6B383: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11431==    by 0xD6B353: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11431==    by 0xD4E116: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11431==    by 0xD40DDE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11431==    by 0xD79B2C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11431==    by 0xD48EAD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11431== 
==11431== 64 bytes in 4 blocks are still reachable in loss record 5 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C35AAC: alloc (alloc.rs:80)
==11431==    by 0x1C35AAC: alloc (alloc.rs:174)
==11431==    by 0x1C35AAC: exchange_malloc (alloc.rs:277)
==11431==    by 0x1C35AAC: std::sys::unix::thread::Thread::new (thread.rs:44)
==11431==    by 0xD6EAAB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11431==    by 0xD70D2B: std::thread::Builder::spawn (mod.rs:386)
==11431==    by 0xD3F818: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11431==    by 0xD4095F: rayon_core::registry::Registry::new (registry.rs:256)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431==    by 0xD633B0: std::sync::once::Once::call_once (once.rs:264)
==11431==    by 0xD3FD96: rayon_core::registry::set_global_registry (registry.rs:194)
==11431== 
==11431== 72 bytes in 1 blocks are still reachable in loss record 6 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x182823B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0x1828363: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0x182819C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0x182B057: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==11431==    by 0x182B38C: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==11431==    by 0x181CD00: __static_ref_initialize (frame_info.rs:28)
==11431==    by 0x181CD00: core::ops::function::FnOnce::call_once (function.rs:233)
==11431==    by 0x1854A1B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11431==    by 0x1853394: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431==    by 0x1853310: std::sync::once::Once::call_once (once.rs:264)
==11431==    by 0x1818128: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==11431==    by 0x1818128: __stability (lib.rs:142)
==11431==    by 0x1818128: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==11431== 
==11431== 128 bytes in 4 blocks are still reachable in loss record 7 of 31
==11431==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11431==    by 0x1C020DE: register_dtor (fast_thread_local.rs:33)
==11431==    by 0x1C020DE: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11431==    by 0x1C020DE: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11431==    by 0x1C248D9: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11431==    by 0x1C248D9: __getit (local.rs:175)
==11431==    by 0x1C248D9: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11431==    by 0x1C248D9: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11431==    by 0x1C248D9: std::sys_common::thread_info::set (thread_info.rs:40)
==11431==    by 0xD6FF41: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11431==    by 0xD6455E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11431==    by 0x1C35EC9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11431==    by 0x1C35EC9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11431==    by 0x1C35EC9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11431==    by 0x52516DA: start_thread (pthread_create.c:463)
==11431==    by 0x57A271E: clone (clone.S:95)
==11431== 
==11431== 128 bytes in 4 blocks are still reachable in loss record 8 of 31
==11431==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11431==    by 0xDA7DB1: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11431==    by 0xDA7CB2: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11431==    by 0xDA7E56: std::thread::local::fast::Key<T>::get (local.rs:410)
==11431==    by 0xDA7BAC: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11431==    by 0xD52E24: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11431==    by 0xD572B2: crossbeam_epoch::default::with_handle (default.rs:43)
==11431==    by 0xD57516: crossbeam_epoch::default::is_pinned (default.rs:30)
==11431==    by 0xD4E2DC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11431==    by 0xD42C42: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11431==    by 0xD3E0DC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11431== 
==11431== 160 bytes in 4 blocks are still reachable in loss record 9 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD6E28F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11431==    by 0xD819A0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11431==    by 0xD41B8C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11431==    by 0xD64351: core::ops::function::FnMut::call_mut (function.rs:154)
==11431==    by 0xD7A313: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11431==    by 0xD5D333: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11431==    by 0xD7AFF8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11431==    by 0xD791B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11431== 
==11431== 160 bytes in 4 blocks are still reachable in loss record 10 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD6E28F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11431==    by 0xD819A0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11431==    by 0xD41BA4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11431==    by 0xD64351: core::ops::function::FnMut::call_mut (function.rs:154)
==11431==    by 0xD7A313: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11431==    by 0xD5D333: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11431==    by 0xD7AFF8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11431==    by 0xD791B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11431== 
==11431== 160 bytes in 4 blocks are still reachable in loss record 11 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD6E28F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11431==    by 0xD71B53: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11431==    by 0xD5C7FE: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11431==    by 0xD59CAD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11431==    by 0xD5B09A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11431==    by 0xD79FE0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11431==    by 0xD49188: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11431==    by 0xD7AF39: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11431== 
==11431== 160 bytes in 4 blocks are still reachable in loss record 12 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C0347E: alloc (alloc.rs:80)
==11431==    by 0x1C0347E: alloc (alloc.rs:174)
==11431==    by 0x1C0347E: exchange_malloc (alloc.rs:277)
==11431==    by 0x1C0347E: new<()> (mutex.rs:223)
==11431==    by 0x1C0347E: std::thread::Thread::new (mod.rs:1149)
==11431==    by 0xD6E84D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11431==    by 0xD70D2B: std::thread::Builder::spawn (mod.rs:386)
==11431==    by 0xD3F818: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11431==    by 0xD4095F: rayon_core::registry::Registry::new (registry.rs:256)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431==    by 0xD633B0: std::sync::once::Once::call_once (once.rs:264)
==11431==    by 0xD3FD96: rayon_core::registry::set_global_registry (registry.rs:194)
==11431== 
==11431== 160 bytes in 4 blocks are still reachable in loss record 13 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD38E97: alloc::sync::Arc<T>::new (sync.rs:324)
==11431==    by 0xD6E8EB: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11431==    by 0xD70D2B: std::thread::Builder::spawn (mod.rs:386)
==11431==    by 0xD3F818: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11431==    by 0xD4095F: rayon_core::registry::Registry::new (registry.rs:256)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431== 
==11431== 192 bytes in 4 blocks are still reachable in loss record 14 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C20576: alloc (alloc.rs:80)
==11431==    by 0x1C20576: alloc (alloc.rs:174)
==11431==    by 0x1C20576: exchange_malloc (alloc.rs:277)
==11431==    by 0x1C20576: std::sync::condvar::Condvar::new (condvar.rs:130)
==11431==    by 0xD819BC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11431==    by 0xD41B8C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11431==    by 0xD64351: core::ops::function::FnMut::call_mut (function.rs:154)
==11431==    by 0xD7A313: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11431==    by 0xD5D333: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11431==    by 0xD7AFF8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11431==    by 0xD791B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11431==    by 0xD611B1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11431==    by 0xD61894: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11431==    by 0xD629C6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11431== 
==11431== 192 bytes in 4 blocks are still reachable in loss record 15 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C20576: alloc (alloc.rs:80)
==11431==    by 0x1C20576: alloc (alloc.rs:174)
==11431==    by 0x1C20576: exchange_malloc (alloc.rs:277)
==11431==    by 0x1C20576: std::sync::condvar::Condvar::new (condvar.rs:130)
==11431==    by 0xD819BC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11431==    by 0xD41BA4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11431==    by 0xD64351: core::ops::function::FnMut::call_mut (function.rs:154)
==11431==    by 0xD7A313: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11431==    by 0xD5D333: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11431==    by 0xD7AFF8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11431==    by 0xD791B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11431==    by 0xD611B1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11431==    by 0xD61894: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11431==    by 0xD629C6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11431== 
==11431== 192 bytes in 4 blocks are still reachable in loss record 16 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C20576: alloc (alloc.rs:80)
==11431==    by 0x1C20576: alloc (alloc.rs:174)
==11431==    by 0x1C20576: exchange_malloc (alloc.rs:277)
==11431==    by 0x1C20576: std::sync::condvar::Condvar::new (condvar.rs:130)
==11431==    by 0xD5C81A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11431==    by 0xD59CAD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11431==    by 0xD5B09A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11431==    by 0xD79FE0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11431==    by 0xD49188: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11431==    by 0xD7AF39: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11431==    by 0xD7908A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11431==    by 0xD60DB7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11431==    by 0xD619E1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11431==    by 0xD62A25: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11431== 
==11431== 192 bytes in 4 blocks are still reachable in loss record 17 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C034E2: alloc (alloc.rs:80)
==11431==    by 0x1C034E2: alloc (alloc.rs:174)
==11431==    by 0x1C034E2: exchange_malloc (alloc.rs:277)
==11431==    by 0x1C034E2: new (condvar.rs:130)
==11431==    by 0x1C034E2: std::thread::Thread::new (mod.rs:1150)
==11431==    by 0xD6E84D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11431==    by 0xD70D2B: std::thread::Builder::spawn (mod.rs:386)
==11431==    by 0xD3F818: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11431==    by 0xD4095F: rayon_core::registry::Registry::new (registry.rs:256)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431==    by 0xD633B0: std::sync::once::Once::call_once (once.rs:264)
==11431==    by 0xD3FD96: rayon_core::registry::set_global_registry (registry.rs:194)
==11431== 
==11431== 320 bytes in 4 blocks are still reachable in loss record 18 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C03531: alloc (alloc.rs:80)
==11431==    by 0x1C03531: alloc (alloc.rs:174)
==11431==    by 0x1C03531: exchange_malloc (alloc.rs:277)
==11431==    by 0x1C03531: new<std::thread::Inner> (sync.rs:324)
==11431==    by 0x1C03531: std::thread::Thread::new (mod.rs:1145)
==11431==    by 0xD6E84D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11431==    by 0xD70D2B: std::thread::Builder::spawn (mod.rs:386)
==11431==    by 0xD3F818: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11431==    by 0xD4095F: rayon_core::registry::Registry::new (registry.rs:256)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431==    by 0xD633B0: std::sync::once::Once::call_once (once.rs:264)
==11431==    by 0xD3FD96: rayon_core::registry::set_global_registry (registry.rs:194)
==11431== 
==11431== 384 bytes in 1 blocks are still reachable in loss record 19 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xDD071B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xDD0FC3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xDC7ADA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11431==    by 0xD84E20: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11431==    by 0xD83033: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11431==    by 0xD868F2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11431==    by 0xD5FBD8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11431==    by 0xD610C7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11431==    by 0xD61894: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11431==    by 0xD629C6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11431==    by 0xD78E48: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11431== 
==11431== 416 bytes in 4 blocks are still reachable in loss record 20 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD6EA17: new<closure-0> (boxed.rs:177)
==11431==    by 0xD6EA17: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11431==    by 0xD70D2B: std::thread::Builder::spawn (mod.rs:386)
==11431==    by 0xD3F818: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11431==    by 0xD4095F: rayon_core::registry::Registry::new (registry.rs:256)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431== 
==11431== 512 bytes in 1 blocks are still reachable in loss record 21 of 31
==11431==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C25FE9: aligned_malloc (alloc.rs:95)
==11431==    by 0x1C25FE9: alloc (alloc.rs:22)
==11431==    by 0x1C25FE9: __rdl_alloc (alloc.rs:304)
==11431==    by 0xDD071B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xDD0FC3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xDC7ADA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11431==    by 0xD84AC0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11431==    by 0xD82F33: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11431==    by 0xD86A32: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11431==    by 0xD5FBA8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11431==    by 0xD60CF7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11431==    by 0xD619E1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11431== 
==11431== 640 bytes in 1 blocks are still reachable in loss record 22 of 31
==11431==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C25FE9: aligned_malloc (alloc.rs:95)
==11431==    by 0x1C25FE9: alloc (alloc.rs:22)
==11431==    by 0x1C25FE9: __rdl_alloc (alloc.rs:304)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD38CC5: alloc::sync::Arc<T>::new (sync.rs:324)
==11431==    by 0xD40557: rayon_core::registry::Registry::new (registry.rs:234)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431== 
==11431== 640 bytes in 1 blocks are still reachable in loss record 23 of 31
==11431==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C25FE9: aligned_malloc (alloc.rs:95)
==11431==    by 0x1C25FE9: alloc (alloc.rs:22)
==11431==    by 0x1C25FE9: __rdl_alloc (alloc.rs:304)
==11431==    by 0xDAC61B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xDACB63: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xDAC57C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xDA87F5: alloc::sync::Arc<T>::new (sync.rs:324)
==11431==    by 0xDA8D39: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11431==    by 0xDA8D66: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11431==    by 0xDA7259: __static_ref_initialize (default.rs:13)
==11431==    by 0xDA7259: core::ops::function::FnOnce::call_once (function.rs:233)
==11431==    by 0xDA70C5: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11431==    by 0xDA8384: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431== 
==11431== 808 bytes in 1 blocks are still reachable in loss record 24 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x182823B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0x1828363: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0x182819C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0x1836410: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==11431==    by 0x1836410: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==11431==    by 0x181CD19: core::ops::function::FnOnce::call_once (function.rs:233)
==11431==    by 0x182945C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==11431==    by 0x184ED1E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==11431==    by 0x184F0F1: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==11431==    by 0x184FF69: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==11431==    by 0x1817E3F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==11431==    by 0xBE0F04: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==11431== 
==11431== 1,152 bytes in 4 blocks are possibly lost in loss record 25 of 31
==11431==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11431==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11431==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11431==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11431==    by 0x1C35BFC: std::sys::unix::thread::Thread::new (thread.rs:66)
==11431==    by 0xD6EAAB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11431==    by 0xD70D2B: std::thread::Builder::spawn (mod.rs:386)
==11431==    by 0xD3F818: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11431==    by 0xD4095F: rayon_core::registry::Registry::new (registry.rs:256)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431== 
==11431== 1,520 bytes in 1 blocks are still reachable in loss record 26 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD4FDF1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11431==    by 0xD4FDF1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11431==    by 0xD4E67D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11431==    by 0xD40323: rayon_core::registry::Registry::new (registry.rs:238)
==11431==    by 0xD3FA8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11431==    by 0xD3FF49: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11431==    by 0xD63613: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11431==    by 0x1C20C29: std::sync::once::Once::call_inner (once.rs:416)
==11431==    by 0xD633B0: std::sync::once::Once::call_once (once.rs:264)
==11431== 
==11431== 1,536 bytes in 4 blocks are still reachable in loss record 27 of 31
==11431==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0x1C25FE9: aligned_malloc (alloc.rs:95)
==11431==    by 0x1C25FE9: alloc (alloc.rs:22)
==11431==    by 0x1C25FE9: __rdl_alloc (alloc.rs:304)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD39025: alloc::sync::Arc<T>::new (sync.rs:324)
==11431==    by 0xD4E1AD: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11431==    by 0xD40DDE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11431==    by 0xD79B2C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11431==    by 0xD48EAD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11431==    by 0xD7B0E3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11431== 
==11431== 2,008 bytes in 1 blocks are still reachable in loss record 28 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xDAC61B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xDACB63: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xDAC57C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xDA4F39: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11431==    by 0xDA4F39: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11431==    by 0xDA48E5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11431==    by 0xDA4835: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11431==    by 0xDA513B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11431==    by 0xDA0533: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11431==    by 0xDA8D2B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11431==    by 0xDA8D66: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11431==    by 0xDA7259: __static_ref_initialize (default.rs:13)
==11431==    by 0xDA7259: core::ops::function::FnOnce::call_once (function.rs:233)
==11431== 
==11431== 4,096 bytes in 4 blocks are still reachable in loss record 29 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD82A7D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11431==    by 0xD85FE0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11431==    by 0xD8215E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11431==    by 0xD5D97E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11431==    by 0xD4CBC0: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11431==    by 0xD4E099: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11431==    by 0xD40DDE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11431==    by 0xD79B2C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11431==    by 0xD48EAD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11431== 
==11431== 6,080 bytes in 4 blocks are still reachable in loss record 30 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xD6956B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xD6A393: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xD694CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD4FDF1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11431==    by 0xD4FDF1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11431==    by 0xD4E67D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11431==    by 0xD3AA5C: rayon_core::job::JobFifo::new (job.rs:193)
==11431==    by 0xD42D7A: rayon_core::registry::main_loop (registry.rs:802)
==11431==    by 0xD3F34F: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11431==    by 0xD3FA00: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11431==    by 0xD7842F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11431==    by 0xD70C30: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11431== 
==11431== 8,160 bytes in 4 blocks are still reachable in loss record 31 of 31
==11431==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11431==    by 0xDAC61B: alloc::alloc::alloc (alloc.rs:80)
==11431==    by 0xDACB63: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11431==    by 0xDAC57C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11431==    by 0xD9FF69: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11431==    by 0xD9FF69: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11431==    by 0xDA4885: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11431==    by 0xDA47E5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11431==    by 0xDA0DD2: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11431==    by 0xDA8D8D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11431==    by 0xDA7B73: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11431==    by 0xDA7238: core::ops::function::FnOnce::call_once (function.rs:233)
==11431==    by 0xDACD0B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11431== 
==11431== LEAK SUMMARY:
==11431==    definitely lost: 0 bytes in 0 blocks
==11431==    indirectly lost: 0 bytes in 0 blocks
==11431==      possibly lost: 1,152 bytes in 4 blocks
==11431==    still reachable: 29,232 bytes in 87 blocks
==11431==         suppressed: 0 bytes in 0 blocks
==11431== 
==11431== For counts of detected and suppressed errors, rerun with: -v
==11431== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
