==11438== Memcheck, a memory error detector
==11438== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11438== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11438== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/instance
==11438== 
==11438== 
==11438== HEAP SUMMARY:
==11438==     in use at exit: 26,704 bytes in 85 blocks
==11438==   total heap usage: 539 allocs, 454 frees, 100,942 bytes allocated
==11438== 
==11438== 32 bytes in 1 blocks are still reachable in loss record 1 of 29
==11438==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11438==    by 0x4E3F165: dlsym (dlsym.c:70)
==11438==    by 0x1C2BC43: fetch (weak.rs:61)
==11438==    by 0x1C2BC43: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11438==    by 0x1C2BC43: min_stack_size (thread.rs:449)
==11438==    by 0x1C2BC43: std::sys::unix::thread::Thread::new (thread.rs:49)
==11438==    by 0xD64C9B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11438==    by 0xD66F1B: std::thread::Builder::spawn (mod.rs:386)
==11438==    by 0xD35A08: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11438==    by 0xD36B4F: rayon_core::registry::Registry::new (registry.rs:256)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438== 
==11438== 64 bytes in 4 blocks are still reachable in loss record 2 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD45C06: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11438==    by 0xD45C06: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11438==    by 0xD61423: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11438==    by 0xD61573: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11438==    by 0xD61543: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11438==    by 0xD44306: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11438==    by 0xD36FCE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11438==    by 0xD6FD1C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11438==    by 0xD3F09D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11438== 
==11438== 64 bytes in 4 blocks are still reachable in loss record 3 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1C2BB9C: alloc (alloc.rs:80)
==11438==    by 0x1C2BB9C: alloc (alloc.rs:174)
==11438==    by 0x1C2BB9C: exchange_malloc (alloc.rs:277)
==11438==    by 0x1C2BB9C: std::sys::unix::thread::Thread::new (thread.rs:44)
==11438==    by 0xD64C9B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11438==    by 0xD66F1B: std::thread::Builder::spawn (mod.rs:386)
==11438==    by 0xD35A08: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11438==    by 0xD36B4F: rayon_core::registry::Registry::new (registry.rs:256)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438==    by 0xD595A0: std::sync::once::Once::call_once (once.rs:264)
==11438==    by 0xD35F86: rayon_core::registry::set_global_registry (registry.rs:194)
==11438== 
==11438== 72 bytes in 1 blocks are still reachable in loss record 4 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x181E32B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0x181E453: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0x181E28C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0x1821147: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==11438==    by 0x182147C: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==11438==    by 0x1812DF0: __static_ref_initialize (frame_info.rs:28)
==11438==    by 0x1812DF0: core::ops::function::FnOnce::call_once (function.rs:233)
==11438==    by 0x184AB0B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11438==    by 0x1849484: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438==    by 0x1849400: std::sync::once::Once::call_once (once.rs:264)
==11438==    by 0x180E218: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==11438==    by 0x180E218: __stability (lib.rs:142)
==11438==    by 0x180E218: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==11438== 
==11438== 96 bytes in 3 blocks are still reachable in loss record 5 of 29
==11438==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11438==    by 0x1BF81CE: register_dtor (fast_thread_local.rs:33)
==11438==    by 0x1BF81CE: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11438==    by 0x1BF81CE: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11438==    by 0x1C1A9C9: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11438==    by 0x1C1A9C9: __getit (local.rs:175)
==11438==    by 0x1C1A9C9: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11438==    by 0x1C1A9C9: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11438==    by 0x1C1A9C9: std::sys_common::thread_info::set (thread_info.rs:40)
==11438==    by 0xD66131: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11438==    by 0xD5A74E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11438==    by 0x1C2BFB9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11438==    by 0x1C2BFB9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11438==    by 0x1C2BFB9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11438==    by 0x52516DA: start_thread (pthread_create.c:463)
==11438==    by 0x57A271E: clone (clone.S:95)
==11438== 
==11438== 96 bytes in 3 blocks are still reachable in loss record 6 of 29
==11438==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11438==    by 0xD9DFA1: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11438==    by 0xD9DEA2: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11438==    by 0xD9E046: std::thread::local::fast::Key<T>::get (local.rs:410)
==11438==    by 0xD9DD9C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11438==    by 0xD49014: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11438==    by 0xD4D4A2: crossbeam_epoch::default::with_handle (default.rs:43)
==11438==    by 0xD4D706: crossbeam_epoch::default::is_pinned (default.rs:30)
==11438==    by 0xD444CC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11438==    by 0xD38E32: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11438==    by 0xD342CC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11438== 
==11438== 160 bytes in 4 blocks are still reachable in loss record 7 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD6447F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11438==    by 0xD77B90: rayon_core::latch::LockLatch::new (latch.rs:230)
==11438==    by 0xD37D7C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11438==    by 0xD5A541: core::ops::function::FnMut::call_mut (function.rs:154)
==11438==    by 0xD70503: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11438==    by 0xD53523: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11438==    by 0xD711E8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11438==    by 0xD6F3A9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11438== 
==11438== 160 bytes in 4 blocks are still reachable in loss record 8 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD6447F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11438==    by 0xD77B90: rayon_core::latch::LockLatch::new (latch.rs:230)
==11438==    by 0xD37D94: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11438==    by 0xD5A541: core::ops::function::FnMut::call_mut (function.rs:154)
==11438==    by 0xD70503: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11438==    by 0xD53523: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11438==    by 0xD711E8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11438==    by 0xD6F3A9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11438== 
==11438== 160 bytes in 4 blocks are still reachable in loss record 9 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD6447F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11438==    by 0xD67D43: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11438==    by 0xD529EE: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11438==    by 0xD4FE9D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11438==    by 0xD5128A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11438==    by 0xD701D0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11438==    by 0xD3F378: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11438==    by 0xD71129: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11438== 
==11438== 160 bytes in 4 blocks are still reachable in loss record 10 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1BF956E: alloc (alloc.rs:80)
==11438==    by 0x1BF956E: alloc (alloc.rs:174)
==11438==    by 0x1BF956E: exchange_malloc (alloc.rs:277)
==11438==    by 0x1BF956E: new<()> (mutex.rs:223)
==11438==    by 0x1BF956E: std::thread::Thread::new (mod.rs:1149)
==11438==    by 0xD64A3D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11438==    by 0xD66F1B: std::thread::Builder::spawn (mod.rs:386)
==11438==    by 0xD35A08: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11438==    by 0xD36B4F: rayon_core::registry::Registry::new (registry.rs:256)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438==    by 0xD595A0: std::sync::once::Once::call_once (once.rs:264)
==11438==    by 0xD35F86: rayon_core::registry::set_global_registry (registry.rs:194)
==11438== 
==11438== 160 bytes in 4 blocks are still reachable in loss record 11 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD2F087: alloc::sync::Arc<T>::new (sync.rs:324)
==11438==    by 0xD64ADB: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11438==    by 0xD66F1B: std::thread::Builder::spawn (mod.rs:386)
==11438==    by 0xD35A08: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11438==    by 0xD36B4F: rayon_core::registry::Registry::new (registry.rs:256)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438== 
==11438== 192 bytes in 4 blocks are still reachable in loss record 12 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1C16666: alloc (alloc.rs:80)
==11438==    by 0x1C16666: alloc (alloc.rs:174)
==11438==    by 0x1C16666: exchange_malloc (alloc.rs:277)
==11438==    by 0x1C16666: std::sync::condvar::Condvar::new (condvar.rs:130)
==11438==    by 0xD77BAC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11438==    by 0xD37D7C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11438==    by 0xD5A541: core::ops::function::FnMut::call_mut (function.rs:154)
==11438==    by 0xD70503: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11438==    by 0xD53523: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11438==    by 0xD711E8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11438==    by 0xD6F3A9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11438==    by 0xD573A1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11438==    by 0xD57A84: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11438==    by 0xD58BB6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11438== 
==11438== 192 bytes in 4 blocks are still reachable in loss record 13 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1C16666: alloc (alloc.rs:80)
==11438==    by 0x1C16666: alloc (alloc.rs:174)
==11438==    by 0x1C16666: exchange_malloc (alloc.rs:277)
==11438==    by 0x1C16666: std::sync::condvar::Condvar::new (condvar.rs:130)
==11438==    by 0xD77BAC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11438==    by 0xD37D94: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11438==    by 0xD5A541: core::ops::function::FnMut::call_mut (function.rs:154)
==11438==    by 0xD70503: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11438==    by 0xD53523: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11438==    by 0xD711E8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11438==    by 0xD6F3A9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11438==    by 0xD573A1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11438==    by 0xD57A84: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11438==    by 0xD58BB6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11438== 
==11438== 192 bytes in 4 blocks are still reachable in loss record 14 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1C16666: alloc (alloc.rs:80)
==11438==    by 0x1C16666: alloc (alloc.rs:174)
==11438==    by 0x1C16666: exchange_malloc (alloc.rs:277)
==11438==    by 0x1C16666: std::sync::condvar::Condvar::new (condvar.rs:130)
==11438==    by 0xD52A0A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11438==    by 0xD4FE9D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11438==    by 0xD5128A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11438==    by 0xD701D0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11438==    by 0xD3F378: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11438==    by 0xD71129: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11438==    by 0xD6F27A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11438==    by 0xD56FA7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11438==    by 0xD57BD1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11438==    by 0xD58C15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11438== 
==11438== 192 bytes in 4 blocks are still reachable in loss record 15 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1BF95D2: alloc (alloc.rs:80)
==11438==    by 0x1BF95D2: alloc (alloc.rs:174)
==11438==    by 0x1BF95D2: exchange_malloc (alloc.rs:277)
==11438==    by 0x1BF95D2: new (condvar.rs:130)
==11438==    by 0x1BF95D2: std::thread::Thread::new (mod.rs:1150)
==11438==    by 0xD64A3D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11438==    by 0xD66F1B: std::thread::Builder::spawn (mod.rs:386)
==11438==    by 0xD35A08: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11438==    by 0xD36B4F: rayon_core::registry::Registry::new (registry.rs:256)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438==    by 0xD595A0: std::sync::once::Once::call_once (once.rs:264)
==11438==    by 0xD35F86: rayon_core::registry::set_global_registry (registry.rs:194)
==11438== 
==11438== 320 bytes in 4 blocks are still reachable in loss record 16 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1BF9621: alloc (alloc.rs:80)
==11438==    by 0x1BF9621: alloc (alloc.rs:174)
==11438==    by 0x1BF9621: exchange_malloc (alloc.rs:277)
==11438==    by 0x1BF9621: new<std::thread::Inner> (sync.rs:324)
==11438==    by 0x1BF9621: std::thread::Thread::new (mod.rs:1145)
==11438==    by 0xD64A3D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11438==    by 0xD66F1B: std::thread::Builder::spawn (mod.rs:386)
==11438==    by 0xD35A08: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11438==    by 0xD36B4F: rayon_core::registry::Registry::new (registry.rs:256)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438==    by 0xD595A0: std::sync::once::Once::call_once (once.rs:264)
==11438==    by 0xD35F86: rayon_core::registry::set_global_registry (registry.rs:194)
==11438== 
==11438== 384 bytes in 1 blocks are still reachable in loss record 17 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xDC690B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xDC71B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xDBDCCA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11438==    by 0xD7B010: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11438==    by 0xD79223: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11438==    by 0xD7CAE2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11438==    by 0xD55DC8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11438==    by 0xD572B7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11438==    by 0xD57A84: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11438==    by 0xD58BB6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11438==    by 0xD6F038: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11438== 
==11438== 416 bytes in 4 blocks are still reachable in loss record 18 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD64C07: new<closure-0> (boxed.rs:177)
==11438==    by 0xD64C07: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11438==    by 0xD66F1B: std::thread::Builder::spawn (mod.rs:386)
==11438==    by 0xD35A08: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11438==    by 0xD36B4F: rayon_core::registry::Registry::new (registry.rs:256)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438== 
==11438== 512 bytes in 1 blocks are still reachable in loss record 19 of 29
==11438==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1C1C0D9: aligned_malloc (alloc.rs:95)
==11438==    by 0x1C1C0D9: alloc (alloc.rs:22)
==11438==    by 0x1C1C0D9: __rdl_alloc (alloc.rs:304)
==11438==    by 0xDC690B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xDC71B3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xDBDCCA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11438==    by 0xD7ACB0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11438==    by 0xD79123: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11438==    by 0xD7CC22: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11438==    by 0xD55D98: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11438==    by 0xD56EE7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11438==    by 0xD57BD1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11438== 
==11438== 640 bytes in 1 blocks are still reachable in loss record 20 of 29
==11438==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1C1C0D9: aligned_malloc (alloc.rs:95)
==11438==    by 0x1C1C0D9: alloc (alloc.rs:22)
==11438==    by 0x1C1C0D9: __rdl_alloc (alloc.rs:304)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD2EEB5: alloc::sync::Arc<T>::new (sync.rs:324)
==11438==    by 0xD36747: rayon_core::registry::Registry::new (registry.rs:234)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438== 
==11438== 640 bytes in 1 blocks are still reachable in loss record 21 of 29
==11438==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1C1C0D9: aligned_malloc (alloc.rs:95)
==11438==    by 0x1C1C0D9: alloc (alloc.rs:22)
==11438==    by 0x1C1C0D9: __rdl_alloc (alloc.rs:304)
==11438==    by 0xDA280B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xDA2D53: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xDA276C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD9E9E5: alloc::sync::Arc<T>::new (sync.rs:324)
==11438==    by 0xD9EF29: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11438==    by 0xD9EF56: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11438==    by 0xD9D449: __static_ref_initialize (default.rs:13)
==11438==    by 0xD9D449: core::ops::function::FnOnce::call_once (function.rs:233)
==11438==    by 0xD9D2B5: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11438==    by 0xD9E574: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438== 
==11438== 808 bytes in 1 blocks are still reachable in loss record 22 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x181E32B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0x181E453: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0x181E28C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0x182C500: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==11438==    by 0x182C500: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==11438==    by 0x1812E09: core::ops::function::FnOnce::call_once (function.rs:233)
==11438==    by 0x181F54C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==11438==    by 0x1844E0E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==11438==    by 0x18451E1: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==11438==    by 0x1846059: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==11438==    by 0x180DF2F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==11438==    by 0xBD70F4: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==11438== 
==11438== 1,152 bytes in 4 blocks are possibly lost in loss record 23 of 29
==11438==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11438==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11438==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11438==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11438==    by 0x1C2BCEC: std::sys::unix::thread::Thread::new (thread.rs:66)
==11438==    by 0xD64C9B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11438==    by 0xD66F1B: std::thread::Builder::spawn (mod.rs:386)
==11438==    by 0xD35A08: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11438==    by 0xD36B4F: rayon_core::registry::Registry::new (registry.rs:256)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438== 
==11438== 1,520 bytes in 1 blocks are still reachable in loss record 24 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD45FE1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11438==    by 0xD45FE1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11438==    by 0xD4486D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11438==    by 0xD36513: rayon_core::registry::Registry::new (registry.rs:238)
==11438==    by 0xD35C7D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11438==    by 0xD36139: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11438==    by 0xD59803: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11438==    by 0x1C16D19: std::sync::once::Once::call_inner (once.rs:416)
==11438==    by 0xD595A0: std::sync::once::Once::call_once (once.rs:264)
==11438== 
==11438== 1,536 bytes in 4 blocks are still reachable in loss record 25 of 29
==11438==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0x1C1C0D9: aligned_malloc (alloc.rs:95)
==11438==    by 0x1C1C0D9: alloc (alloc.rs:22)
==11438==    by 0x1C1C0D9: __rdl_alloc (alloc.rs:304)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD2F215: alloc::sync::Arc<T>::new (sync.rs:324)
==11438==    by 0xD4439D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11438==    by 0xD36FCE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11438==    by 0xD6FD1C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11438==    by 0xD3F09D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11438==    by 0xD712D3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11438== 
==11438== 2,008 bytes in 1 blocks are still reachable in loss record 26 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xDA280B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xDA2D53: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xDA276C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD9B129: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11438==    by 0xD9B129: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11438==    by 0xD9AAD5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11438==    by 0xD9AA25: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11438==    by 0xD9B32B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11438==    by 0xD96723: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11438==    by 0xD9EF1B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11438==    by 0xD9EF56: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11438==    by 0xD9D449: __static_ref_initialize (default.rs:13)
==11438==    by 0xD9D449: core::ops::function::FnOnce::call_once (function.rs:233)
==11438== 
==11438== 4,096 bytes in 4 blocks are still reachable in loss record 27 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD78C6D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11438==    by 0xD7C1D0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11438==    by 0xD7834E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11438==    by 0xD53B6E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11438==    by 0xD42DB0: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11438==    by 0xD44289: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11438==    by 0xD36FCE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11438==    by 0xD6FD1C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11438==    by 0xD3F09D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11438== 
==11438== 4,560 bytes in 3 blocks are still reachable in loss record 28 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xD5F75B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xD60583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xD5F6BC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD45FE1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11438==    by 0xD45FE1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11438==    by 0xD4486D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11438==    by 0xD30C4C: rayon_core::job::JobFifo::new (job.rs:193)
==11438==    by 0xD38F6A: rayon_core::registry::main_loop (registry.rs:802)
==11438==    by 0xD3553F: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11438==    by 0xD35BF0: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11438==    by 0xD6E61F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11438==    by 0xD66E20: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11438== 
==11438== 6,120 bytes in 3 blocks are still reachable in loss record 29 of 29
==11438==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11438==    by 0xDA280B: alloc::alloc::alloc (alloc.rs:80)
==11438==    by 0xDA2D53: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11438==    by 0xDA276C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11438==    by 0xD96159: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11438==    by 0xD96159: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11438==    by 0xD9AA75: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11438==    by 0xD9A9D5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11438==    by 0xD96FC2: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11438==    by 0xD9EF7D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11438==    by 0xD9DD63: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11438==    by 0xD9D428: core::ops::function::FnOnce::call_once (function.rs:233)
==11438==    by 0xDA2EFB: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11438== 
==11438== LEAK SUMMARY:
==11438==    definitely lost: 0 bytes in 0 blocks
==11438==    indirectly lost: 0 bytes in 0 blocks
==11438==      possibly lost: 1,152 bytes in 4 blocks
==11438==    still reachable: 25,552 bytes in 81 blocks
==11438==         suppressed: 0 bytes in 0 blocks
==11438== 
==11438== For counts of detected and suppressed errors, rerun with: -v
==11438== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
