==29860== Memcheck, a memory error detector
==29860== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29860== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29860== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/memory
==29860== 
==29860== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==29860== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==29860== 
==29860== HEAP SUMMARY:
==29860==     in use at exit: 30,336 bytes in 90 blocks
==29860==   total heap usage: 1,019 allocs, 929 frees, 183,696 bytes allocated
==29860== 
==29860== 8 bytes in 1 blocks are still reachable in loss record 1 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD4B1F2: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29860==    by 0xD4B1F2: rayon_core::util::leak (util.rs:5)
==29860==    by 0xD504EE: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29860==    by 0xD86528: core::result::Result<T,E>::map (result.rs:519)
==29860==    by 0xD50589: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860==    by 0xD739C0: std::sync::once::Once::call_once (once.rs:264)
==29860==    by 0xD50496: rayon_core::registry::set_global_registry (registry.rs:194)
==29860== 
==29860== 32 bytes in 1 blocks are still reachable in loss record 2 of 30
==29860==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29860==    by 0x4E3F165: dlsym (dlsym.c:70)
==29860==    by 0x1C46003: fetch (weak.rs:61)
==29860==    by 0x1C46003: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29860==    by 0x1C46003: min_stack_size (thread.rs:449)
==29860==    by 0x1C46003: std::sys::unix::thread::Thread::new (thread.rs:49)
==29860==    by 0xD7FF2B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29860==    by 0xD8115B: std::thread::Builder::spawn (mod.rs:386)
==29860==    by 0xD4FF78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29860==    by 0xD5105F: rayon_core::registry::Registry::new (registry.rs:260)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860== 
==29860== 64 bytes in 4 blocks are still reachable in loss record 3 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD5EED6: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29860==    by 0xD5EED6: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29860==    by 0xD7B783: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29860==    by 0xD7B8D3: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29860==    by 0xD7B8A3: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29860==    by 0xD5D5D6: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29860==    by 0xD514DE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29860==    by 0xD8A1EC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29860==    by 0xD5AE3D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29860== 
==29860== 64 bytes in 4 blocks are still reachable in loss record 4 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C45F5C: alloc (alloc.rs:80)
==29860==    by 0x1C45F5C: alloc (alloc.rs:174)
==29860==    by 0x1C45F5C: exchange_malloc (alloc.rs:277)
==29860==    by 0x1C45F5C: std::sys::unix::thread::Thread::new (thread.rs:44)
==29860==    by 0xD7FF2B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29860==    by 0xD8115B: std::thread::Builder::spawn (mod.rs:386)
==29860==    by 0xD4FF78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29860==    by 0xD5105F: rayon_core::registry::Registry::new (registry.rs:260)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860==    by 0xD739C0: std::sync::once::Once::call_once (once.rs:264)
==29860==    by 0xD50496: rayon_core::registry::set_global_registry (registry.rs:194)
==29860== 
==29860== 72 bytes in 1 blocks are still reachable in loss record 5 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x18386EB: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0x1838813: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0x183864C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0x183B507: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==29860==    by 0x183B83C: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==29860==    by 0x182D1B0: __static_ref_initialize (frame_info.rs:28)
==29860==    by 0x182D1B0: core::ops::function::FnOnce::call_once (function.rs:233)
==29860==    by 0x1864ECB: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29860==    by 0x1863844: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860==    by 0x18637C0: std::sync::once::Once::call_once (once.rs:264)
==29860==    by 0x18285D8: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==29860==    by 0x18285D8: __stability (lib.rs:142)
==29860==    by 0x18285D8: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==29860== 
==29860== 128 bytes in 4 blocks are still reachable in loss record 6 of 30
==29860==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29860==    by 0x1C1258E: register_dtor (fast_thread_local.rs:33)
==29860==    by 0x1C1258E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29860==    by 0x1C1258E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29860==    by 0x1C34D89: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29860==    by 0x1C34D89: __getit (local.rs:175)
==29860==    by 0x1C34D89: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29860==    by 0x1C34D89: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29860==    by 0x1C34D89: std::sys_common::thread_info::set (thread_info.rs:40)
==29860==    by 0xD802F1: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29860==    by 0xD74A0E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29860==    by 0x1C46379: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29860==    by 0x1C46379: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29860==    by 0x1C46379: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29860==    by 0x52516DA: start_thread (pthread_create.c:463)
==29860==    by 0x57A271E: clone (clone.S:95)
==29860== 
==29860== 128 bytes in 4 blocks are still reachable in loss record 7 of 30
==29860==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29860==    by 0xDB8261: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29860==    by 0xDB8162: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29860==    by 0xDB8306: std::thread::local::fast::Key<T>::get (local.rs:410)
==29860==    by 0xDB805C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29860==    by 0xD61D04: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29860==    by 0xD67692: crossbeam_epoch::default::with_handle (default.rs:43)
==29860==    by 0xD67976: crossbeam_epoch::default::is_pinned (default.rs:30)
==29860==    by 0xD5D79C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29860==    by 0xD53342: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29860==    by 0xD4E72C: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29860== 
==29860== 160 bytes in 4 blocks are still reachable in loss record 8 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD7E63F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29860==    by 0xD91E50: rayon_core::latch::LockLatch::new (latch.rs:230)
==29860==    by 0xD5228C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29860==    by 0xD74921: core::ops::function::FnMut::call_mut (function.rs:154)
==29860==    by 0xD89F03: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29860==    by 0xD6D8A3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29860==    by 0xD8B7B8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29860==    by 0xD896B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29860== 
==29860== 160 bytes in 4 blocks are still reachable in loss record 9 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD7E63F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29860==    by 0xD91E50: rayon_core::latch::LockLatch::new (latch.rs:230)
==29860==    by 0xD522A4: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29860==    by 0xD74921: core::ops::function::FnMut::call_mut (function.rs:154)
==29860==    by 0xD89F03: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29860==    by 0xD6D8A3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29860==    by 0xD8B7B8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29860==    by 0xD896B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29860== 
==29860== 160 bytes in 4 blocks are still reachable in loss record 10 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD7E63F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29860==    by 0xD81FB3: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29860==    by 0xD6CC9E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29860==    by 0xD6A0CD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29860==    by 0xD6B53A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29860==    by 0xD8A0B0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29860==    by 0xD5AC48: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29860==    by 0xD8B889: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29860== 
==29860== 160 bytes in 4 blocks are still reachable in loss record 11 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C1392E: alloc (alloc.rs:80)
==29860==    by 0x1C1392E: alloc (alloc.rs:174)
==29860==    by 0x1C1392E: exchange_malloc (alloc.rs:277)
==29860==    by 0x1C1392E: new<()> (mutex.rs:223)
==29860==    by 0x1C1392E: std::thread::Thread::new (mod.rs:1149)
==29860==    by 0xD7FCCD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29860==    by 0xD8115B: std::thread::Builder::spawn (mod.rs:386)
==29860==    by 0xD4FF78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29860==    by 0xD5105F: rayon_core::registry::Registry::new (registry.rs:260)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860==    by 0xD739C0: std::sync::once::Once::call_once (once.rs:264)
==29860==    by 0xD50496: rayon_core::registry::set_global_registry (registry.rs:194)
==29860== 
==29860== 160 bytes in 4 blocks are still reachable in loss record 12 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD49697: alloc::sync::Arc<T>::new (sync.rs:324)
==29860==    by 0xD7FD6B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29860==    by 0xD8115B: std::thread::Builder::spawn (mod.rs:386)
==29860==    by 0xD4FF78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29860==    by 0xD5105F: rayon_core::registry::Registry::new (registry.rs:260)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860== 
==29860== 192 bytes in 4 blocks are still reachable in loss record 13 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C30A26: alloc (alloc.rs:80)
==29860==    by 0x1C30A26: alloc (alloc.rs:174)
==29860==    by 0x1C30A26: exchange_malloc (alloc.rs:277)
==29860==    by 0x1C30A26: std::sync::condvar::Condvar::new (condvar.rs:130)
==29860==    by 0xD91E6C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29860==    by 0xD5228C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29860==    by 0xD74921: core::ops::function::FnMut::call_mut (function.rs:154)
==29860==    by 0xD89F03: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29860==    by 0xD6D8A3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29860==    by 0xD8B7B8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29860==    by 0xD896B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29860==    by 0xD71291: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29860==    by 0xD71F14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29860==    by 0xD72EB6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29860== 
==29860== 192 bytes in 4 blocks are still reachable in loss record 14 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C30A26: alloc (alloc.rs:80)
==29860==    by 0x1C30A26: alloc (alloc.rs:174)
==29860==    by 0x1C30A26: exchange_malloc (alloc.rs:277)
==29860==    by 0x1C30A26: std::sync::condvar::Condvar::new (condvar.rs:130)
==29860==    by 0xD91E6C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29860==    by 0xD522A4: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29860==    by 0xD74921: core::ops::function::FnMut::call_mut (function.rs:154)
==29860==    by 0xD89F03: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29860==    by 0xD6D8A3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29860==    by 0xD8B7B8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29860==    by 0xD896B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29860==    by 0xD71291: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29860==    by 0xD71F14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29860==    by 0xD72EB6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29860== 
==29860== 192 bytes in 4 blocks are still reachable in loss record 15 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C30A26: alloc (alloc.rs:80)
==29860==    by 0x1C30A26: alloc (alloc.rs:174)
==29860==    by 0x1C30A26: exchange_malloc (alloc.rs:277)
==29860==    by 0x1C30A26: std::sync::condvar::Condvar::new (condvar.rs:130)
==29860==    by 0xD6CCBA: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29860==    by 0xD6A0CD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29860==    by 0xD6B53A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29860==    by 0xD8A0B0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29860==    by 0xD5AC48: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29860==    by 0xD8B889: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29860==    by 0xD894EA: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29860==    by 0xD71657: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29860==    by 0xD71E71: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29860==    by 0xD72E55: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29860== 
==29860== 192 bytes in 4 blocks are still reachable in loss record 16 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C13992: alloc (alloc.rs:80)
==29860==    by 0x1C13992: alloc (alloc.rs:174)
==29860==    by 0x1C13992: exchange_malloc (alloc.rs:277)
==29860==    by 0x1C13992: new (condvar.rs:130)
==29860==    by 0x1C13992: std::thread::Thread::new (mod.rs:1150)
==29860==    by 0xD7FCCD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29860==    by 0xD8115B: std::thread::Builder::spawn (mod.rs:386)
==29860==    by 0xD4FF78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29860==    by 0xD5105F: rayon_core::registry::Registry::new (registry.rs:260)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860==    by 0xD739C0: std::sync::once::Once::call_once (once.rs:264)
==29860==    by 0xD50496: rayon_core::registry::set_global_registry (registry.rs:194)
==29860== 
==29860== 320 bytes in 4 blocks are still reachable in loss record 17 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C139E1: alloc (alloc.rs:80)
==29860==    by 0x1C139E1: alloc (alloc.rs:174)
==29860==    by 0x1C139E1: exchange_malloc (alloc.rs:277)
==29860==    by 0x1C139E1: new<std::thread::Inner> (sync.rs:324)
==29860==    by 0x1C139E1: std::thread::Thread::new (mod.rs:1145)
==29860==    by 0xD7FCCD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29860==    by 0xD8115B: std::thread::Builder::spawn (mod.rs:386)
==29860==    by 0xD4FF78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29860==    by 0xD5105F: rayon_core::registry::Registry::new (registry.rs:260)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860==    by 0xD739C0: std::sync::once::Once::call_once (once.rs:264)
==29860==    by 0xD50496: rayon_core::registry::set_global_registry (registry.rs:194)
==29860== 
==29860== 384 bytes in 1 blocks are still reachable in loss record 18 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xDE0BCB: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xDE1473: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xDD7F8A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29860==    by 0xD94C10: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29860==    by 0xD93563: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29860==    by 0xD97162: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29860==    by 0xD70048: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29860==    by 0xD711A7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29860==    by 0xD71F14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29860==    by 0xD72EB6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29860==    by 0xD89318: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29860== 
==29860== 416 bytes in 4 blocks are still reachable in loss record 19 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD7FE97: new<closure-0> (boxed.rs:177)
==29860==    by 0xD7FE97: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29860==    by 0xD8115B: std::thread::Builder::spawn (mod.rs:386)
==29860==    by 0xD4FF78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29860==    by 0xD5105F: rayon_core::registry::Registry::new (registry.rs:260)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860== 
==29860== 512 bytes in 1 blocks are still reachable in loss record 20 of 30
==29860==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C36499: aligned_malloc (alloc.rs:95)
==29860==    by 0x1C36499: alloc (alloc.rs:22)
==29860==    by 0x1C36499: __rdl_alloc (alloc.rs:304)
==29860==    by 0xDE0BCB: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xDE1473: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xDD7F8A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29860==    by 0xD94F70: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29860==    by 0xD93463: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29860==    by 0xD970C2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29860==    by 0xD6FFE8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29860==    by 0xD71597: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29860==    by 0xD71E71: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29860== 
==29860== 640 bytes in 1 blocks are still reachable in loss record 21 of 30
==29860==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C36499: aligned_malloc (alloc.rs:95)
==29860==    by 0x1C36499: alloc (alloc.rs:22)
==29860==    by 0x1C36499: __rdl_alloc (alloc.rs:304)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD494C5: alloc::sync::Arc<T>::new (sync.rs:324)
==29860==    by 0xD50C57: rayon_core::registry::Registry::new (registry.rs:238)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860== 
==29860== 640 bytes in 1 blocks are still reachable in loss record 22 of 30
==29860==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C36499: aligned_malloc (alloc.rs:95)
==29860==    by 0x1C36499: alloc (alloc.rs:22)
==29860==    by 0x1C36499: __rdl_alloc (alloc.rs:304)
==29860==    by 0xDBCACB: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xDBD013: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xDBCA2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xDB8CA5: alloc::sync::Arc<T>::new (sync.rs:324)
==29860==    by 0xDB91E9: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29860==    by 0xDB9216: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29860==    by 0xDB7709: __static_ref_initialize (default.rs:13)
==29860==    by 0xDB7709: core::ops::function::FnOnce::call_once (function.rs:233)
==29860==    by 0xDB7575: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29860==    by 0xDB8834: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860== 
==29860== 808 bytes in 1 blocks are still reachable in loss record 23 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x18386EB: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0x1838813: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0x183864C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0x18468C0: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==29860==    by 0x18468C0: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==29860==    by 0x182D1C9: core::ops::function::FnOnce::call_once (function.rs:233)
==29860==    by 0x183990C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==29860==    by 0x185F1CE: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==29860==    by 0x185F5A1: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==29860==    by 0x1860419: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==29860==    by 0x18282EF: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==29860==    by 0xBF15C4: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==29860== 
==29860== 1,152 bytes in 4 blocks are possibly lost in loss record 24 of 30
==29860==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29860==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29860==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29860==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29860==    by 0x1C460AC: std::sys::unix::thread::Thread::new (thread.rs:66)
==29860==    by 0xD7FF2B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29860==    by 0xD8115B: std::thread::Builder::spawn (mod.rs:386)
==29860==    by 0xD4FF78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29860==    by 0xD5105F: rayon_core::registry::Registry::new (registry.rs:260)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860== 
==29860== 1,520 bytes in 1 blocks are still reachable in loss record 25 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD5F2B1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29860==    by 0xD5F2B1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29860==    by 0xD5DB3D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29860==    by 0xD50A23: rayon_core::registry::Registry::new (registry.rs:242)
==29860==    by 0xD501ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29860==    by 0xD50579: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29860==    by 0xD73A43: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29860==    by 0x1C310D9: std::sync::once::Once::call_inner (once.rs:416)
==29860==    by 0xD739C0: std::sync::once::Once::call_once (once.rs:264)
==29860== 
==29860== 1,536 bytes in 4 blocks are still reachable in loss record 26 of 30
==29860==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0x1C36499: aligned_malloc (alloc.rs:95)
==29860==    by 0x1C36499: alloc (alloc.rs:22)
==29860==    by 0x1C36499: __rdl_alloc (alloc.rs:304)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD492E5: alloc::sync::Arc<T>::new (sync.rs:324)
==29860==    by 0xD5D66D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29860==    by 0xD514DE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29860==    by 0xD8A1EC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29860==    by 0xD5AE3D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29860==    by 0xD8BA43: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29860== 
==29860== 2,008 bytes in 1 blocks are still reachable in loss record 27 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xDBCACB: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xDBD013: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xDBCA2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xDB53E9: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29860==    by 0xDB53E9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29860==    by 0xDB4D95: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29860==    by 0xDB4CE5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29860==    by 0xDB55EB: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29860==    by 0xDB09E3: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29860==    by 0xDB91DB: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29860==    by 0xDB9216: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29860==    by 0xDB7709: __static_ref_initialize (default.rs:13)
==29860==    by 0xDB7709: core::ops::function::FnOnce::call_once (function.rs:233)
==29860== 
==29860== 4,096 bytes in 4 blocks are still reachable in loss record 28 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD9321D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29860==    by 0xD96490: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29860==    by 0xD9260E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29860==    by 0xD6DE1E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29860==    by 0xD5C080: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29860==    by 0xD5D559: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29860==    by 0xD514DE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29860==    by 0xD8A1EC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29860==    by 0xD5AE3D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29860== 
==29860== 6,080 bytes in 4 blocks are still reachable in loss record 29 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xD79A2B: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xD7A853: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xD7998C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xD5F2B1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29860==    by 0xD5F2B1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29860==    by 0xD5DB3D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29860==    by 0xD4B0BC: rayon_core::job::JobFifo::new (job.rs:193)
==29860==    by 0xD5347A: rayon_core::registry::main_loop (registry.rs:806)
==29860==    by 0xD4FAAF: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29860==    by 0xD50160: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29860==    by 0xD88A0F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29860==    by 0xD80FE0: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29860== 
==29860== 8,160 bytes in 4 blocks are still reachable in loss record 30 of 30
==29860==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29860==    by 0xDBCACB: alloc::alloc::alloc (alloc.rs:80)
==29860==    by 0xDBD013: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29860==    by 0xDBCA2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29860==    by 0xDB0419: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29860==    by 0xDB0419: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29860==    by 0xDB4D35: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29860==    by 0xDB4C95: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29860==    by 0xDB1282: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29860==    by 0xDB923D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29860==    by 0xDB8023: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29860==    by 0xDB76E8: core::ops::function::FnOnce::call_once (function.rs:233)
==29860==    by 0xDBD1BB: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29860== 
==29860== LEAK SUMMARY:
==29860==    definitely lost: 0 bytes in 0 blocks
==29860==    indirectly lost: 0 bytes in 0 blocks
==29860==      possibly lost: 1,152 bytes in 4 blocks
==29860==    still reachable: 29,184 bytes in 86 blocks
==29860==         suppressed: 0 bytes in 0 blocks
==29860== 
==29860== For counts of detected and suppressed errors, rerun with: -v
==29860== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
