==4347== Memcheck, a memory error detector
==4347== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4347== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==4347== Command: /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b
==4347== 
--4347-- WARNING: unhandled amd64-linux syscall: 332
--4347-- You may be able to write your own handler.
--4347-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--4347-- Nevertheless we consider this a bug.  Please report
--4347-- it at http://valgrind.org/support/bug_reports.html.
==4347== Thread 2 test_wasi:
==4347== Conditional jump or move depends on uninitialised value(s)
==4347==    at 0x7F108D: wasmparser::validator::Validator::end (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x7E6B8C: wasmparser::validator::Validator::payload (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x7E5E01: wasmparser::validator::Validator::validate_all (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F378C: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3BEEB8: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::validate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E0794: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A1563: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3AB0: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347== 
==4347== Thread 3:
==4347== Conditional jump or move depends on uninitialised value(s)
==4347==    at 0x4E04C8: cranelift_codegen::isa::unwind::systemv::UnwindInfo::build (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x5994A2: cranelift_codegen::isa::x86::unwind::systemv::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x462682: cranelift_codegen::isa::x86::abi::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x493DF8: <cranelift_codegen::isa::x86::Isa as cranelift_codegen::isa::TargetIsa>::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x49822C: cranelift_codegen::context::Context::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3FD87B: wasmer_compiler_cranelift::translator::unwind::compiled_function_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F5142: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x402F4E: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x40C3C8: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E9F0A: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E8566: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F34C1: _ZN10rayon_core4join12join_context28_$u7b$$u7b$closure$u7d$$u7d$17hdd5b099c3d4f7436E.llvm.9017103831828045350 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347== 
==4347== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==4347== Thread 2 test_wasi:
==4347== Invalid write of size 8
==4347==    at 0x815C04: wasmer_vm::memory::LinearMemory::new_internal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x815938: wasmer_vm::memory::LinearMemory::from_definition (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E4531: <wasmer::tunables::Tunables as wasmer_engine::tunables::Tunables>::create_vm_memory (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A31F8: wasmer_engine::tunables::Tunables::create_memories (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DA199: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E0B4E: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6DF1F0: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D72: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==  Address 0x6f19910 is 2,784 bytes inside an unallocated block of size 4,176 in arena "client"
==4347== 
==4347== Invalid write of size 4
==4347==    at 0x815C07: wasmer_vm::memory::LinearMemory::new_internal (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x815938: wasmer_vm::memory::LinearMemory::from_definition (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E4531: <wasmer::tunables::Tunables as wasmer_engine::tunables::Tunables>::create_vm_memory (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A31F8: wasmer_engine::tunables::Tunables::create_memories (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DA199: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E0B4E: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6DF1F0: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D72: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==  Address 0x6f19918 is 2,792 bytes inside an unallocated block of size 4,176 in arena "client"
==4347== 
==4347== Invalid write of size 8
==4347==    at 0x809055: wasmer_vm::table::LinearTable::new_inner (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x808E8B: wasmer_vm::table::LinearTable::from_definition (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E4831: <wasmer::tunables::Tunables as wasmer_engine::tunables::Tunables>::create_vm_table (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A2C7F: wasmer_engine::tunables::Tunables::create_tables (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DA2B5: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E0B4E: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6DF1F0: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D72: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==  Address 0x6f18710 is 800 bytes inside a block of size 2,560 free'd
==4347==    at 0x4C32D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x3F1FC4: <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F7339: core::ptr::drop_in_place (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F9323: alloc::sync::Arc<T>::drop_slow (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3FA0EA: <wasmer_compiler_cranelift::compiler::CraneliftCompiler as wasmer_compiler::compiler::Compiler>::compile_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DE248: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3BF06A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E07EF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A1563: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3AB0: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==  Block was alloc'd at
==4347==    at 0x4C33D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x6D3944: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6BC484: gimli::write::cfi::FrameDescriptionEntry::add_instruction (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x4E0DD7: cranelift_codegen::isa::unwind::systemv::UnwindInfo::to_fde (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F539E: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x402F4E: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x40C3C8: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E9F0A: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E8566: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x406088: rayon_core::job::StackJob<L,F,R>::run_inline (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F3548: _ZN10rayon_core4join12join_context28_$u7b$$u7b$closure$u7d$$u7d$17hdd5b099c3d4f7436E.llvm.9017103831828045350 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E8987: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347== 
==4347== Invalid write of size 4
==4347==    at 0x809058: wasmer_vm::table::LinearTable::new_inner (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x808E8B: wasmer_vm::table::LinearTable::from_definition (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E4831: <wasmer::tunables::Tunables as wasmer_engine::tunables::Tunables>::create_vm_table (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A2C7F: wasmer_engine::tunables::Tunables::create_tables (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DA2B5: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E0B4E: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6DF1F0: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D72: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==  Address 0x6f18718 is 808 bytes inside a block of size 2,560 free'd
==4347==    at 0x4C32D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x3F1FC4: <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F7339: core::ptr::drop_in_place (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F9323: alloc::sync::Arc<T>::drop_slow (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3FA0EA: <wasmer_compiler_cranelift::compiler::CraneliftCompiler as wasmer_compiler::compiler::Compiler>::compile_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DE248: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3BF06A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E07EF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A1563: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3AB0: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==  Block was alloc'd at
==4347==    at 0x4C33D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x6D3944: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6BC484: gimli::write::cfi::FrameDescriptionEntry::add_instruction (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x4E0DD7: cranelift_codegen::isa::unwind::systemv::UnwindInfo::to_fde (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F539E: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x402F4E: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x40C3C8: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E9F0A: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E8566: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x406088: rayon_core::job::StackJob<L,F,R>::run_inline (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F3548: _ZN10rayon_core4join12join_context28_$u7b$$u7b$closure$u7d$$u7d$17hdd5b099c3d4f7436E.llvm.9017103831828045350 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E8987: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347== 
==4347== Invalid read of size 4
==4347==    at 0x809154: <wasmer_vm::table::LinearTable as wasmer_vm::table::Table>::size (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x8119AB: wasmer_vm::instance::InstanceHandle::finish_instantiation (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DAC5A: wasmer_engine::artifact::Artifact::finish_instantiation (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E0BC0: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6DF1F0: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D72: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347==  Address 0x6f18718 is 808 bytes inside a block of size 2,560 free'd
==4347==    at 0x4C32D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x3F1FC4: <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F7339: core::ptr::drop_in_place (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F9323: alloc::sync::Arc<T>::drop_slow (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3FA0EA: <wasmer_compiler_cranelift::compiler::CraneliftCompiler as wasmer_compiler::compiler::Compiler>::compile_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DE248: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3BF06A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E07EF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A1563: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3AB0: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==  Block was alloc'd at
==4347==    at 0x4C33D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x6D3944: alloc::raw_vec::RawVec<T,A>::reserve (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6BC484: gimli::write::cfi::FrameDescriptionEntry::add_instruction (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x4E0DD7: cranelift_codegen::isa::unwind::systemv::UnwindInfo::to_fde (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F539E: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x402F4E: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x40C3C8: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E9F0A: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E8566: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x406088: rayon_core::job::StackJob<L,F,R>::run_inline (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3F3548: _ZN10rayon_core4join12join_context28_$u7b$$u7b$closure$u7d$$u7d$17hdd5b099c3d4f7436E.llvm.9017103831828045350 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E8987: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347== 
==4347== Conditional jump or move depends on uninitialised value(s)
==4347==    at 0x811B71: wasmer_vm::instance::InstanceHandle::finish_instantiation (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DAC5A: wasmer_engine::artifact::Artifact::finish_instantiation (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E0BC0: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6DF1F0: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D72: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== Conditional jump or move depends on uninitialised value(s)
==4347==    at 0x811B82: wasmer_vm::instance::InstanceHandle::finish_instantiation (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3DAC5A: wasmer_engine::artifact::Artifact::finish_instantiation (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6E0BC0: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x6DF1F0: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D72: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==4347== 
==4347== HEAP SUMMARY:
==4347==     in use at exit: 33,292 bytes in 156 blocks
==4347==   total heap usage: 57,797 allocs, 57,641 frees, 29,847,121 bytes allocated
==4347== 
==4347== Thread 1:
==4347== 16 bytes in 1 blocks are definitely lost in loss record 9 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EDB47: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 10 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EDC5D: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 11 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EDD7B: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 12 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EDE91: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 13 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EDFA7: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 14 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EE0BD: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 15 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EE1D3: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 16 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EE2E9: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 17 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EE3FF: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 18 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EE511: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 19 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EE623: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 20 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EE739: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 21 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EE84F: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 22 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EE965: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 23 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EEA7B: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 24 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EEB91: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 25 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EECA7: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 26 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EEDBD: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 27 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EEED3: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 28 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EEFE9: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 29 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EF0FF: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 30 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EF215: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 31 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EF32B: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 32 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EF441: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 33 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EF557: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 34 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EF669: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 35 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EF77F: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 36 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EF895: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 37 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EF9AB: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 38 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EFBD7: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 39 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2ED9B7: wasmer_wasi::get_path_open_for_store (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2EFCE8: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 40 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EFD35: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 41 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EFE4B: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 42 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EFF61: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 43 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F0077: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 44 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F018D: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 45 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F02A3: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 46 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F03B9: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 47 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F04CE: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 48 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F05E0: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 49 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F06F6: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 50 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F0809: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 51 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F091F: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 16 bytes in 1 blocks are definitely lost in loss record 52 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2F0A35: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== 1,152 bytes in 4 blocks are possibly lost in loss record 89 of 96
==4347==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==4347==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==4347==    by 0x5252227: allocate_stack (allocatestack.c:627)
==4347==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==4347==    by 0x8A242C: std::sys::unix::thread::Thread::new (thread.rs:66)
==4347==    by 0x437086: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x43A406: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x43AFBF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x43DFB6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x88D459: std::sync::once::Once::call_inner (once.rs:416)
==4347==    by 0x43A580: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x43D37B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x3E64F1: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347== 
==4347== 1,959 (16 direct, 1,943 indirect) bytes in 1 blocks are definitely lost in loss record 92 of 96
==4347==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4347==    by 0x2EFAC1: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2ED661: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2A3D01: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==4347==    by 0x2D0E4B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x2D0E4B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4347==    by 0x2D0E4B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4347==    by 0x2D0E4B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4347==    by 0x2D0E4B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4347==    by 0x2D0E4B: run_test_in_process (lib.rs:541)
==4347==    by 0x2D0E4B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4347==    by 0x2A5EE5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:475)
==4347==    by 0x2ABCB4: call_once<(),closure-0> (panic.rs:318)
==4347==    by 0x2ABCB4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4347==    by 0x2ABCB4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4347==    by 0x2ABCB4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4347==    by 0x2ABCB4: {{closure}}<closure-0,()> (mod.rs:474)
==4347==    by 0x2ABCB4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4347==    by 0x8A26F9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4347==    by 0x8A26F9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4347==    by 0x8A26F9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4347==    by 0x52516DA: start_thread (pthread_create.c:463)
==4347==    by 0x57A271E: clone (clone.S:95)
==4347== 
==4347== LEAK SUMMARY:
==4347==    definitely lost: 720 bytes in 45 blocks
==4347==    indirectly lost: 1,943 bytes in 13 blocks
==4347==      possibly lost: 1,152 bytes in 4 blocks
==4347==    still reachable: 29,477 bytes in 94 blocks
==4347==         suppressed: 0 bytes in 0 blocks
==4347== Reachable blocks (those to which a pointer was found) are not shown.
==4347== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==4347== 
==4347== For counts of detected and suppressed errors, rerun with: -v
==4347== Use --track-origins=yes to see where uninitialised values come from
==4347== ERROR SUMMARY: 281 errors from 55 contexts (suppressed: 0 from 0)
